### ISSUE TITLE
Why longjunyu2 left the team?

### ISSUE THREAD

**Issue by SevenIsNotNumber** [AOF-Dev/MCinaBox#1009]

**Comment by SevenIsNotNumber** [comment]
Also is AOF-DEV team finding a new mcinabix maintainer?

**Comment by AyHa1810** [comment]
@Iscle can you?

**Comment by AyHa1810** [comment]
I would like to maintain it, but I don't know programming yet, so I can't.

**Comment by Iscle** [comment]
I can do patches from time to time, but not maintain it regularly because of lack of time...

**Comment by SevenIsNotNumber** [comment]
R.I.P mcinabox. Only cosinemath have admin access sooo... Closing
