### ISSUE TITLE
Hitting a mob breaks every texture

### ISSUE THREAD

**Issue by Eliatshaha** [AOF-Dev/MCinaBox#1011]
I'm playing 1.12.2 version on a Samsung A21s (4gb ram) with 1024 mb ram asigned to java parameters, nice fps and the game runs almost perfect, except this. 
If I hit any mob ( or any mob hits me) then textures become black or just shattered like this (transparent ones loses its transparency like glass, grass and tools)
![Screenshot_20210307-011732_MCinaBox](https://user-images.githubusercontent.com/80188761/110230310-7971a180-7ee6-11eb-91ed-eebe33a34831.jpg)
![Screenshot_20210307-011742_MCinaBox](https://user-images.githubusercontent.com/80188761/110230314-7eceec00-7ee6-11eb-96a5-d22e1ad2c1bc.jpg)

I tried to run 1.12.2 with/without forge, optifine, these captures are the vanilla game indeed... what can I do? I just wanted to play 1.12.2 version because my favorite mods runs fine there

**Comment by Vijay96t1945** [comment]
Hitting a mob breaks every texture  same issue

**Comment by Accountuser99** [comment]
I have the same issue, to work around this I use the runtime for the previous version.

**Comment by Eliatshaha** [comment]
Thanks, I'm gonna try with a previous ver. If it fixed I'll tell you.

**Comment by Eliatshaha** [comment]
Thanks!!! It works now ^^ ( Im using p2 runtime arch64 )
