### ISSUE TITLE
Can't Install Forge 1.6.4

### ISSUE THREAD

**Issue by NBGReal** [AOF-Dev/MCinaBox#1018]
Anyone Knows a Fix?
I Need This to Work

 - Device: [Huawei Y7P]
 - OS: [Android 10]
 - App Version [v0.1.4-p5+0119]
 - CPU architecture [arm64]

**Comment by wakaru44** [comment]
that's not much detail for the devs to work with...
but maybe your issue is a duplicate of 
https://github.com/AOF-Dev/MCinaBox/issues/1045
or 
https://github.com/AOF-Dev/MCinaBox/issues/1024

**Comment by NBGReal** [comment]
> that's not much detail for the devs to work with... but maybe your issue is a duplicate of #1045 or #1024

I think that forge only works with 1.7+ and doesn't work with older versions on MCinabox.
