### ISSUE TITLE
Allow Tlauncher Auth Server?

### ISSUE THREAD

**Issue by ThatMG393** [AOF-Dev/MCinaBox#1028]
Can You Allow Tlauncher Auth Server?

![Screenshot_20210318-184818_MCinaBox](https://user-images.githubusercontent.com/73651803/111615216-6da5a980-881b-11eb-986a-8ab4e68e1d97.jpg)

In The Server When U Create An Account?

U Know, JUST MAYBE?

**Comment by LegacyGamerHD** [comment]
Not gone happen
