### ISSUE TITLE
Did you quit making mcinabox? Because mcinabox can still have a chance of beating pojav this is the og java on android pls don't quit

### ISSUE THREAD

**Issue by minerchino** [AOF-Dev/MCinaBox#1035]
1. If you have any questions, you can ask here and wait for the answers.
2. You can also post files or screenshots if it is related to the question.

**Comment by MCredbear** [comment]
>     1. If you have any questions, you can ask here and wait for the answers.
> 
>     2. You can also post files or screenshots if it is related to the question.

Don't be worry man,Longjunyu though that his programing skill was to week.So now,he is in the college,and he would be back soon.

**Comment by minerchino** [comment]
> back

Thanks for the info

**Comment by artdeell** [comment]
> og java on android

Mf doesn't know about Boardwalk

**Comment by dashboarder** [comment]
See this timeline:
- Boardwalk: 2014, proof: [here](https://github.com/zhuowei/Boardwalk/commit/4ff6b62a132c292fab9b065f83b87171ad1b6034
- mc launcher (old pojav V1 or smth ): 2018 proof: [here](https://drive.google.com/drive/u/0/mobile/folders/1Sk_GXoXmLwruPTFgVUUeYkPQ5voWHmkv?sort=13&direction=a
- pojav: 2019, Proof: [here](https://youtu.be/PgtNWWO8L04)
- Boat: 2019~2020
- mcinabox: 2020
- Other boat stuff (mio, h2o): 2020~2021

**Comment by MCredbear** [comment]
> > og java on android
> 
> Mf doesn't know about Boardwalk

?who is Mf
