### ISSUE TITLE
Minecraft Forge 1.16.5 Stuck on white screen

### ISSUE THREAD

**Issue by lightersmash1** [AOF-Dev/MCinaBox#1041]
**Describe the bug**
Minecraft Forge 1.16.5 Frozen on white screen

**To Reproduce**
Install minecraft forge and launch it

**Expected behavior**
Minecraft forge to load up and bring me to the menu area.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samaung Galaxy Tab S5
 - OS: Android 9
 - CPU arm64

**Comment by EnderTheCoder** [comment]
Turn the memory size larger, and try again.

**Comment by TSaltedfishKing** [comment]
We knew
