### ISSUE TITLE
Transparent Textures not working after entity is hit

### ISSUE THREAD

**Issue by Florianm2907** [AOF-Dev/MCinaBox#1043]
Device: Samsung Galaxy S10 Lite
Chipset: Snapdragon 855, Adreno 640, 8GB RAM
OS: Android 11

Everything works just fine until I hit a mob, then every transparent texture (f.e. grass, shadows, e.g.) 
isn't transparent anymore, everything's just "filled" with an accent color of the texture. (see images)

![WhatsApp Image 2021-03-26 at 22 09 03 (2)](https://user-images.githubusercontent.com/70763418/112692980-1be6ca00-8e80-11eb-9468-df233c3fe5bf.jpeg)
![WhatsApp Image 2021-03-26 at 22 09 03](https://user-images.githubusercontent.com/70763418/112692983-1c7f6080-8e80-11eb-8151-c5cdb039e620.jpeg)
![WhatsApp Image 2021-03-26 at 22 09 03 (1)](https://user-images.githubusercontent.com/70763418/112692984-1c7f6080-8e80-11eb-9ed2-36b4bdeded8f.jpeg)

**Comment by jianren818** [comment]
Using mcinabox v0.1.4-p2 of the runtime

**Comment by Florianm2907** [comment]
Surprisingly, I didn't even have a runtime installed, the p5 runtime also had the same problem, but the p2 runtime fixed the problem. Thanks!
