### ISSUE TITLE
Where is the runtime?

### ISSUE THREAD

**Issue by VenomousSteam81** [AOF-Dev/MCinaBox#1044]
I'm using the mobile app rn, but where is the runtime?

**Comment by jianren818** [comment]
![Screenshot_20210401_173302](https://user-images.githubusercontent.com/77053726/113274477-546b2580-9310-11eb-93cc-4baa069a1c24.jpg)
![Screenshot_20210401_173322](https://user-images.githubusercontent.com/77053726/113274486-5634e900-9310-11eb-8f81-f502bbdbb5ef.jpg)
