### ISSUE TITLE
stuck with a white screen every version

### ISSUE THREAD

**Issue by elyesishere** [AOF-Dev/MCinaBox#1060]
when i want to play normal 1.16.4, it shows me a white screen, when i take a screenshot of that, it shows me a black screen

just press the play button and hers the crash
![Screenshot_20210426-123838](https://user-images.githubusercontent.com/72686414/116077528-7e083a00-a68d-11eb-92fb-8510ee0a1442.png)

**Smartphone (please complete the following information):**
 - Device: INFINIX hot 8
 - OS: android 9
 - App Version the latest
 - CPU architecture arm64

pls help

**Comment by TSaltedfishKing** [comment]
This problem only occurs on MediaTek devices,It may be fixed in the next update
