### ISSUE TITLE
Unable to download Minecraft version, Too much resource files

### ISSUE THREAD

**Issue by hrjohbfwnfgvdamysvgsmgsbgsb** [AOF-Dev/MCinaBox#1079]
I am unable to download any Minecraft version so you have to fix this I'll stick to another Minecraft launcher so yeah your launcher is trash.

**Comment by TSaltedfishKing** [comment]
download source

**Comment by GxmerSam** [comment]
atleast more info or screenshots

**Comment by hrjohbfwnfgvdamysvgsmgsbgsb** [comment]
Download source is fine. but cannot install a version due to missing resource files, I am moving to PojavLauncher

**Comment by hrjohbfwnfgvdamysvgsmgsbgsb** [comment]
> download source

Hah, dumb, Are you literally dumb, Stop closing it , PojavLauncher is better than your lame launcher

**Comment by pojavluncher2021** [comment]
I agreem This is so stupid, Artdeell is better than your stupid asslame development
