### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by SNWCreations** [AOF-Dev/MCinaBox#1084]
I recently bought Minecraft:Java Edition .
But my computer broke down, so I used the software again.
But it seems that this software does **not** support **Microsoft account** login. Do you have any plans to support it in the future?

In addition, this software seems unable to download minecraft's resource index.

My device information:
System: MIUI 11.0.3 by Xiaomi
Mobile phone model: Redmi 5 Plus
MCinabox Version: v0.1.4 p5-0119
Region: China
Memory: 4 GB

Thanks!

**Comment by Harsh-bot-beep** [comment]
Consider Using Pojav Launcher

**Comment by Harsh-bot-beep** [comment]
It Supports Microsoft Login And Also Is BugLess Until McInaBox Team Stabilises It
