### ISSUE TITLE
Can't use 1.17

### ISSUE THREAD

**Issue by JJfriends** [AOF-Dev/MCinaBox#1085]
If I try to launch 1.17 the screen is just black is there something I need to do for it to work? I am on mcinabox v0.14-p5. I also use a samsung s8 active 1.16.4 works fine normally.

**Comment by DreamOneTop** [comment]
这是因为我们亲爱的Bugjump从20w19a这个快照开始，要求使用java16，而mcinabox使用的运行库是java8
This is because our dear Bugjump requires Java16 from the snapshot 20w19a, and the runtime library used by mcinabox is Java8.

**Comment by CosineMath** [comment]
Support for Minecraft 1.17+ in MCinaBox is incomplete.
