### ISSUE TITLE
Version 1.17 Failed to Launch due to JRE upgraded

### ISSUE THREAD

**Issue by lingxide** [AOF-Dev/MCinaBox#1091]
Hi, 

I've found that MC 1.17 is failed to launch and it seems to be the JRE changed from openjdk8 to java16. Could you please re-compile the runtime package for java16?

Many thanks.

**Comment by CosineMath** [comment]
I am waiting for openjdk17. Maybe I will have a look on openjdk16 on July. Developers of pojav have ported a under-developing openjdk can run Minecraft 21w19a+

**Comment by lingxide** [comment]
Can you share the package? I can make a test.

**Comment by atakan014** [comment]
İt is still under development bruh. U will get like 1 fps or if u are luck u will get 3

**Comment by CriticalRange** [comment]
Not only JRE version change, but also OpenGL core version changes are making it fail to launch as well

**Comment by atakan014** [comment]
![Uploading Screenshot_20210629-194039_PojavLauncher_Minecraft_Java_Edition__Android.png…]()
Here i get 99 fps on pojav

**Comment by QingSaYa** [comment]
> 在这里， 我得到 99 fps 在 pojav

Why your FPS can be so high, I installed sodium 1.16.5 only 100FPS, 1.17 my FPS is only single digits

**Comment by Saturn345** [comment]
You can try PojavLauncher because it is better than MCinabox.

**Comment by CosineMath** [comment]
Everything is ready except MCinaBox launcher. Sigh.

**Comment by lingxide** [comment]
> Everything is ready except MCinaBox launcher. Sigh.

No worry for that, it's just a game. Many thanks for your development and engagement. Merry Christmas 🎄

**Comment by CosineMath** [comment]
> > Everything is ready except MCinaBox launcher. Sigh.
> 
> No worry for that, it's just a game. Many thanks for your development and engagement. Merry Christmas 🎄

Thank you.
