### ISSUE TITLE
amd64 Release for Chromebooks

### ISSUE THREAD

**Issue by MansaceBall** [AOF-Dev/MCinaBox#1093]
I'm trying to play Minecraft MCinabox on my chromebook, but it won't work. Can you make an amd64 release somehow. If you can't it's fine, but if it is somewhat possible, can you do it

**Comment by CosineMath** [comment]
I don't have a  Chormebook. Currently PojavLauncher can be used on Android x86. MCinaBox has been abandoned, but Boat might support x86_64 later.
