### ISSUE TITLE
Sound problem

### ISSUE THREAD

**Issue by Shaik4737** [AOF-Dev/MCinaBox#1098]
**Describe the bug**

**To Reproduce**

**Expected behavior**
No sound 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Redmii note 9 ]
 - OS: [Android 10 ]
 - App Version [v0.1.4-p5-0119]
 - CPU architecture [aarch64]  

**Additional context**

**Comment by m-a-g-g** [comment]
I would like to solve the problem.

**Comment by CosineMath** [comment]
My suggestion is downloading assets including sound.
