### ISSUE TITLE
期待支持fabric！hope can support fabric

### ISSUE THREAD

**Issue by valetzx** [AOF-Dev/MCinaBox#110]
可以加载fabric但是不加载mod 希望未来版本可以支持，还有版本隔离希望也能实现。
作者np！！
this app can load fabric but cant load mod 
![1](https://user-images.githubusercontent.com/45054400/79980124-34629d80-84d5-11ea-9bf0-42b93e6cdafe.jpg)

**Comment by yejunjie10311031** [comment]
你上面这个图片是渲染问题导致的方块透视，按f11就可以解决。

**Comment by yejunjie10311031** [comment]
能不能把1.15.2fabric的下载链接发一下？

**Comment by valetzx** [comment]
> 能不能把1.15.2织物的下载链接发一下？

https://fabricmc.net/

**Comment by yejunjie10311031** [comment]
用forge安装器安装fabric时闪退

**Comment by valetzx** [comment]
> 用forge安装器安装fabric时闪退

因为他是forge安装器啊这不是很正常吗看得到我标题？？

**Comment by Jokkaj** [comment]
> 可以加载fabric但是不加载mod 希望未来版本可以支持，还有版本隔离希望也能实现。
> 作者np！！
> this app can load fabric but cant load mod
> ![1](https://user-images.githubusercontent.com/45054400/79980124-34629d80-84d5-11ea-9bf0-42b93e6cdafe.jpg)

您是如何获得1.15.2以60fps运行的
您使用什么图形配置？
How did you get 1.15.2 to work at 60fps? What video settings are you using?

**Comment by yejunjie10311031** [comment]
那你能不能把装了fabric的. minecraft文件夹用百度网盘发一下？谢谢

**Comment by valetzx** [comment]
> > 可以加载fabric但是不加载mod 希望未来版本可以支持，还有版本隔离希望也能实现。
> > 作者np！！
> > this app can load fabric but cant load mod
> > ![1](https://user-images.githubusercontent.com/45054400/79980124-34629d80-84d5-11ea-9bf0-42b93e6cdafe.jpg)
> 
> 您是如何获得1.15.2以60fps运行的
> 您使用什么图形配置？
> How did you get 1.15.2 to work at 60fps? What video settings are you using?

this is the void world and my phone is Huawei kirin980 sitting all off and lock 60fps mipmap is 3

**Comment by valetzx** [comment]
> > 可以加载fabric但是不加载mod 希望未来版本可以支持，还有版本隔离希望也能实现。
> > 作者np！！
> > this app can load fabric but cant load mod
> > ![1](https://user-images.githubusercontent.com/45054400/79980124-34629d80-84d5-11ea-9bf0-42b93e6cdafe.jpg)
> 
> 您是如何获得1.15.2以60fps运行的
> 您使用什么图形配置？
> How did you get 1.15.2 to work at 60fps? What video settings are you using?

![Screenshot_20200425_223821_com aof mcinabox](https://user-images.githubusercontent.com/45054400/80283549-ee167400-874a-11ea-99cb-0b6fa73eee0a.jpg)
![Screenshot_20200425_223826_com aof mcinabox](https://user-images.githubusercontent.com/45054400/80283551-f2db2800-874a-11ea-8198-a8bacd4a63c9.jpg)
like this

**Comment by LegacyGamerHD** [comment]
@Jokkaj dont bother touchscreen is broken

**Comment by Jokkaj** [comment]
> @Jokkaj dont bother touchscreen is broken

To fix the touchscreen you need to disable raw imput and discrete scrolling in the mouse settings inside controls.
It's not perfect but you can rotate your field of view
