### ISSUE TITLE
⏺️MCinaBox Manager for Android: producing

### ISSUE THREAD

**Issue by MatheusTGamerPro** [AOF-Dev/MCinaBox#1120]
# 🇺🇸 About
I'm developing a complete code, for managing MCinaBox, OptFine installer, Forge, and among other functions, it will support the PojavLaucher launcher too, I count on the help of Everyone.

The code is available on GitHub in Beta access, some new functions will be developed to it, below click on the name and go to the Repository!

Please, when accessing the repository, translate the page into your default language, viewing will be better and easier!

The code will receive new automatic updates, so if you can't run the code as the Tutorial says in the README, rest assured, you'll have news soon!

Even though the MCinaBox Project has ended, I plan to help those who play the Launcher still, remembering, it will have support for other Minecraft mobile launchers!

# ⏺️Code
🛡️ | **Acess**: [MLauncher - Manager](https://github.com/MatheusTGamerPro/MLauncher_MCinaBox_Manager)

# 🛎️Information...
I hope everyone's help for possible in the future to produce an Interface for the code!

**If you are going to use the manager, please wait for the release of version 2.0 so you don't get tangled up in the code execution!**

**Comment by DovydasTEDS** [comment]
Good luck, especially due to android 11's private directories.

**Comment by DovydasTEDS** [comment]
Also it is so easy to install forge/fabric/optifine on pojav
