### ISSUE TITLE
Feature Request: dragonwell JDK

### ISSUE THREAD

**Issue by LXY1226** [AOF-Dev/MCinaBox#1128]
**Is your feature request related to a problem? Please describe.**
[Dragonwell JDK](https://github.com/alibaba/dragonwell8/tree/dragonwell-8.9.10_jdk8u312-ga) shows better performance and smaller memory footprint than openjdk or oracle version on desktop platform. I hope these performance improvements can be applied here.

**Describe the solution you'd like**

Using & patching dragonwell jdk instead of dis-continued adoptjdk

**Comment by DovydasTEDS** [comment]
Use PojavLauncher

**Comment by CosineMath** [comment]
The README says "Alibaba Dragonwell JDK currently supports Linux/x86_64 platform only."
