### ISSUE TITLE
saat saya log in di pojav launcher tiba tiba error

### ISSUE THREAD

**Issue by azliasabilfathanl** [AOF-Dev/MCinaBox#1131]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy J6]
 - OS: [e.g. Android 8.1]
 - App Version [e.g. v0.1.3]
 - CPU architecture [e.g. arm64]  

**Additional context**

**Comment by CosineMath** [comment]
Then go to Pojav's repo.
