### ISSUE TITLE
[BUG+WARN] User-Agent not have set `MCinaBox/<version>` in User-Agent's Head

### ISSUE THREAD

**Issue by 8MiYile** [AOF-Dev/MCinaBox#1173]
### Is this request related to a bug?

Because our statistics found that MCinaBox uses the BMCLAPI service and does not request according to the specifications, resulting in a large number of User-Agent requests starting with Dalvik in our statistical list.
I hope you can change your User-Agent, which will facilitate our statistics.

### Describe the request.

This is a `WARNING` !
https://github.com/MCLF-CN/docs/issues/2#issuecomment-1982754824

**Comment by Sey178agame** [comment]
...

**Comment by Sey178agame** [comment]
This game is not new version.

**Comment by longjunyu2** [comment]
#213

**Comment by longjunyu2** [comment]
可以确定不是来自MCinaBox
