### ISSUE TITLE
支持ios客户端

### ISSUE THREAD

**Issue by 1234qiao** [AOF-Dev/MCinaBox#1176]
**Is your feature request related to a problem? Please describe.**
我希望能在ios设备上使用MCinaBox,像pojavLauncher

**Describe the solution you'd like**
编译一个ipa文件用于在ios设备上运行

**Describe alternatives you've considered**
无

**Additional context**
无

**Comment by TSaltedfishKing** [comment]
You should know that this project is designed for android, not intend for iOS users.
The chance to port to iOS : nearly ZERO.
