### ISSUE TITLE
Please do not submit code or fork projects at this time.

### ISSUE THREAD

**Issue by longjunyu2** [AOF-Dev/MCinaBox#121]
Increasing modularity and decoupling.Plug-in interfaces will also be provided, so there will be major changes to the code. Please do not make any changes to the project at this time.Thank you.

**Comment by lizeyan200711** [comment]
我十分期待0.1.4！尽管0.1.3版本已接近完美！

**Comment by gabbosta** [comment]
2st may

**Comment by LegacyGamerHD** [comment]
@longjunyu2 also aarch64 support

**Comment by gabbosta** [comment]
May 1st in what time zone?

**Comment by gabbosta** [comment]
Where's 0.1.4?

**Comment by gabbosta** [comment]
@longjunyu2

**Comment by longjunyu2** [comment]
For me, there are too many things to deal with. Now mcinabox's plan is to provide more customization, so that future new functions can be added to the app without updating the project. Therefore, my priority is to improve the code scalability and plug-in support, so that developers can more easily provide the functions they want for the app in the future. Of course, this includes support for future custom runtimepack. I'm sorry, but I have to put off a day to finish the priority plan.

**Comment by longjunyu2** [comment]
The original project code was too messy, and I did my best to reduce their coupling.But it took longer than I expected....

**Comment by gabbosta** [comment]
but when will version 0.1.4 be released

**Comment by gabbosta** [comment]
Day 2 or 3, Weihai time zone in China

**Comment by gabbosta** [comment]
@longjunyu2

**Comment by LegacyGamerHD** [comment]
@longjunyu2 take your time also can make a list of planed changes for 0.1.4

**Comment by gabbosta** [comment]
>but when will version 0.1.4 be released

today the 2nd in Weihai until 0:00? @longjunyu2

**Comment by lizeyan200711** [comment]
虽然0.1.4还没有发布，但可能会在这1-2周发布

Although 0.1.4 has not been released, it may be released in this 1-2 weeks

**Comment by longjunyu2** [comment]
> 虽然0.1.4还没有发布，但可能会在这1-2周发布
> 
> Although 0.1.4 has not been released, it may be released in this 1-2 weeks

NO！Why？

**Comment by lizeyan200711** [comment]
> > 虽然0.1.4还没有发布，但可能会在这1-2周发布
> > Although 0.1.4 has not been released, it may be released in this 1-2 weeks
> 
> NO！Why？

那你准备什么时候发布0.1.4，暑假后？还是完成模块化后？

**Comment by gabbosta** [comment]
> > > 虽然0.1.4还没有发布，但可能会在这1-2周发布
> > > Although 0.1.4 has not been released, it may be released in this 1-2 weeks
> > 
> > 
> > NO！Why？
> 
> 那你准备什么时候发布0.1.4，暑假后？还是完成模块化后？

Please release soon, I uninstalled mcinabox for this version and now it will take

**Comment by longjunyu2** [comment]
@lizeyan200711 
I will also take the college entrance examination in 2020. So programming has to be suspended, I'm about 60 days away. As far as I know, the latest source code is not so different from the last release in function. Why are you so worried?

**Comment by longjunyu2** [comment]
@lizeyan200711 And I've done the modularity, as shown in the previous two submissions. Now I need to concentrate on my study. Please don't submit this meaningless question so often

**Comment by lizeyan200711** [comment]
OK, I see. I wish you a good result in the 2020 college entrance examination! (I'm not worried. I'm just looking forward to it. I wish you good grades in the exam! )

**Comment by artdeell** [comment]
> @lizeyan200711
> I will also take the college entrance examination in 2020. So programming has to be suspended, I'm about 60 days away. As far as I know, the latest source code is not so different from the last release in function. Why are you so worried?

> @lizeyan200711 And I've done the modularity, as shown in the previous two submissions. Now I need to concentrate on my study. Please don't submit this meaningless question so often

@longjunyu2 
First you said that it will came out on  2st May. Then you said it will be released in 60 days.
Nice!
People needs 64-bit Runtime Packs. You may not do 0.1.4, just send your built JDK for aarch64 and someone other will pack it into runtime pack!

**Comment by gabbosta** [comment]
> > @ lizeyan200711 
> > Também farei o exame vestibular em 2020. Portanto, a programação deve ser suspensa, estou a 60 dias de distância. Até onde eu sei, o código-fonte mais recente não é tão diferente do último lançamento em função. Por que você está tão preocupado?
> 
> > @ lizeyan200711 E eu fiz a modularidade, como mostrado nas duas apresentações anteriores. Agora eu preciso me concentrar no meu estudo. Por favor, não envie essa pergunta sem sentido com tanta frequência
> 
> @ longjunyu2
> Primeiro você disse que sairia em 2 de maio. Então você disse que será lançado em 60 dias.
> Agradável!
> As pessoas precisam de pacotes de tempo de execução de 64 bits. Você não pode executar o 0.1.4, basta enviar seu JDK para aarch64 e alguém o empacotará no pacote de tempo de execução!

@longjunyu2
