### ISSUE TITLE
Fabric Installer Loader missing... README

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [AOF-Dev/MCinaBox#128]
Can you add Fabric Installer to i install Fabric Loader for running Fabric mods or how can i add Fabric Loader manually as new game profile.

**Comment by lizeyan200711** [comment]
You can download the game body and install fabric on the computer, then copy it to the mobile phone, and finally start it! This method has not been proved, you can try it

**Comment by admin-elvistrujanovic** [comment]
> You can download the game body and install fabric on the computer, then copy it to the mobile phone, and finally start it! This method has not been proved, you can try it
> 
> 
> 

I don't have a computer, so I need everything on my phone. I have heard of virtual applications running virtual Linux, Windows, MacOS ... but none worked. It's not a problem for me, I'll wait as long as I need to, but at least in one of the following updates to add this option, while many will be enabled in what I am now. My computer is black so I don't have a computer now. If you have any advice on doing this on your phone, I will gladly accept it.

**Comment by artdeell** [comment]
Umm.... i can send you my fabric installation.
From PC, of course.

**Comment by admin-elvistrujanovic** [comment]
> Umm.... i can send you my fabric installation.
> From PC, of course
I agree 

Thanks

**Comment by longjunyu2** [comment]
Can this issue be closed?

**Comment by admin-elvistrujanovic** [comment]
> Can this issue be closed?

The completed Fabric installation has yet to arrive. When she arrives, I'll close this problem.

**Comment by Universe973** [comment]
> You can download the game body and install fabric on the computer, then copy it to the mobile phone, and finally start it! This method has not been proved, you can try it

Yes it does work but you need 3gb or 4gb space.

**Comment by NicCrimson** [comment]
> Umm.... i can send you my fabric installation.
> From PC, of course.

Can you send me the file also?  I tried on my own but the fabric version does not show up when choosing a version to launch.
