### ISSUE TITLE
Minecraft 1.15.2 mouse bug fix

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [AOF-Dev/MCinaBox#140]
Minecraft 1.15.2 not working

**Comment by HomieBigSmoke** [comment]
yeah its normal, versions over 1.12.2 don't well work well...

**Comment by FrankOu2001** [comment]
It is known that 1.12.2 on some devices can't work well.(My phone is MI8 with android Q and I can perfectly play the 1.12.2 and 1.15.2). Perhaps there is something wrong with your options. You can refer to https://github.com/longjunyu2/MCinaBox/issues/24 to have your mcinabox reset. If my suggestion do nothing helpful to your problem, please upload  
> /MCinabox/BoatApp/crash.txt
to us.

**Comment by CosineMath** [comment]
Any details?

**Comment by admin-elvistrujanovic** [comment]
> It is known that 1.12.2 on some devices can't work well.(My phone is MI8 with android Q and I can perfectly play 1.12.2 and 1.15.2). Perhaps there is something wrong with your options. You can refer to https://github.com/longjunyu2/MCinaBox/issues/24 to have your mcinabox reset. If my suggestion is not helpful to your problem, please upload  
> > /MCinabox/BoatApp/crash.txt
> to us.
> 

Link to crash.txt is here:

https://drive.google.com/file/d/1c3Jrvep-P-iZ79C6VT8YVWv-EVn_J8J4/view?usp=drivesdk

Link to boat_output is here:

https://drive.google.com/file/d/1c7GfhGgFEXoDytvW4qC7fwoi1dI8ne8y/view?usp=drivesdk

**Comment by Jokkaj** [comment]
> It is known that 1.12.2 on some devices can't work well.(My phone is MI8 with android Q and I can perfectly play 1.12.2 and 1.15.2). Perhaps there is something wrong with your options. You can refer to #24 to have your mcinabox reset. If my suggestion is not helpful to your problem, please upload
> 
> > /MCinabox/BoatApp/crash.txt
> > to us.
Wait, how did you manage to get 1.15.2 working? i have Mi9 android Q and 1.15.2 lags terribly with mipmap at 1 and 2, everything is black with mipmap off
