### ISSUE TITLE
Error MC-Version-1.8 : "Invalid Session, Try Restarting your game."

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [AOF-Dev/MCinaBox#146]
Do you can fix this error in minecraft 1.8 for playing minecraft servers with cracked version of this game.

**Comment by BlueGuy25** [comment]
The Minecraft 1.8 and 1.7.10 and 1.12.2 it's crashing on my Oppo A5s

**Comment by BlueGuy25** [comment]
Did u know how to fix it??

**Comment by admin-elvistrujanovic** [comment]
> Did u know how to fix it??
> 

Do you have MCinaBox crash file for this errors?

**Comment by BlueGuy25** [comment]
Yep

**Comment by BlueGuy25** [comment]
Yep

**Comment by admin-elvistrujanovic** [comment]
> Yep

Send it Google Drive, Mega, Dropbox etc ... link to this file here.  Then the application developer will see crashes and logs so he will be able to fix the problem.

**Comment by BlueGuy25** [comment]
http://www.mediafire.com/file/n4odyf1d3fmvtiu/crash_for_my_Mcinabox_%25E2%2598%25B9%25EF%25B8%258F.zip/file
That's the link on my Mcinabox I hope u fix it 😔

**Comment by BlueGuy25** [comment]
Open the zip

**Comment by Nejitaka** [comment]
Try deleting your login in the profiles then readding it. Works for me.

**Comment by admin-elvistrujanovic** [comment]
Closing this issue because it's useless. The problem is that I used cracked account for playing mc servers - online mode servers must be played via paid account to be able to join. Session will be vaild only if you using official paid Minecraft account to play the game.
