### ISSUE TITLE
問題-讀取遊戲後一旦點擊螢幕就會跳出

### ISSUE THREAD

**Issue by Godpriest** [AOF-Dev/MCinaBox#156]
手機:Sony XA2
Android版本:9
MCinaBox apk版本: v0.1.2 & v0.1.3
登入帳號>裝了aarch32_runtime_20200328.tar.xz>然後隨便放了顆按鈕當成操作設定
使用1.15.2 / 1.15.1 / 1.12.2 都有相同問題
在進入遊戲後一旦點擊螢幕就會直接跳回選單，然後右上角驚嘆號跳出我沒有設定操作，但幾秒鐘後又恢復正常...
有沒有辦法不要檢測操作介面，因為進去的時候有看到左上角可以呼叫出預設的模擬按鈕，不然自行設定操作介面很難使用，目前還因為它直接無法遊玩...又或著我少了哪一個步驟?

**Comment by longjunyu2** [comment]
根据你的描述，我认为是mcinabox在启动1.15.2/1.15.1/1.12.2时出现了崩溃。你的配置应该是完整的。

**Comment by Godpriest** [comment]
> 根據你的描述，我認為是mcinabox在啟動1.15.2 / 1.15.1 / 1.12.2時出現了崩潰。你的配置應該是完整的。
因為我如果不點擊螢幕，我甚至能讀完Mojang Logo並看到主選單...目前只能先用遠端電腦玩了，希望之後的版本能更穩定，加油!
