### ISSUE TITLE
Why my phone cant instal the app?

### ISSUE THREAD

**Issue by zomcake** [AOF-Dev/MCinaBox#168]
Why my phone cannot instal the app? My phone version 4.4.4 Gpu MALI, Pls help i want play Minecraft Pc on my phone, can you make for All Gpu plsss :( and for all version phone plss

**Comment by artdeell** [comment]
Too old. 400 series Mali GPUs (usually installed in Android 4.x devices with MTK65xx) can't supply enough graphics performance to run Minecraft. Best result I've ever seen is somewhere around 15 fps on that GPUs.

Of couse, you CAN try it, but it will require bumping your android verson via custom firmwares.

**Comment by CosineMath** [comment]
The prebuilt apk packages we release are compiled with `minSdkVersion 21` tag, so they cannot be installed on Android 4.4 devices. 

MCinabox supports Android 4.4 devices, but you may need to build it yourself from source code.

**Comment by longjunyu2** [comment]
I agreed with @artdeell .The GPU is too old.In addition, you can not build mcinabox with ```minSdkVersion``` lower than 21.You need to delete the codes which require SDK 21.
