### ISSUE TITLE
Before when I put 1024 mb it worked, but now that I installed it again, I put 1024 mb and it crashed

### ISSUE THREAD

**Issue by gabbosta** [AOF-Dev/MCinaBox#171]

**Comment by longjunyu2** [comment]
Pity.This is a known issue,I will try to fix it.

**Comment by gabbosta** [comment]
when it released version 0.1.4 with support of more than 1024 mb

**Comment by gabbosta** [comment]
@longjunyu2

**Comment by lizeyan200711** [comment]
支持超过1024 mb的版本,似乎需要手机arm64运行库

**Comment by longjunyu2** [comment]
@lizeyan200711 兄，我这次不得不说了，支持1024+内存和运行库的架构没有关系。

**Comment by lizeyan200711** [comment]
> @ lizeyan200711兄，我这次不得不说了，支持1024+内存和运行库的架构没有关系。


好的,谢谢改正

**Comment by lizeyan200711** [comment]
> @ lizeyan200711兄，我这次不得不说了，支持1024+内存和运行库的架构没有关系。


"如果"可以支持1024+内存,但会在某些手机上无法放入1024+内存,因为某些手机有内存限制

**Comment by gabbosta** [comment]
but how can I put 1024mb?

**Comment by longjunyu2** [comment]
@gabbosta 在启动mcinabox之前，先关掉其他app来节省更多的内存。

**Comment by gabbosta** [comment]
I still couldn't put 1024mb, but before I could

**Comment by longjunyu2** [comment]
@lizeyan200711 @gabbosta 目前，mcinabox可用的内存是安卓系统限制的，是由dalvik.vm.heapsize定义的。这个是无法修改的，因此我使用了android:largeHeap="true"来增加可用内存大小，大约可以增加两倍，但是这个数值是不确定的，是由安卓系统根据当前状态定义的，所以我也不确定内存上限是多少。我会寻找一些绕过限制的办法，在以后的更新中加入的。

**Comment by Mikar9** [comment]
0.1.4 what is new ?

**Comment by Mikar9** [comment]
I download forge 1.15.2 and app is out , 0.1.4 can support ?

**Comment by azrabrijer** [comment]
@ longjunyu2 and when the bug with the mouse is fixed?

**Comment by hamid12121** [comment]
Hi, I fixed this issue
Step 1 : turn off your phone 
Step 2 : turn on your phone 
Step 3 : optimize memory (can use some clear memory) 
Step 4 : open the app 
Step 5 : set memory at 850 
Step 6 : start, if worked and didn't crash, exit it 
Step 7 :open and set memory 25m upper than before (875)
You have to 25m 25m go up to unit it crash and set it to upper memory work 
And if it not work return at step 1 
I before can use 1024 now I can up it at 1060
Step 7 : open
