### ISSUE TITLE
Now not enough items (NEI) is usable in MCinabox (1.7.10)

### ISSUE THREAD

**Issue by TataTawa** [AOF-Dev/MCinaBox#177]
ccc is a dependency of NEI. My version of ccc could run in MCinabox, which makes a lot of mod (waila nei neiaddons thaumcraft) are possible to run in MCinabox.
[CodeChickenCore-1.7.10-1.0.7.49-universal.jar.zip](https://github.com/longjunyu2/MCinaBox/files/4699654/CodeChickenCore-1.7.10-1.0.7.49-universal.jar.zip)

ccc follows MIT license. ccc main repo shows the license and Chicken-Bones have the copyright: https://github.com/Chicken-Bones/CodeChickenCore/blob/master/LICENSE.txt

**Comment by blissband123** [comment]
How do u install it

**Comment by leetmussc** [comment]
Could you edit lucraft core?

**Comment by leetmussc** [comment]
I'm sorry. I meant lucraft World.
