### ISSUE TITLE
x86 support?

### ISSUE THREAD

**Issue by Krackeen777** [AOF-Dev/MCinaBox#179]
I wanted to install a launcher, and it only works on armv7, but my Asus ZenFone 5 T00F works on Intel Atom Z2580. Can you add x86 support?

**Comment by lizeyan200711** [comment]
x86................

**Comment by CosineMath** [comment]
Although it might be in our plan, supporting x86 is of low priority level to us. 

So working on it yourself is more recommended...

**Comment by littlegao233** [comment]
using x86 platform, why don't you launch MCJE on Windows or Linux

**Comment by Ogar-the-best** [comment]
Well what if Windows or Linux is too much for that potato and he can use only Android?

**Comment by artdeell** [comment]
Well, if device is too potato for Windows or Linux, it can't run Minecraft with acceptable performance. If it's too potato for Linux, how it runs Android?
