### ISSUE TITLE
In the future you could add support for Minecraft Windows 10, since it is still different from mcpe

### ISSUE THREAD

**Issue by gabbosta** [AOF-Dev/MCinaBox#181]

**Comment by azrabrijer** [comment]
Я так не думаю . Поддержка java edition слишком не совершена . Поэтому рано думать о майнкрафт win1p edition

**Comment by serpentspirale** [comment]
I don't think adding support for non-java version of minecraft is the goal here, furthermore MC Windows 10 edition is an almost direct port of MCPE. @gabbosta

**Comment by CosineMath** [comment]
Win10 edition is not considered.
