### ISSUE TITLE
Could not allocate more ram than 1GB

### ISSUE THREAD

**Issue by Universe973** [AOF-Dev/MCinaBox#184]
![Screenshot_20200601_150959](https://user-images.githubusercontent.com/66241829/83384726-7529cc80-a41a-11ea-87fb-0bf29940b74d.JPG)
The picture above always says that when I go over 1GB of ram.
![Screenshot_20200601_150205](https://user-images.githubusercontent.com/66241829/83384828-a4403e00-a41a-11ea-8096-3f4098f8add8.jpg)
This is my set up for now.

**Comment by gabbosta** [comment]
What link is that in Advanced?

**Comment by Universe973** [comment]
Wdym?

**Comment by gabbosta** [comment]
What is written there in Advanced?

**Comment by Universe973** [comment]
Oh that. That's the JVM Argument from PC. I copy & paste the code from pc to phone with or without the JVM Argument nothing much happened. 
[Its still forcing me to play at 1gb of ram (This is without the JVM Argument)].

**Comment by gabbosta** [comment]
send it, I don't have a pc

**Comment by Universe973** [comment]
> send it, I don't have a pc

-Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

Here, that code means Minecraft will use 1GB of ram

**Comment by gabbosta** [comment]
And mine before I could use it in 1024 now I have to use it in 900

**Comment by CosineMath** [comment]
Note that the JVM arguments copied from PC won't work on Android.

**Comment by Universe973** [comment]
> Note that the JVM arguments copied from PC won't work on Android.

Yeah, its just for the style.

**Comment by serpentspirale** [comment]
@Universe973 If I remember correctly you could put anything in this field since the code doesn't take it into account (for now, maybe later ?)

**Comment by gabbosta** [comment]
@longjunyu2

**Comment by Universe973** [comment]
> @Universe973 If I remember correctly you could put anything in this field since the code doesn't take it into account (for now, maybe later ?)

Maybe idk

**Comment by leetmussc** [comment]
Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

**Comment by leetmussc** [comment]
This works. 3gb ram

**Comment by serpentspirale** [comment]
Those aren't valid java arguments ! @leetmussc did you tried them on pc beforehand ?

**Comment by leetmussc** [comment]
I used on pc through a custom mcpc launcher.

**Comment by artdeell** [comment]
> Those aren't valid java arguments ! @leetmussc did you tried them on pc beforehand ?

Those ARE valid.

**Comment by leetmussc** [comment]
Ik I used tlauncher beta to test it.

**Comment by serpentspirale** [comment]
> -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG3GC -XX:G3NewSizePercent=50 -XX:G3ReservePercent=50 -XX:MaxGCPauseMillis=80 -XX:G3HeapRegionSize=62M
> Those ARE valid.

Allow me to have a fair amount of skepticism... @leetmussc @artdeell 
Tried those arguments on my pc on 1.15.2 and optifine 1.14.4 with this result:
![image](https://user-images.githubusercontent.com/24864674/84791001-5454a000-aff2-11ea-835c-1ba3b4c31ddf.png)

**Comment by Universe973** [comment]
> > -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG3GC -XX:G3NewSizePercent=50 -XX:G3ReservePercent=50 -XX:MaxGCPauseMillis=80 -XX:G3HeapRegionSize=62M
> > Those ARE valid.
> 
> Allow me to have a fair amount of skepticism... @leetmussc @artdeell
> Tried those arguments on my pc on 1.15.2 and optifine 1.14.4 with this result:
> ![image](https://user-images.githubusercontent.com/24864674/84791001-5454a000-aff2-11ea-835c-1ba3b4c31ddf.png)

Here's the default JVM Argument:
-Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

To allocate is:
Replace the `2` with the amount of RAM you need.

For example: if you need 4GB, paste `-Xmx4G`. If you need 16GB, paste `-Xmx16G`.

**Comment by thagott** [comment]
isnt the problem caused because it is running in a 32 bits java version?

**Comment by JarlPenguin** [comment]
I could not allocate more than 956MB, otherwise the game would not start

**Comment by JarlPenguin** [comment]
Not it's decreased to 894MB. Not sure why

**Comment by lephuc0167283** [comment]
Tại sao nhỉ
