### ISSUE TITLE
Chash

### ISSUE THREAD

**Issue by guiguinho** [AOF-Dev/MCinaBox#201]
when I'm playing it comes out of nowhere

**Comment by guiguinho** [comment]
when I'm playing mcinabox crash

**Comment by guiguinho** [comment]
when I'm playing mxinabox crash

**Comment by LegacyGamerHD** [comment]
give at least a crash log ... and more info

**Comment by guiguinho** [comment]
> dê pelo menos um log de falha ... e mais informações

Mostra dando do mundo e saiu do mcinabox

**Comment by guiguinho** [comment]
> dê pelo menos um log de falha ... e mais informações

Quando estou jogando mostra saindo do mundo mas saiu e do mcinabox

**Comment by guiguinho** [comment]
When I'm play out of nowhere  coming out of the world, but it's actually coming out of Mcinabox

**Comment by CosineMath** [comment]
No log...
