### ISSUE TITLE
Don't support resourcepacks 3D??

### ISSUE THREAD

**Issue by ZeroMe905** [AOF-Dev/MCinaBox#203]
Don't support resourcepacks 3D??

**Comment by longjunyu2** [comment]
yes.I dont know.

**Comment by Universe973** [comment]
Do you mean POM or PBR?

**Comment by AjGamingPHOfficial** [comment]
Welp
I have a video about 3d resourcepack

**Comment by Universe973** [comment]
@AjGamingPHOfficial What is the vid link. I will check if it POM/PBR supported.

**Comment by Iscle** [comment]
Hi, I'm closing this issue. If you want to reopen it, please give more specific details about your issue. I don't even know what you mean by "3D resource packs".

**Comment by AjGamingPHOfficial** [comment]
https://youtu.be/HNIYCe45TKA

Here is my video!
