### ISSUE TITLE
Runtime Pack arm64 build

### ISSUE THREAD

**Issue by artdeell** [AOF-Dev/MCinaBox#21]
As i see, no Runtime Packs are builded for aarch64, this can cause significant FPS drop on 64-bit devices.

**Comment by khanhduytran0** [comment]
As you know OpenAL not work on 64-bit so might not have 64-bit packs

**Comment by artdeell** [comment]
Maybe this launcher uses other AL implementation?

**Comment by longjunyu2** [comment]
这个问题在一开始就被注意到了。所有的本地库都可以为aarch64编译，除了openjdk-8。我缺少openjdk的编译经验，按照jdk9mobile的官方文档无法进行下去。所以我在等待CosineMath的帮助，他成功的通过ndk编译了openjdk-8 aarch32。

**Comment by longjunyu2** [comment]
openjdk必须链接到安卓的linker并使用STL，这也是和boardwalk的不同之处，boardwalk依然是用了glibc

**Comment by artdeell** [comment]
@longjunyu2 this app would encounter some serious issues because of natives

> This app only has 32-bit [armeabi-v7a] native libraries. Beginning August 1, 2019 Google Play store requires
 that all apps that include native libraries must provide 64-bit versions. For more information, visit https
://g.co/64-bit-requirement

**Comment by CosineMath** [comment]
> As you know OpenAL not work on 64-bit so might not have 64-bit packs

We have tested on some 64-bits devices (We only have 32-bits build) and OpenAL library (https://github.com/kcat/openal-soft/) works fine. 
Do you mean a 64-bits build of OpenAL will not work?

**Comment by khanhduytran0** [comment]
No one tested, yes OpenAL32 works in 64-bit but a build of OpenAL32 native library in 64-bit will not work. Something like OpenAL64 will work.

**Comment by pbs666** [comment]
真的特别想要64位java的运行库，特别重要！（性能等等）

**Comment by Puqns67** [comment]
64位库很重要的，没64意味着没更大的内存支持，多mod就没希望了啊
