### ISSUE TITLE
User-Agent for BMCLAPI

### ISSUE THREAD

**Issue by bangbang93** [AOF-Dev/MCinaBox#213]
BMCLAPI using User-Agent for tracking all launchers usage information.
Now I found that there is a user-agent named `FileDownloader/1.7.7`, which cannot be identified to any known launcher. After some investigation, I found that FileDownloader is an android downloader tool, so I guess maybe this project.
Of course, you can use BMCLAPI as in the past. But it's will be my pleasure that you can follow BMCLAPI user-agent pattern. For example `mcinabox/0.1.3`

**Comment by longjunyu2** [comment]
好的，明白了。给你添麻烦了。

**Comment by bangbang93** [comment]
添麻烦算不上，我也应该在文档里补一句来着

**Comment by longjunyu2** [comment]
从 0.1.4 preview 1 开始， 修正了User-Agent

**Comment by bangbang93** [comment]
”MCinaBox/0.1.4-p3“，日志确认已修改
