### ISSUE TITLE
能不能写一个中文的使用说明？

### ISSUE THREAD

**Issue by xhemj** [AOF-Dev/MCinaBox#215]
嗯

**Comment by longjunyu2** [comment]
我不会说中文。

**Comment by xhemj** [comment]
那为什么你的change log是中文？我还以为你会中文呢，那就不用了，谢谢
Google Translate:
Why is your change log in Chinese? I thought you could speak Chinese, then you don’t need to write anymore, thank you

**Comment by longjunyu2** [comment]
No..开玩笑的。我会中文。现在我在备考，时间不多。所有的工作，包括文档完善都要等到七月中旬。

**Comment by xhemj** [comment]
顺便反馈一个问题，为什么小米手机打开后会闪退?

**Comment by MCredbear** [comment]
> 顺便反馈一个问题，为什么小米手机打开后会闪退?

权限获取没搞好，你需要先手动给它存储权限
