### ISSUE TITLE
Install apk error

### ISSUE THREAD

**Issue by ssaagamemer** [AOF-Dev/MCinaBox#216]
I click install but fail to install

**Comment by longjunyu2** [comment]
This is because that the lastest apk was only signed by v2. So some devices with Android Version lower than 7 cannot install it. You can solve it if you would like to sign it with v1 again.

**Comment by qaz6750** [comment]
可以尝试重新 签名

**Comment by ssaagamemer** [comment]
> This is because that the lastest apk was only signed by v2. So some devices with Android Version lower than 7 cannot install it. You can solve it if you would like to sign it with v1 again.

OK thanks

**Comment by qaz6750** [comment]
> > This is because that the lastest apk was only signed by v2. So some devices with Android Version lower than 7 cannot install it. You can solve it if you would like to sign it with v1 again.
> 
> OK thanks But how I sign to v1


Re-sign, I have tried it works
