### ISSUE TITLE
Restart the phone will change different amont of RAM can set

### ISSUE THREAD

**Issue by Kotarou2k4** [AOF-Dev/MCinaBox#220]
Every time I restart my phone, I can set different amount of ram in MCinabox. First time I install MCinabox i can set 800MB, but then I restarted the phone i can set it to 900MB. The next time I restart the phone I can only set it to 600MB

**Comment by longjunyu2** [comment]
Thanks. This is a known issue. Please wait for the solution.

**Comment by piotrek94692** [comment]
That's because the number of free RAM changes, when you have different number of services running in background. You can check and manage all these things in the developer settings of your phone.
