### ISSUE TITLE
Mcinabox crashes wen i preess on install to install forge mcinabox crashes

### ISSUE THREAD

**Issue by testloldhdid** [AOF-Dev/MCinaBox#223]
So i think that the newer versions of forge crash wen i try to instal them (i tryed to install the lates version of forge for the version of minecraft 1.7.10 and it crashed , wen i tryed to instal the recomeded version it didnt crash i did the same thing wen i tryed to install the forge version for 1.12.2 and the same thing happen) and some mods need the lastes forge version

**Comment by bghyt** [comment]
if you copy over the 1.7.10 or 1.12.2 forge version folder's from an installed instance on desktop it will work or you can just drag over the versions folder with every minecraft version you have on your PC onto your phone into the .minecraft folder on your phone and it should work.
