### ISSUE TITLE
Can you install the Comes Alive mod? MCA?

### ISSUE THREAD

**Issue by MarcoElNarcoXD** [AOF-Dev/MCinaBox#225]
Me and some friends, thanks to MCinaBox, we did a survival with a few mods, but the MCA fails, the question is if, if the mod is compatible in the MCinaBox, if it is not, the same thanks.

**Comment by serpentspirale** [comment]
A crash log would be appreciated, along with the version of minecraft (and forge) used, to see if there is a particular problem with MCinabox, one of its core components or just your installation ^^'

@MarcoElNarcoXD

**Comment by Dergrive** [comment]
I don't think he will respond back. And I'm interested to join the Discord

**Comment by MarcoElNarcoXD** [comment]
that happened with minecraft 1.7.10 forge.
but I just wanted to know if someone was interested in the mod, but thanks.
