### ISSUE TITLE
Mipmap 0 causes black blocks (1.16.1)

### ISSUE THREAD

**Issue by Bean3571** [AOF-Dev/MCinaBox#235]
Haven't tested on other versions
Huawei P30 Lite

**Comment by Bean3571** [comment]
[https://youtu.be/OBn5NZDNqIY](video)

**Comment by AyHa1810** [comment]
Your issue is related to this issue #24 
It is a native graphics library issue from Minecraft 1.14+.

**Comment by qaz6750** [comment]
在1.13+ 版本有渲染错误，安装高清修复也体会修复许多， 如果并没有用，可以尝试重新打开数值1到4左右

**Comment by AyHa1810** [comment]
Can't you use English to tell us? What is wrong with using english? I had to use Google translator to translate EvErY pOsT oF dIfFeReNt LaNgUaGeS other than English! 😂

**Comment by qaz6750** [comment]
> 你不能用英语告诉我们吗？使用英语有什么错？我不得不使用谷歌翻译翻译 Every 18ifferent Languages 除了英语！😂


There is a rendering error in the 1.13+ version. Installing HD repair will also experience many repairs. If it is not useful, you can try to reopen the value of about 1 to 4.

**Comment by qaz6750** [comment]
Sorry, I am a student, English is not good, but I am studying hard

**Comment by AyHa1810** [comment]
Ok don't worry. I always translate those languages.

**Comment by CosineMath** [comment]
Fixed.
