### ISSUE TITLE
Forge seems to not load some of the game resources

### ISSUE THREAD

**Issue by gaussandhisgun** [AOF-Dev/MCinaBox#237]
So, I've got my hands to MCInABox 1.0.3 with its forge installer, set it up, already tested some mods, but... Seems like Forge installed by Box completely ignore some game resources, like audios or language files. http://imgur.com/a/xWZ7ezN If I want to play on Forge I got a muted english game, while when I run it without Forge, I got translated to ru_RU game with music.

**Comment by artdeell** [comment]
well, this launcher does not handle version inheritance, so expect it to do that.

**Comment by Kotarou2k4** [comment]
The solution is simple, you can check out #94
