### ISSUE TITLE
game crash when ram>512mb

### ISSUE THREAD

**Issue by Horange321** [AOF-Dev/MCinaBox#240]
安卓9，运行内存最大512m，超过游戏就崩溃，可用物理内存还有3点几g。
是bug还是我的操作不对？望回复，谢谢

**Comment by GreenDude120** [comment]
I have the same issue. If I use anything about 512mb then the app just closes out.

**Comment by piotrek94692** [comment]
You should check developer settings of your phone, there should be an option to show currently running services, and it should say how much free RAM you have, you can't allocate more RAM than free RAM.

**Comment by Horange321** [comment]
> You should check developer settings of your phone, there should be an option to show currently running services, and it should say how much free RAM you have, you can't allocate more RAM than free RAM.

I see. Thanks for your help.

**Comment by CosineMath** [comment]
使用64位版本。
