### ISSUE TITLE
Multi-arch support

### ISSUE THREAD

**Issue by AyHa1810** [AOF-Dev/MCinaBox#244]
This is stupid! I don't know who wants it. Maybe Android users with different architectures other than arm/arm64 like x86 or x86-64 devices?

**Comment by serpentspirale** [comment]
@AyHa1810 The support of arm64 would get many devices (anything from a few years ago) a significant boost on performance.

**Comment by AyHa1810** [comment]
> @AyHa1810 The support of arm64 would get many devices (anything from a few years ago) a significant boost on performance.

Yes, you are right. And Minecraft Java Edition only requires native libraries and java runtime to work. It need to compile native libraries and JRE for Android aarch64 support.

**Comment by serpentspirale** [comment]
If only. You can't just recompile for android, since the architecture (and the way it works) is different.
If I'm wrong, I'll be glad, because it means you are able to compiles an aarch64 version of the libs and JRE.

**Comment by AyHa1810** [comment]
It's is possible. Linux has arm and aarch64 variant. Since, Android has a modified linux kernel, the source code of native libraries and JRE needs to be modified to make it work on Android.

**Comment by serpentspirale** [comment]
And that's the hard part. Feel free to create yourself an implementation for arm64 since you seems knowledgeable.

**Comment by AyHa1810** [comment]
Sorry, but I am not a programmer. I said what I know lol. I could try to learn programming but, first of all, my pc sucks. It cannot handle IDEs. Once, I tried to decompile Minecraft 1.15.2 jar with it's obfuscation maps, but because my pc is crap, it crashed. I used https://github.com/FabricMC/Enigma to decompile it. I want to both laugh and cry at this!
