### ISSUE TITLE
⚠️⚠️⚠️Minecraft 1.15.2 Crash Bugging and Performanse Bugging FIX⚠️⚠️⚠️

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [AOF-Dev/MCinaBox#248]
Please check this version to increase performance because I am waiting for 20 minutes to load and when it is loaded, and I have 3 GB RAM and 32 GB of internal memory and it is occupied only 50%. Apps don't have much, and I didn't get the SD card, so I know it's not installed on the SD card. My device is POT-LX1, I have Android 10.0 Q (EMUI 10), but it still doesn't work. Everything else works perfectly. Please specifically the app developer to pay attention to this version of the game and to this device.

I will send if you require both MCinaBox/BoatApp folder and logs from that folder as with Android/data/% MCinabox%/logs and BoatApp folder also. I expect a shorter response from the app developer. Thanks for understanding 👍

**Comment by artdeell** [comment]
Performance is limited by your device. What's your CPU/GPU?
I was able to pull out 60 stable FPS from Snapdragon 820/3GB RAM with unofficial firmware (Minecraft 1.12.2). Also, developer can't focus on one single device, since this may lead to performance degradation on other devices.

**Comment by artdeell** [comment]
Also, this particular issue is not new, 1.15.2 generally runs very slowly on all devices.

**Comment by SnowNF** [comment]
see newset version(p5)
