### ISSUE TITLE
Beta releases?

### ISSUE THREAD

**Issue by AyHa1810** [AOF-Dev/MCinaBox#250]
Since some people can't compile the latest source code, including me, beta or pre-release versions should be released.

**Comment by serpentspirale** [comment]
You can ask people who compiles the code to make their version available, however the main releases are all "stables" releases.
(And seriously, any freaking computer can compile this.)

**Comment by AyHa1810** [comment]
I don't have any access to my pc even though it's mine. Because I am a 14 y/o (freaking) student. So, compile it and give it to me. And I know that they are stable releases.

**Comment by serpentspirale** [comment]
Hey, calm down.
The latest source code isn't stable enough.
It crashes every time you open the app. (Tested this morning)
Built it with an online ide, because it was possible not to use a pc.
I can surely just work around the issue, however your behavior isn't something I would reward.

**Comment by AyHa1810** [comment]
😅 I was calm! I was not mad or angry or anything!
