### ISSUE TITLE
📢 Forge for 1.15.2 universal and full installer not working

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [AOF-Dev/MCinaBox#251]
I tryed to install Forge for minecraft 1.15.2 universal.jar file and installer.jar file but didn't worked. Did you everyone try to install Forge in 2020 for minecraft 1.15.2 - universal.jar file and installer? Can any of you fix this problem?

**Comment by BryleHelll** [comment]
Video on how ro fix it:

**Comment by BryleHelll** [comment]
https://m.youtube.com/watch?feature=youtu.be&v=oHg5SJYRHA0
