### ISSUE TITLE
Shaders Not supported

### ISSUE THREAD

**Issue by KssGamerEdits** [AOF-Dev/MCinaBox#253]
When running a shaders with GLSL MOD and activating a shaders package causes an OpenGL error, Next error:

 ERROR: Invalid program "error"

**Comment by serpentspirale** [comment]
Shaders are indeed not supported.

**Comment by bghyt** [comment]
the OpenGL that is supported is to low for shader's at the moment and not fully optimised, to expect shaders to work full stop is silly.
