### ISSUE TITLE
I can't play old versions

### ISSUE THREAD

**Issue by Werex-Upix** [AOF-Dev/MCinaBox#257]
I can not play beta versions for example beta 1.7.3 to investigate the farlands.
**If you know the solution please tell me**

**Comment by CosineMath** [comment]
Only 1.6+ are supported. beta 1.7.3 is too old.

**Comment by Werex-Upix** [comment]
but then why do they put the old versions?

**Comment by MansaceBall** [comment]
Yeah sorry. But xiaomi 8 can run old versions😑 lucky xiaomi users

**Comment by ManosSef** [comment]
No I have xiaomi 8 and old versions don't run

**Comment by MansaceBall** [comment]
I think longjunyu2 said you can run old versions on Xiaomi 8
