### ISSUE TITLE
Don't work on arm64 android 10 r29

### ISSUE THREAD

**Issue by OneGuyS** [AOF-Dev/MCinaBox#259]
Only download option are arch32 so it doesn't work on 64 system . Please compile for for arm64. Or give me another instructions.

**Comment by artdeell** [comment]
Generally, most of the SoCs actually support 32-bit instructions in
compartiblity mode. Consider checking your supported ABIs using AIDA64 (or
simillar) to have armeabi-v7a supported. If you have, just install 32-bit
runtime and don't worry.

чт, 16 июл. 2020 г., 19:08 OneGuyS <notifications@github.com>:

**Comment by OneGuyS** [comment]
But 32 bit don't work for me . If I import aarch32 app call me success install but in info I still have not installed aarch. I don't know what i'm to do

**Comment by OneGuyS** [comment]
Sorry I'm not native english

**Comment by qaz6750** [comment]
https://github.com/longjunyu2/MCinaBox/releases Please download again here, and then test whether the import is successful

**Comment by OneGuyS** [comment]
So I reinsttal files . In second try I delete files manualy.
I have mi 8 lite with pixel experience 10 I think this information could be help. When I run app I get this information : "this app is for older android version." Sorry for late comment . I manualy rebuild aarch to 64 and this not work. I don't know where is the problem. Btw Thanks for advices.

**Comment by OneGuyS** [comment]
![Screenshot_20200724-214348514](https://user-images.githubusercontent.com/64399110/88429568-2c2d3d80-cdf7-11ea-80fa-44e92d30cda0.jpg)
![Screenshot_20200724-214345642](https://user-images.githubusercontent.com/64399110/88429571-2df70100-cdf7-11ea-88b1-9a15e0a1aaca.jpg)
![Screenshot_20200724-214341671](https://user-images.githubusercontent.com/64399110/88429574-2e8f9780-cdf7-11ea-88de-d22775915ba6.jpg)
![Screenshot_20200724-214326866](https://user-images.githubusercontent.com/64399110/88429576-2fc0c480-cdf7-11ea-9928-5da471180aff.jpg)
![Screenshot_20200724-214321375](https://user-images.githubusercontent.com/64399110/88429578-30595b00-cdf7-11ea-9bfb-f2b7ef26fa14.jpg)
![Screenshot_20200724-214317673](https://user-images.githubusercontent.com/64399110/88429580-30f1f180-cdf7-11ea-8e28-51a9d2397e0b.jpg)
![Screenshot_20200724-214313760](https://user-images.githubusercontent.com/64399110/88429581-318a8800-cdf7-11ea-8616-1984a52a8cf1.jpg)
![Screenshot_20200724-214309879](https://user-images.githubusercontent.com/64399110/88429583-32231e80-cdf7-11ea-8a5d-1422c3664a60.jpg)
![Screenshot_20200724-214305648](https://user-images.githubusercontent.com/64399110/88429587-32bbb500-cdf7-11ea-9c6b-81aff08d1a34.jpg)
![Screenshot_20200724-214301202](https://user-images.githubusercontent.com/64399110/88429590-33544b80-cdf7-11ea-8465-e71d6c42764f.jpg)
![Screenshot_20200724-214255413](https://user-images.githubusercontent.com/64399110/88429594-33ece200-cdf7-11ea-8657-e69ae936f173.jpg)
![Screenshot_20200724-214250092](https://user-images.githubusercontent.com/64399110/88429597-34857880-cdf7-11ea-9b66-8ae9ec7289e3.jpg)
![Screenshot_20200724-214241520](https://user-images.githubusercontent.com/64399110/88429599-351e0f00-cdf7-11ea-8315-5440d5a0bd05.jpg)
![Screenshot_20200724-214245507](https://user-images.githubusercontent.com/64399110/88429601-364f3c00-cdf7-11ea-8c6a-1fa59fc04268.jpg)
![Screenshot_20200724-214227857](https://user-images.githubusercontent.com/64399110/88429607-36e7d280-cdf7-11ea-9ec2-90ce0a236cb4.jpg)
![Screenshot_20200724-214221206](https://user-images.githubusercontent.com/64399110/88429611-37806900-cdf7-11ea-9f8f-7863e73cc994.jpg)
![Screenshot_20200724-214154055](https://user-images.githubusercontent.com/64399110/88429612-3818ff80-cdf7-11ea-8e87-4a4b5cb0288b.jpg)
Screen for help
