### ISSUE TITLE
Support android

### ISSUE THREAD

**Issue by UIOgame1** [AOF-Dev/MCinaBox#265]
I cant install it and i think is because it does not support my android. I dont know if it true

My android is 
6.0.1
And 32 bit

**Comment by BryleHelll** [comment]
To answer your question click this link:

**Comment by BryleHelll** [comment]
https://m.youtube.com/watch?feature=youtu.be&v=oHg5SJYRHA0

**Comment by UIOgame1** [comment]
> https://m.youtube.com/watch?feature=youtu.be&v=oHg5SJYRHA0

😡

**Comment by BryleHelll** [comment]
https://github.com/khanhduytran0/PojavLauncher

**Comment by BryleHelll** [comment]
Dont try v3

**Comment by BryleHelll** [comment]
Only 2.5

**Comment by BryleHelll** [comment]
2.5.1 to be exact

**Comment by UIOgame1** [comment]
Oh okay thanks

**Comment by BryleHelll** [comment]
Sorry for rick roll 😞😞😞

**Comment by UIOgame1** [comment]
> 2.5.1 to be exact

I need help idk how to download

**Comment by BryleHelll** [comment]
Scroll down

**Comment by UIOgame1** [comment]
Then?

**Comment by BryleHelll** [comment]
See releases

**Comment by BryleHelll** [comment]
Click

**Comment by BryleHelll** [comment]
Click 2.5.1 And Click asset

**Comment by BryleHelll** [comment]
Download apk and click it after download

**Comment by BryleHelll** [comment]
Click install

**Comment by UIOgame1** [comment]
Oh thanks i tought we cant click that text lol but thank you

**Comment by BryleHelll** [comment]
Wait

**Comment by UIOgame1** [comment]
What

**Comment by BryleHelll** [comment]
Until apk installation is done

**Comment by UIOgame1** [comment]
Done

**Comment by BryleHelll** [comment]
Pojav is still buggy :(

**Comment by UIOgame1** [comment]
Can i open and play minecraft java now 😮?

**Comment by BryleHelll** [comment]
Yes

**Comment by UIOgame1** [comment]
K thanks

**Comment by BryleHelll** [comment]
Choose version 1.7.10-11.2

**Comment by BryleHelll** [comment]
Enjoyyyy😊😊😊

**Comment by BryleHelll** [comment]
Worked?
