### ISSUE TITLE
I can't install v0.1.3 on FireOS

### ISSUE THREAD

**Issue by etiennec78** [AOF-Dev/MCinaBox#268]
Hi, i found this excellent project on youtube and wanted to try it out. I installed version 0.1.2 but I cannot install v0.1.3. I have an error. I am on FireOS 5.3.6.4 (Amazon Android 5.1.1) with my Amazon Fire HD 8 6th gen.
![Screenshot_2020-07-21-00-35-33](https://user-images.githubusercontent.com/59794011/87993429-c422e280-caea-11ea-89f3-e260b2256ab3.png)

**Comment by BryleHelll** [comment]
Its for android. Fire OS and Android are different.

**Comment by BryleHelll** [comment]
Also IOS Not workinf

**Comment by etiennec78** [comment]
Fire OS is an Android with a custom interface. The system is almost the same as another Android version. It's Android 5.1.1

**Comment by BryleHelll** [comment]
I think any device lower than android 6 cant run mcinabox

**Comment by BryleHelll** [comment]
Mcinabox require high ram that average phone dont Have(Maybe)

**Comment by BryleHelll** [comment]
Try another launcher

**Comment by BryleHelll** [comment]
Pojav Work nice on your device. 😊😊😊.

**Comment by etiennec78** [comment]
Mcinabox 0.1.2 works. Another launcher? Can you give me a link please?

**Comment by etiennec78** [comment]
Ok I'll try it

**Comment by BryleHelll** [comment]
https://github.com/khanhduytran0/PojavLauncher

**Comment by BryleHelll** [comment]
Sorry because pojav cant install moda

**Comment by BryleHelll** [comment]
Dont try v3. It dont work

**Comment by etiennec78** [comment]
Ok, I am going to try V2.5.1

**Comment by BryleHelll** [comment]
You know this launcher before?

**Comment by etiennec78** [comment]
No, I view a video of mcinabox yesterday

**Comment by etiennec78** [comment]
I am downloading mc 1.8.9

**Comment by BryleHelll** [comment]
Reduce lag

**Comment by BryleHelll** [comment]
https://m.youtube.com/watch?feature=youtu.be&v=oHg5SJYRHA0

**Comment by etiennec78** [comment]
x)

**Comment by BryleHelll** [comment]
You clicked the link

**Comment by BryleHelll** [comment]
???

**Comment by etiennec78** [comment]
yes

**Comment by BryleHelll** [comment]
I rick rolled you

**Comment by BryleHelll** [comment]
Hahahaha

**Comment by etiennec78** [comment]
I finished the download

**Comment by etiennec78** [comment]
I got a crash ;/

**Comment by etiennec78** [comment]
log:   java.lang.IllegalStateException: Only one LWJGL context may be instantiated at one time.

**Comment by etiennec78** [comment]
Mojang logo :D

**Comment by BryleHelll** [comment]
What version you install

**Comment by etiennec78** [comment]
1.8.9

**Comment by BryleHelll** [comment]
Worked?

**Comment by etiennec78** [comment]
It's working!!!

**Comment by etiennec78** [comment]
I am on Hypixel

**Comment by etiennec78** [comment]
oh no :(

**Comment by etiennec78** [comment]
Crash

**Comment by BryleHelll** [comment]
Multiplayer may not work on your device

**Comment by BryleHelll** [comment]
Maybe play mcinabox 0.1.2

**Comment by etiennec78** [comment]
I can't login with my premium account on 0.1.2

**Comment by BryleHelll** [comment]
it will be fixed on v3. But some component not working........😓😓😓

**Comment by BryleHelll** [comment]
*v3 component

**Comment by BryleHelll** [comment]
Sorry if you dont like

**Comment by BryleHelll** [comment]
Ir

**Comment by etiennec78** [comment]
When will it be available?

**Comment by BryleHelll** [comment]
Until v3 is finished.(But developer is struggling)

**Comment by BryleHelll** [comment]
Developer is focusing on gl streaming

**Comment by BryleHelll** [comment]
Because its the most important part of v3

**Comment by CosineMath** [comment]
Sorry, the released apk package of 0.1.3 is not signed correctly so cannot be installed...

**Comment by SkilledHasBadPC** [comment]
Hey, how about you try resigning the 0.1.3 apk with apk editor? It didn't work for me until I resigned it. Maybe that will help.

**Comment by SkilledHasBadPC** [comment]
If you're too lazy then use this instead: http://www.mediafire.com/file/ms8k2wm687xpt8y/MCinaBox_signed.apk/file
