### ISSUE TITLE
how to increase fps on sevrerah?

### ISSUE THREAD

**Issue by ZloyDobrec** [AOF-Dev/MCinaBox#296]
version 1.12.2 optifine_mod forge everything is installed but still FPS falls if you use some mods to increase FPS, which ones?

**Comment by 18296565196** [comment]
Mobile phone configuration?

**Comment by ZloyDobrec** [comment]
> Конфигурация мобильного телефона?

did you have my device in charge? just the translator does not translate correctly if about the device then Xiaomi mi max 2
