### ISSUE TITLE
Crashes if the ram goes over the limit

### ISSUE THREAD

**Issue by LegacyGamerHD** [AOF-Dev/MCinaBox#30]
This also happens if you set the ram over 1GB on my s9+

**Comment by LegacyGamerHD** [comment]
My phone got 6GB of ram

**Comment by longjunyu2** [comment]
Android System have memory limitation for each app.I have uesd ```largeHeap=true``` to apply more memory,but it is always lower than 1024mb. And the limitation is not the same all time.I am trying to use other method to apply more memory.

**Comment by gabbosta** [comment]
> O sistema Android tem limitação de memória para cada app. É `largeHeap=true`necessário aplicar mais memória, mas ela é sempre menor que 1024mb. E a limitação não é a mesma o tempo todo. Estou tentando usar outro método para aplicar mais memória.
When will this be released

**Comment by gabbosta** [comment]
@longjunyu2

**Comment by gabbosta** [comment]
When will this be released?

**Comment by Soul-Void** [comment]
> Android System have memory limitation for each app.I have uesd ```largeHeap=true``` to apply more memory,but it is always lower than 1024mb. And the limitation is not the same all time.I am trying to use other method to apply more memory.

Old post, I know, but on the topic of allocating more ram to the app in general, I did a quick google search and found that it's possible to allocate more than the largeHeap allows by using the Android NDK. I couldn't really find too many details but many people were saying that they were using upwards of 1gb ram on apps via NDK. 

I personally don't know how difficult it may be to use the NDK in MCinabox, but I figured I'd bring it to your attention so you could look into it in the future, if you haven't already.

Looking forward to v 0.1.4, but no rush, take your time and good luck  :)

**Comment by artdeell** [comment]
> > Android System have memory limitation for each app.I have uesd `largeHeap=true` to apply more memory,but it is always lower than 1024mb. And the limitation is not the same all time.I am trying to use other method to apply more memory.
> 
> Old post, I know, but on the topic of allocating more ram to the app in general, I did a quick google search and found that it's possible to allocate more than the largeHeap allows by using the Android NDK. I couldn't really find too many details but many people were saying that they were using upwards of 1gb ram on apps via NDK.
> 
> I personally don't know how difficult it may be to use the NDK in MCinabox, but I figured I'd bring it to your attention so you could look into it in the future, if you haven't already.
> 
> Looking forward to v 0.1.4, but no rush, take your time and good luck :)

The main thing is: android does not constrain RAM for native apps.
The only limitation is ARMv7-only Java supplied with launcher that just can't adress more than 1 gig. of RAM.

**Comment by artdeell** [comment]
Apps on any 32-bits architeccture can allocate maximum of half of the address space. For ex: IA-32 can allocate 3 gigs of adress space - only 1.5 gigs is accesible to Java. ARMv7 as documentation states has 32-bit memory map which can hold up to 2 gigs of ram, so half of it is accesible to Java.
