### ISSUE TITLE
how to play mcinabox with shaderrr

### ISSUE THREAD

**Issue by KUALALUM** [AOF-Dev/MCinaBox#303]
Pls set the mcinabox opengl into 3.0 version

**Comment by jamo-lcr** [comment]
Had you Install optifine?

**Comment by KUALALUM** [comment]
I Already have optifine in my forge

**Comment by Malaska678** [comment]
No. Because all launcher use gl4es which only support up to opengl 2.0. There's regal which support up to opengl 4.0. Pojav launcher developer is trying to make regal.

**Comment by AjGamingPHOfficial** [comment]
Do u think your device can run shader???
