### ISSUE TITLE
安装forge时崩溃

### ISSUE THREAD

**Issue by tjxy0** [AOF-Dev/MCinaBox#321]
如题
系统：EMUI9. 1 Android 9. 0
游戏版本：1.7.10
forge 版本10.13.4.1448

**Comment by yejunjie10311031** [comment]
你可以尝试旧一点的forge，有些版本的最新版forge安装的确会闪退，例如1.12.2等版本，你可以去下载比较旧的forge版本。

**Comment by TSaltedfishKing** [comment]
请检查文件是否完整
