### ISSUE TITLE
关闭mipmap导致地面变黑

### ISSUE THREAD

**Issue by gamecss** [AOF-Dev/MCinaBox#323]
1.16.1版本下关闭mipmap会导致地面变黑
其他版本还没测试

**Comment by FrankOu2001** [comment]
第一次遇到关闭mipmap地面变黑是在1.16.1版本

**Comment by gamecss** [comment]
？你说的是第一次在1.16.1遇到关闭mipmap导致地面变黑吗

**Comment by MCredbear** [comment]
别问，问就是gl4es和lwjgl的问题

**Comment by JohnsonLi06** [comment]
我有解决方法，把mipmap调大点就行了

**Comment by JohnsonLi06** [comment]
我有解决方法，把mipmap调大点就行了

**Comment by gamecss** [comment]
......

**Comment by friendlyfredward** [comment]
Same thing happens to me. My solution has just been to set mipmap levels to 1, it doesn't seem to impact performance that much and this issue doesn't occur.
![image](https://user-images.githubusercontent.com/72116427/94656571-94daee00-0343-11eb-9dd9-2c8b1508bff1.png)

**Comment by gamecss** [comment]
居然发现非国人了

**Comment by gamecss** [comment]
“同样的事情也发生在我身上，我的解决方案是将mipmap设置为1，它似乎不会对性能产生太大的影响，也不会出现此问题。”

**Comment by CosineMath** [comment]
这一问题在新版可能会解决。
