### ISSUE TITLE
Switching minecraft to the background causes a crash

### ISSUE THREAD

**Issue by longjunyu2** [AOF-Dev/MCinaBox#33]

**Comment by lizeyan200711** [comment]
emmm.....

**Comment by TataTawa** [comment]
i think that this crash crashes both the game and mcinabox. it is very pain when you have a large modpack which may take several minutes to start, and switch to back ground ,and you have to reload the pack.

**Comment by 502647092** [comment]
@longjunyu2 这个有办法解决嘛
或者用悬浮窗的方式运行
虚拟大师 VMOS的之类的 就是悬浮运行了一个程序

**Comment by CosineMath** [comment]
Fixed.
