### ISSUE TITLE
How to install optifine just optifine without forge  

### ISSUE THREAD

**Issue by KUALALUM** [AOF-Dev/MCinaBox#351]
I already try this method but its not working and this is my friend he tell me the method
![Screenshot_20200825_173329](https://user-images.githubusercontent.com/67228223/91158718-a522fc00-e6f9-11ea-8ea5-0e0387438749.png)

My phone type : VIVO Y55 
model : Vivo 1603
Core : 1hz snapdragon

**Comment by KUALALUM** [comment]
This method i already try it in 1.15.2 but it just say modded and the optifine was no riggt there

**Comment by TSaltedfishKing** [comment]
what

**Comment by TSaltedfishKing** [comment]
may be we will fix

**Comment by TSaltedfishKing** [comment]
did you see wiki

**Comment by KUALALUM** [comment]
> did you see wiki

Nope

**Comment by Kotarou2k4** [comment]
I think that you can't install optifine without forge. But why you ask this ? Do you have any problem with forge ?

**Comment by KUALALUM** [comment]
> I think that you can't install optifine without forge. But why you ask this ? Do you have any problem with forge ?

Yep

**Comment by KUALALUM** [comment]
> > I think that you can't install optifine without forge. But why you ask this ? Do you have any problem with forge ?
> 
> Yep

The problem is, If open forge it will took a hour too open it

**Comment by Kotarou2k4** [comment]
> The problem is, If open forge it will took a hour too open it

I think you should have to deal with that :v
