### ISSUE TITLE
Unable to download forge

### ISSUE THREAD

**Issue by Mathimino3** [AOF-Dev/MCinaBox#353]
Hello, I'm trying to download forge but during the installation an error message appears: download failed and this with any version
![Screenshot_2020-08-25-11-41-31-817_com aof mcinabox](https://user-images.githubusercontent.com/49202827/91159899-067ea700-e6c9-11ea-93eb-9ca33ef9a374.jpg)

**Comment by TSaltedfishKing** [comment]
use first source
the 2 3is china's

**Comment by Mathimino3** [comment]
Official ?

**Comment by TSaltedfishKing** [comment]
yep

**Comment by TSaltedfishKing** [comment]
install opt,,,,
use the pc

**Comment by Mathimino3** [comment]
the official download is only for minecraft versions

**Comment by Mathimino3** [comment]
> installer opt ,,,,
> utiliser le pc

how to do ?

**Comment by TSaltedfishKing** [comment]
we are 摸鱼ing.so need time

**Comment by TSaltedfishKing** [comment]
opt.....google.com

**Comment by Mathimino3** [comment]
Okay but is there a way to install forge despite this bug?

**Comment by TSaltedfishKing** [comment]
hey,man,do you have QQ

**Comment by TSaltedfishKing** [comment]
y

**Comment by Kotarou2k4** [comment]
Don't use official download source

**Comment by Kotarou2k4** [comment]
But if that still doesn't work I think you should download that minecraft version again or check the forge file is complete download yet
