### ISSUE TITLE
Can't download other mod launchers

### ISSUE THREAD

**Issue by Basileulord** [AOF-Dev/MCinaBox#362]
I don't like that they force you to use Forge, you can't really use most of the mods because of it, I want a way to download more of them like Fabric, MCLauncher etc.

**Comment by friendlyfredward** [comment]
It could be possible to do a clean install of Minecraft on your PC and add any mods/launchers you want, then just copy the .minecraft folder to the one on the phone. This worked for me when I was testing vanilla optifine (without forge) and some older versions of Fabric
