### ISSUE TITLE
Minecraft Fabric Installer missing

### ISSUE THREAD

**Issue by HerobrineM** [AOF-Dev/MCinaBox#371]
If MCinaBox Had A Fabric Installer like you have the Forge One, we would be Installing the Sodium Mod and Get Free Access to some better Frames in the Game. This. Feature is Needed, especially for Devices That Run MCInaBox below Android 7.0.
-I Hope You add this Feature,
							Have a great Day!

**Comment by Mhowser** [comment]
I would like this feature as well please. Fabric is becoming a pretty popular modding platform.

**Comment by TSaltedfishKing** [comment]
ok

**Comment by vico93** [comment]
Just want to add Fabric is much more lightweight than Forge, so i think Fabric modpacks would have far more success to run via mcinabox than Forge.

**Comment by Bekzat123** [comment]
ПЖ ДА ФАБРИК ВКЛЮЧАЕТ МНОГО МОДОВ ДОБАВЬТЕ ФАБРИК ПЖ

**Comment by vico93** [comment]
> ПЖ ДА ФАБРИК ВКЛЮЧАЕТ МНОГО МОДОВ ДОБАВЬТЕ ФАБРИК ПЖ

Please don't conjure the Devil on my issues. Thanks.
