### ISSUE TITLE
I understand that the project is dead/close? d

### ISSUE THREAD

**Issue by Dndrix** [AOF-Dev/MCinaBox#379]
(

**Comment by Mhowser** [comment]
the latest commit was from 17 days ago, so not dead yet.

**Comment by Dndrix** [comment]
> последняя фиксация была сделана 17 дней назад, так что еще не умер.

Yes, but updates have not been released for almost six months

**Comment by Mhowser** [comment]
I saw that the next release is in the works but not planned if that makes sense. Your best bet to get a faster update is to share this project and get more developers here.

**Comment by TSaltedfishKing** [comment]
schooling..........
d not d

**Comment by Mhowser** [comment]
I don't understand what you said. Is English not your language?
