### ISSUE TITLE
where can i find the aarch64_runtime_202003228.tar.xz file

### ISSUE THREAD

**Issue by vladtheplay** [AOF-Dev/MCinaBox#388]
where can i find the aarch_runtime_202003228.tar.xz file

**Comment by vladtheplay** [comment]
my phone xiaomi mi mix 2
6 GB of RAM
9 android

**Comment by LegacyGamerHD** [comment]
https://github.com/longjunyu2/MCinaBox/releases/download/v0.1.0/aarch32_runtime_20200328.tar.xz

**Comment by vladtheplay** [comment]
aarch64 runtime .tar.xz

**Comment by LegacyGamerHD** [comment]
> aarch64 runtime .tar.xz

well there is no aarch64 run time yet

**Comment by vladtheplay** [comment]
And when there is time + -

and if not a secret of what they are doing

**Comment by FranzelDamasco909** [comment]
I tried moving the runtime to the mcinabox folder, and doesn't work

**Comment by friendlyfredward** [comment]
There is no 64-bit runtime for versions before the 0.1.4 pre-releases, you're stuck with aarch32 unless you want to try the pre-release (or wait for it to be finished)

**Comment by mcliugepi** [comment]
已经更新了，请下载。
