### ISSUE TITLE
无法安装runtime运行库

### ISSUE THREAD

**Issue by GLgele** [AOF-Dev/MCinaBox#390]
HUAWEI Mate 30 Pro
Android版本 10
内核版本 4. 14. 116
EMUI 10. 0. 0. 205
RAM 8GB
处理器 HUAWEI Kirin 990

最后是日志
无

描述：
无法在启动器内安装runtime，但可以识别到

**Comment by TSaltedfishKing** [comment]
安卓10（×运行
