### ISSUE TITLE
Asking For Android 4 version(seperate)

### ISSUE THREAD

**Issue by Malaska678** [AOF-Dev/MCinaBox#402]
I wanna try mcinabox on android 4.4.4 device of my sister. Pls.

**Comment by Malaska678** [comment]
I would try it with optifine to optimize.

**Comment by longjunyu2** [comment]
I dont know if this works.Just try it..
https://pan.baidu.com/s/1gbr0sirzz_vNCGqxjm7PJQ 
password:nbj4
Sorry that I dont know how to upload file through Github.

**Comment by AyHa1810** [comment]
@longjunyu2 you can create a different repository for only file sharing.

**Comment by Malaska678** [comment]
@longjunyu2 Upload file using we.tl. It has expiration(1 week). Its enough.

**Comment by NidzGamingTV** [comment]
@longjunyu2 upload it to gofile.io

**Comment by longjunyu2** [comment]
I will try to create a new repository to upload the apk.

**Comment by longjunyu2** [comment]
@NidzGamingTV 
I cannot explore gofile.io in China..

**Comment by longjunyu2** [comment]
https://github.com/longjunyu2/other/releases/tag/1

**Comment by AyHa1810** [comment]
@longjunyu2 for that, VPN 

> @NidzGamingTV
> I cannot explore gofile.io in China..

@longjunyu2 for that, VPN is the best option!

**Comment by AyHa1810** [comment]
> @NidzGamingTV
> I cannot explore gofile.io in China..

@longjunyu2 for that, VPN is the best option!

**Comment by LainSakura** [comment]
> 
> 
> @NidzGamingTV
> I cannot explore gofile.io in China..

i wonder how u get easy access to github since gfw sometime block it.
