### ISSUE TITLE
Longjunyu2, read it

### ISSUE THREAD

**Issue by Dndrix** [AOF-Dev/MCinaBox#404]
@longjunyu2 since you are back to development, I beg you, fix the problem of many devices, when not a single version of minecraft starts, except for 1.15.2–1.16.3. Only these versions run without problems, work on servers and the usual world and realms. My device is Huawei Honor 7A, 2Gb RAM. I do not know why this is happening, but please fix it.

**Comment by Dndrix** [comment]
During the launch of any version, except for 1.15.2-1.16.3, control buttons and a black screen appear, and then the application will exit without a crash log. And I even tried ready-made files from other devices, which launched minecraft in MCinaBox, the same effect.

**Comment by Dndrix** [comment]
Sorry, there is in Russian, but by the name I hope you will understand what and where
![Uploading Screenshot_20200927-092343.png…]()

**Comment by NidzGamingTV** [comment]
I also encounter that bug. I hope he will focus on fixing latest also the forge and optifine version though 1.16 is working, but not playable because of lag

**Comment by longjunyu2** [comment]
ok..but I will try to test on more devices to find the solulation.

**Comment by AyHa1810** [comment]
@longjunyu2 I think it's always better if you release the latest beta version for test.

**Comment by NidzGamingTV** [comment]
> @longjunyu2 I think it's always better if you release the latest beta version for test.

Indeed

**Comment by longjunyu2** [comment]
@AyHa1810 
I will release a beta version today(in China).
But I have to say that ONLY Chinese Language is full.(See the lastest commit)
And I will disable online account.(I found that it cannot worked.)
With the beta version, I will also release AArch64 Runtime for testing.
The runtime includes OpenJDK8-262-AArch64 , lwjgl2.9.3, lwjgl3.2.3 , gl4es 1.1.2 amd openal soft.(The max memory size is unlimited)

**Comment by longjunyu2** [comment]
@Dndrix Beta version uses Boat4 as back-end. So the problems may be resolved.

**Comment by AyHa1810** [comment]
@longjunyu2 although this is out of subject,  here's something  [stooopid](https://archive.org/details/microsoft-leaked-source-code-archive-2020-09-24-3d-8b-16242b_202009). 

Nah, this is probably the Microsoft leaked source code.

**Comment by AyHa1810** [comment]
@longjunyu2 btw, is `/assets/src/main/res/values/strings.xml` the MCinaBox's default language values? If it is, then I will translate it into English.

**Comment by longjunyu2** [comment]
> @longjunyu2 btw, is `/assets/src/main/res/values/strings.xml` the MCinaBox's default language values? If it is, then I will translate it into English.

yes

**Comment by gabbosta** [comment]
I am not able to click the buttons, even with that option enabled

**Comment by AyHa1810** [comment]
@longjunyu2 #408 here's the updated language. Now, compile it because I wanna see my mistakes, if I made any.

**Comment by Statsar** [comment]
@longjunyu2 this is Dndrix. Versions 1.7.10 and 1.12.2 still do not work for me. 1.15.2-1.16.3 haven't tested yet. I think the error has not been fixed yet, or I am doing something wrong. I am sending photos of what happens after the launch. First black screen, then return to home screen

**Comment by Statsar** [comment]
![Screenshot_20200928-145921](https://user-images.githubusercontent.com/64459276/94430712-062c6c80-019d-11eb-8fb8-3f2f381761db.png)

![Screenshot_20200928-145940](https://user-images.githubusercontent.com/64459276/94430760-16dce280-019d-11eb-972b-7de87b7f01f4.png)
![Screenshot_20200928-145944](https://user-images.githubusercontent.com/64459276/94430785-1f351d80-019d-11eb-8cd5-e8c1f6575fad.png)
![Screenshot_20200928-145954](https://user-images.githubusercontent.com/64459276/94430826-2825ef00-019d-11eb-8644-aa6bbde22ea9.png)
![Screenshot_20200928-145957](https://user-images.githubusercontent.com/64459276/94430841-3247ed80-019d-11eb-87b2-4b4318464c8e.png)
![Screenshot_20200928-150003](https://user-images.githubusercontent.com/64459276/94430863-3aa02880-019d-11eb-9a20-4097f1140300.png)
![Screenshot_20200928-150009](https://user-images.githubusercontent.com/64459276/94430895-44299080-019d-11eb-9afb-8a5eb9f7c258.png)

**Comment by Kotarou2k4** [comment]
@Statsar Chinese in the fifth picture said "Memory limit is too high"
