### ISSUE TITLE
How to help with the Brazilian language?

### ISSUE THREAD

**Issue by gabbosta** [AOF-Dev/MCinaBox#405]
@longjunyu2

**Comment by longjunyu2** [comment]
the language file is in assets/src/res/valuse/String.xml

**Comment by longjunyu2** [comment]
You can wait for English finished. I think.it is hard to translate Chineses  to other Language

**Comment by longjunyu2** [comment]
But it may be easier to translate English to other Language

**Comment by gabbosta** [comment]
Okay
