### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by snajdovski** [AOF-Dev/MCinaBox#409]
I can make a new logo for free and based on the license you have provided in the Project, I like Minecraft a lot, I am a Java developer too, and have already made some logos for open source projects.
I want to ask you some questions before making the logo.
1)What does MCinaBox stand for?
2)What do you want to represent in the Logo, the Game itself (Minecraft Java Edition), or the Layer you are providing to power Java version of Minecraft on Android.
3)Any color scheme that you want me to use.

**Comment by longjunyu2** [comment]
That is great!
MCinaBox just stands for Minecraft in a box. 
I think we are making a container like box to wrapper minecraft and open it on Android.
It also draws on other projects, such as BoatApp(Crossing the river between PC and Android by boat), boardwalk and bochs.
I've been working with cosine math (author of boatappp), and mcinabox was originally developed as a front-end to boatapap. So I think the icon represents the Java layer better.
In terms of color matching, I'm an idiot.XD but I prefer bright color.
I am looking forward to the new logo!

**Comment by snajdovski** [comment]
![image](https://user-images.githubusercontent.com/42580385/94421407-c9a14680-0185-11eb-846a-e89a138ea3f2.png)
![image](https://user-images.githubusercontent.com/42580385/94421449-d9208f80-0185-11eb-8d2d-6ac9ec720083.png)
The Orange Box represents Java (Java logo has orange color), you said MC in a box so I made the box orange, and also it behaves as a layer and boat, the background is a blue gradient that represents water. I can rework it if you don't like it :)

**Comment by gabbosta** [comment]
I liked

**Comment by snajdovski** [comment]
[mcinaboxsvgs.zip](https://github.com/AOF-Dev/MCinaBox/files/5291598/mcinaboxsvgs.zip)

**Comment by snajdovski** [comment]
[mcinabox_original_file_Affinity_Designer.zip](https://github.com/AOF-Dev/MCinaBox/files/5291607/mcinabox_original_file_Affinity_Designer.zip)

**Comment by AyHa1810** [comment]
@snajdovski The logo is really good! 
BTW, did you came here from Minecraft@Home's discord?

**Comment by snajdovski** [comment]
> @snajdovski The logo is really good!
> BTW, did you came here from Minecraft@Home's discord?

No, I have been following this project for a while, I found it by accident back in few months while searching for Boardwalk alternative.

**Comment by snajdovski** [comment]
Here are Screen Shots from my devices I have
Pixel 2XL:
![image](https://user-images.githubusercontent.com/42580385/94423406-dffcd180-0188-11eb-8b60-cacde83e2d5f.png)
s7 Edge:
![ss1](https://user-images.githubusercontent.com/42580385/94423434-ed19c080-0188-11eb-93d2-29c453ce9f01.png)

**Comment by snajdovski** [comment]
[Uploading res_logo_mipmaps.zip…]()

**Comment by longjunyu2** [comment]
Tge logo is really cool!
I like it!!
Thank you!
