### ISSUE TITLE
Mcinabox bugs 0.1.4 p3

### ISSUE THREAD

**Issue by pedrosouzabrasil** [AOF-Dev/MCinaBox#411]
I am trying to save keyboard and error happened ..also forge dont install using unofficial Download.
![Screenshot_20200928-104259_MCinaBox](https://user-images.githubusercontent.com/63176856/94440119-a40d4080-0177-11eb-9be6-859136b9ec81.jpg)
![Screenshot_20200928-104246_MCinaBox](https://user-images.githubusercontent.com/63176856/94440139-ac657b80-0177-11eb-8477-88ad813fe9eb.jpg)

**Comment by longjunyu2** [comment]
Forge installer works fun. You need to download `Universal` edition of forge. (Unsupport other edition now.)
And I disabled official beacuse the download speed is too low in some countries.
I don't know why you cannot import keyboard layout....(Did you use the Keyboard layout file which fits MCinaBox v0.1.3 ? The new version cannot use old keyboard layouts.)
I think you can just create a new layout and save it to file..

**Comment by pedrosouzabrasil** [comment]
I will try and send feedback..hi from brazil..

**Comment by longjunyu2** [comment]
OK, you can still open this issues if necessary. hi from china.
