### ISSUE TITLE
"Longjunyu2, read it" part 2

### ISSUE THREAD

**Issue by Statsar** [AOF-Dev/MCinaBox#412]
Версия 0.1.4 pre-3 тоже не оправдала ожидания. Кстати, при выборе обеих архитектур MCinaBox предупреждает, что она не соответствует моему устройству. Может, в этом и есть проблема?
P.s. longjunyu2, обрати внимание на мой (Dndrix) предыдущий вопрос под названием "Longjunyu2, read it", я там кое-что написал

**Comment by longjunyu2** [comment]
Hi Statsar, this is longjunyu2.
Please enable debugging and launch minecraft 1.7.10 again. Then upload the log file from `/sdcard/Android/data/com.aof.mcinabox/files/mcinabox/boatapp/boat_output.txt` and `crash.txt`.

**Comment by Statsar** [comment]
@longjunyu2, How do I enable debugging?

**Comment by Kotarou2k4** [comment]
@Statsar the last option in global setting

**Comment by Statsar** [comment]
> Привет, Статсар, это longjunyu2.
> Включите отладку и снова запустите minecraft 1.7.10. Затем загрузите файл журнала из `/sdcard/Android/data/com.aof.mcinabox/files/mcinabox/boatapp/boat_output.txt`и `crash.txt`.

[boat_output.txt](https://github.com/AOF-Dev/MCinaBox/files/5299071/boat_output.txt)

**Comment by Statsar** [comment]
@longjunyu2, crash log
[crash-2020-09-29_12.52.17-client.txt](https://github.com/AOF-Dev/MCinaBox/files/5299083/crash-2020-09-29_12.52.17-client.txt)

**Comment by SnowNF** [comment]
Sorry,your device is too old to run minecraft.
.......Your GPU does not support 24 bit depth.
..........You should use a better phone.
..............This problem might be solved in the future.

**Comment by longjunyu2** [comment]
I just wish this problem will be fixed in the future.
Do you have no patience at all???

**Comment by longjunyu2** [comment]
The best soluation for you now is to try to play mcinabox on another phone.

**Comment by Statsar** [comment]
@longjunyu2, sorry for my last exit, it was just a cry of despair. I have the same problem again. I don't understand why it's the other way round for me: versions up to 1.15.2 do not work, and after that up to 1.16.3 they start successfully (version 0.1.4pre-4). I believe that there is still some kind of error in this not on my device, otherwise nothing would work.
P.S. I will try to put forge on version 1.15.2 using a PC.
I am sorry again

**Comment by Statsar** [comment]
It's just that pojav launcher successfully launches any version, but I would like to play on mcinabox, I hope that you and your team can fix the problem like mine. I often see people with the same problem

**Comment by artdeell** [comment]
> The best soluation for you now is to try to play mcinabox on another phone.

Traditional GH mentality:
"You need this fix?
Well, no one else needs, so we're going to lower the priority and never do it"
