### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by OzzyFox** [AOF-Dev/MCinaBox#418]
I can suggest this keyboard layout (dont have another good screenshot, i'm  sorry)
![photo_2020-09-28_23-58-57](https://user-images.githubusercontent.com/67966949/94485642-ec177c00-01e6-11eb-8987-4d8d03e2182e.jpg)
But at 0.1.4 i cant install it :( Error:
![photo_2020-09-28_23-59-38](https://user-images.githubusercontent.com/67966949/94485688-fd608880-01e6-11eb-9c7a-0533d0bd1d9d.jpg)
Original file:

[keyboard.zip](https://github.com/AOF-Dev/MCinaBox/files/5295041/keyboard.zip)

**Comment by Kotarou2k4** [comment]
I think you actually need to create a new one in new version, because the new version has different custom keyboard editor so the old keyboard won't working

**Comment by ITZPGDYT** [comment]
Yes, 0.1.3 layouts do not import into 0.1.4 however i made a really good layout for 0.1.4, and it's working perfectly for the game, here you go [LAYOUT12.json](https://drive.google.com/file/d/1Nlwabozd30WtGlL9HL0oTltxSny1XDCw/view?usp=drivesdk)

**Comment by Dirk1888** [comment]
Hi, i downloaded this file an I can't use some buttons, for example can i use left click 1to 9 the f keys.
Not working are all other, wsad and other.
I can't walk with the keyboard, when i make a keyboard by myself it's the same.
Thanks
