### ISSUE TITLE
Fabric opens, but does not load mods :(

### ISSUE THREAD

**Issue by Mateus13000** [AOF-Dev/MCinaBox#419]
Fabric opens, but does not load any mods, and the background is gray.

**Comment by Malaska678** [comment]
Fabric still not working

**Comment by Mateus13000** [comment]
> Tecido ainda não funciona

![Screenshot_20200930-184107](https://user-images.githubusercontent.com/38146322/94742770-9eb51f00-034c-11eb-8e8d-19a12912700f.png)

**Comment by HerobrineM** [comment]
How did you do that? Can You Help Me do it? I really wanna see that and {1.8.9; 1.13; 1.14; 1.16; 1.16.1; 1.16.2; 1.16.3}. Don't Load Anything... NO FORGE, NO MODS. WHEN I OPEN 1.16.3 WITH FORGE MOD LOADER, IT SHOWS AS NORMAL...
