### ISSUE TITLE
[BUG] Versions older than 1.8 won't load at all.

### ISSUE THREAD

**Issue by FreddyFeuerstein** [AOF-Dev/MCinaBox#425]
Android version: 10
RAM: 4096
CPU: arm64
[latest.log](https://github.com/AOF-Dev/MCinaBox/files/5296435/latest.log)
[2020-09-29-1.log.gz](https://github.com/AOF-Dev/MCinaBox/files/5296442/2020-09-29-1.log.gz)

**Comment by Kotarou2k4** [comment]
My version 1.7.10 still working normal

**Comment by rApHaEL1211** [comment]
[Uploading latest.log…]()

**Comment by rApHaEL1211** [comment]
[2020-09-29-7.log.gz](https://github.com/AOF-Dev/MCinaBox/files/5296506/2020-09-29-7.log.gz)

**Comment by longjunyu2** [comment]
Could you upload the boat_output.txt which is in /sdcard/Android/data/com.aof.mcinabox/files/mcinabox/boatapp ? It will be more helpful.

**Comment by longjunyu2** [comment]
Did you change enabled=false in 'minecraft_home'/config/splash.properties？

**Comment by Kotarou2k4** [comment]
Oh know what it you mean, normal version older than 1.8 working normal but with forge installed will crash

**Comment by Kotarou2k4** [comment]
@longjunyu2

**Comment by SnowNF** [comment]
You should change enabled=false in 'minecraft_home'/config/splash.properties

**Comment by Kotarou2k4** [comment]
@SnowNF that's not the problem, only version older than 1.8 with forge will crash, but newer version with forge still working normal
