### ISSUE TITLE
Android 4 version not working

### ISSUE THREAD

**Issue by Malaska678** [AOF-Dev/MCinaBox#426]
It always stop. Tested on 2 android 4 device. Btw , fixing it is not priority. Framebuffer issue on normal mcinabox need fix.

**Comment by Malaska678** [comment]
I'm thinking mcinabox use ART features (only available on android 5+). On some android 4 device art can be used ,but both two don't have option to switch to ART..... ART is Better than dalvik :)

**Comment by longjunyu2** [comment]
Did you mean that mcinabox 0.1.3 could not work.on Android 4.4.4?

**Comment by SnowNF** [comment]
mcinabox use OpenJDK instead of ART/dalvik.

**Comment by Malaska678** [comment]
@SnowNF I know. Hey a developer.

**Comment by Malaska678** [comment]
> Did you mean that mcinabox 0.1.3 could not work.on Android 4.4.4?

YES. I mean mcnabox is using android 5 feature..

**Comment by CosineMath** [comment]
Boat is initially developed on Android 4.4.
