### ISSUE TITLE
Crash using aarch32 on 64bit...0.1.4 p-3(it worked on 0.1.3)

### ISSUE THREAD

**Issue by pedrosouzabrasil** [AOF-Dev/MCinaBox#429]
![Screenshot_20200929-072016_MCinaBox](https://user-images.githubusercontent.com/63176856/94547554-c65d9780-0225-11eb-8637-69ea0134b7c3.jpg)
[crash-2020-09-29_08.29.23-client.txt](https://github.com/AOF-Dev/MCinaBox/files/5298277/crash-2020-09-29_08.29.23-client.txt)

**Comment by Kotarou2k4** [comment]
New aarch64: https://github.com/AOF-Dev/MCinaBox/releases/download/v0.1.4-p2/aarch64-20200927.tar.xz

**Comment by pedrosouzabrasil** [comment]
Thanks


Em ter, 29 de set de 2020 08:02, Kotarou2k4 <notifications@github.com>
escreveu:

**Comment by longjunyu2** [comment]
If your device supports aarch64, then you can only use 0.1.4 with aarch64 runrime..
