### ISSUE TITLE
Is aaalrch 64 does not support phone aarch32

### ISSUE THREAD

**Issue by KUALALUM** [AOF-Dev/MCinaBox#432]
I like to try the new runtime because i jealous of people get 80+ fps plssssss answer my qeustion

**Comment by Kotarou2k4** [comment]
I think the new runtime pack just improve a little more performance, try to setting low using optifine

**Comment by KUALALUM** [comment]
> I think the new runtime pack just improve a little more performance, try to setting low using optifine

Stilll laggy

**Comment by Kotarou2k4** [comment]
What is your phone spec ?

**Comment by KUALALUM** [comment]
> What is your phone spec ?

![Screenshot_20200930_000004](https://user-images.githubusercontent.com/67228223/94583758-5bd04a00-026d-11eb-9be4-14414c235245.jpg)
![Uploading Screenshot_20200929_235940.jpg…]()

**Comment by KUALALUM** [comment]
> What is your phone spec ?

![Screenshot_20200930_000004](https://user-images.githubusercontent.com/67228223/94583898-7f939000-026d-11eb-9c1d-0fade1d9534e.jpg)
![Screenshot_20200929_235940](https://user-images.githubusercontent.com/67228223/94583906-81f5ea00-026d-11eb-9de4-308571a0d263.jpg)

**Comment by Kotarou2k4** [comment]
Snap 430 isn't powerful enough to play

**Comment by Kotarou2k4** [comment]
Too laggy

**Comment by pedrosouzabrasil** [comment]
I have a tab s7 (snap 865plus) 8gb ram...

**Comment by longjunyu2** [comment]
aarch64 runtime not supports aarch32 device.

**Comment by CosineMath** [comment]
Use low video settings specification of Minecraft. (e.g. low rendering distance)

64bit version works only on 64bit device and OS.
