### ISSUE TITLE
159 mods loaded! Welldone Dev team!

### ISSUE THREAD

**Issue by bghyt** [AOF-Dev/MCinaBox#435]
i can load FTB ultimate reloaded (you have to delete ALL JEI mod related .jar's for it to work)

Everything works perfectly, only the mods cause issues which is not your problem

All i wanted to say is well fucking done mate, the app works so blumin well!

Proof: 

![Screenshot_20200929-180722](https://user-images.githubusercontent.com/13301381/94591909-9c858e80-0280-11eb-8f97-6a4b10938adf.jpg)
![Screenshot_20200929-180732](https://user-images.githubusercontent.com/13301381/94591910-9d1e2500-0280-11eb-8bab-1714b755bd0c.jpg)

**Comment by bghyt** [comment]
19 FPS because i have my settings on high, i had to edit the options .txt to lower them because of a mod is causing a bug.

**Comment by bghyt** [comment]
My phone is a OnePlus 6T 8GB Ram model with 256GB storage if anyone is wondering

**Comment by hamid12121** [comment]
How do you use 5500G memory ? 
May be learn to me? 
It's just because you are using Forge mod and minecraft Forge version very slow

**Comment by bghyt** [comment]
i allocated 6gb of ram, also it was 1.12.2 99% of mods still use forge so i was force to use it, and it was slow because i had a 30+ chunk range, i put it down to 12 and i got 60FPS constant with small dips to 45 sometimes.

**Comment by longjunyu2** [comment]
Wow, that's cool!.Very glod to see this.

**Comment by hamid12121** [comment]
I can use 500000Mb memory in new version and I get 120Fps With honor 8x 6G ram 128G storage 
But I can't run liquid bounce mod , its crash !

**Comment by AyHa1810** [comment]
@hamid12121 bruh there is too much zero's for the memory! It's like 500 Gb of RAM! Wat da hel? XD

**Comment by hamid12121** [comment]
Yes I can set memory 500G
