### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by gabbosta** [AOF-Dev/MCinaBox#436]
Hello @longjunyu2 I wanted to make you a proposal, I wanted to remodel the design of your FULL application and you would pay me some amount, how many would you give for this work?

**Comment by longjunyu2** [comment]
Hello @gabbosta  I wanted to make you a proposal, I wanted to sell this project to you and you would pay me some amount, how many would you give for this project?

**Comment by by-scott** [comment]
Hello @gabbosta I wanted to make you a proposal, I wanted to sell this project to you and you would pay me some amount, how many would you give for this project?
