### ISSUE TITLE
Wehre can i find the runtime??

### ISSUE THREAD

**Issue by Terapois** [AOF-Dev/MCinaBox#441]
Download or is it in a folder in my phone??

Please help guys.

LG Justin

**Comment by foenerich** [comment]
Download from asset on github

**Comment by gamecss** [comment]
releases 0.1

**Comment by gamecss** [comment]
https://github.com/AOF-Dev/MCinaBox/releases/download/v0.1.0/aarch32_runtime_20200328.tar.xz

**Comment by gamecss** [comment]
0.4 and above
aarch32 https://github.com/AOF-Dev/MCinaBox/releases/download/v0.1.4-p2/aarch32-20200928.tar.xz
aarch64 https://github.com/AOF-Dev/MCinaBox/releases/download/v0.1.4-p2/aarch64-20200927.tar.xz
