### ISSUE TITLE
Lwjgl cause crash

### ISSUE THREAD

**Issue by Kotarou2k4** [AOF-Dev/MCinaBox#442]
I am playing normal then it crash. But it kick me out to the home srceen, not the MCinabox laucher screen. Here the crash log:
[crash-2020-09-30_10.38.37-client.txt](https://github.com/AOF-Dev/MCinaBox/files/5305183/crash-2020-09-30_10.38.37-client.txt)

**Comment by longjunyu2** [comment]
Hi. This is a known issues. I have tried to solve this. And I have found a soluation, which will reduce the change to meet this crash.
(hack lwjgl_utils.jar).
But this soluation causes anthoer crash, so it need to be improved...

**Comment by Kotarou2k4** [comment]
@longjunyu2 I have a another bug, sometimes the app will crash when you enter or create a world and it don't have any crash report
