### ISSUE TITLE
Aarch64 crash...

### ISSUE THREAD

**Issue by pedrosouzabrasil** [AOF-Dev/MCinaBox#444]
[crash-2020-09-30_16.54.27-client.txt](https://github.com/AOF-Dev/MCinaBox/files/5307095/crash-2020-09-30_16.54.27-client.txt)
...i know its  a known issue.... how to fix that?...(release date)..have a blessed day...

**Comment by hamid12121** [comment]
No same here can you fix it?

**Comment by pedrosouzabrasil** [comment]
No ..only dev
