### ISSUE TITLE
0 fps on snapdragon processor(865 plus) v 0.1.3 aarch32

### ISSUE THREAD

**Issue by pedrosouzabrasil** [AOF-Dev/MCinaBox#454]
![Screenshot_20201001-173750_MCinaBox](https://user-images.githubusercontent.com/63176856/94861356-c5875a00-040d-11eb-99b2-37ae239cdedc.jpg)
![Screenshot_20201001-174109_MCinaBox](https://user-images.githubusercontent.com/63176856/94861380-cfa95880-040d-11eb-9a17-c3a99894a5ca.jpg)

Hi..i just want to know why this only happen to snapdragon processors...i have a s20(exynos)...it is playable (20-25fps)...have a blessed day/night..edit....i tried every conf..resource pack..etc..

**Comment by hamid12121** [comment]
Well I thinking

**Comment by hamid12121** [comment]
Do you test new version and new runtime

**Comment by pedrosouzabrasil** [comment]
Yes..but 1.13 plus not suport yet..maybe its a bug idk

**Comment by hamid12121** [comment]
I know but you have to install aarch64 runtime

**Comment by hamid12121** [comment]
Hey 1.13 and 1.14 didn't work but 1.16 working

**Comment by pedrosouzabrasil** [comment]
Thanks ..but i will not close the issue...i just want to know why this happen..

**Comment by hamid12121** [comment]
Hey 1.13 and 1.14 didn't work but 1.16 working why you don't use new version

**Comment by pedrosouzabrasil** [comment]
Aarch64..dont work on 1.16.3....i tested..trust me

**Comment by hamid12121** [comment]
So what memory you set?

**Comment by pedrosouzabrasil** [comment]
On 0.1.4 p3?....i set 850

**Comment by hamid12121** [comment]
I will test it 
I will comment you after 10 minutes

**Comment by pedrosouzabrasil** [comment]
👍

**Comment by pedrosouzabrasil** [comment]
![Screenshot_20201001-181158_MCinaBox](https://user-images.githubusercontent.com/63176856/94864036-c326ff00-0411-11eb-9997-daf142b3ea94.jpg)
![Screenshot_20201001-181211_MCinaBox](https://user-images.githubusercontent.com/63176856/94864060-ce7a2a80-0411-11eb-92b1-0fcd7f1978e3.jpg)

**Comment by pedrosouzabrasil** [comment]
Now ....the new aarch32..(0.1.4p3)gives good fps but no texture

**Comment by hamid12121** [comment]
Oops what the hell ?! 
You can set mipmap to 1 and after set it back it to 0 and it will work

**Comment by pedrosouzabrasil** [comment]
I will test...

**Comment by pedrosouzabrasil** [comment]
Maybe update gl4es update the issue (snapdragon processor)...

**Comment by hamid12121** [comment]
Didn't work yes ?

**Comment by hamid12121** [comment]
> Maybe update gl4es fix the issue (snapdragon processor)...

This is very hard to create this , may be , 
Can you copy this version from your pc if installed minecraft at .minecraft folder

**Comment by hamid12121** [comment]
Did you set mipmap at 4 ?

**Comment by hamid12121** [comment]
Because I before installed this and all blocks dark 


> Did you set mipmap at 4 ?

**Comment by pedrosouzabrasil** [comment]
I will try importing .minecraft ....

**Comment by pedrosouzabrasil** [comment]
![Screenshot_20201001-182848_MCinaBox](https://user-images.githubusercontent.com/63176856/94865581-39c4fc00-0414-11eb-9b05-477a3133b614.jpg)

**Comment by pedrosouzabrasil** [comment]
![Screenshot_20201001-181211_MCinaBox](https://user-images.githubusercontent.com/63176856/94865637-53664380-0414-11eb-8d14-d3817a595ecd.jpg)

**Comment by pedrosouzabrasil** [comment]
Mipmap (1-4 )0fps

**Comment by pedrosouzabrasil** [comment]
Please @longjunyu2 enable aarch32 with updated gl4es..maybe a fix for all snapdragon processors (idk)...if it is a solution

**Comment by hamid12121** [comment]
Hmmmm.... I will fix this issue nearly

**Comment by pedrosouzabrasil** [comment]
Can you share the aarch32 ...friend ?i wait..

**Comment by pedrosouzabrasil** [comment]
@hamid12121

**Comment by hamid12121** [comment]
Yes but why?

**Comment by pedrosouzabrasil** [comment]
Only to test ,...i will be very happy

**Comment by hamid12121** [comment]
New version : https://github.com/AOF-Dev/MCinaBox/releases/download/v0.1.4-p2/aarch32-20200928.tar.xz

**Comment by hamid12121** [comment]
Old version : https://github.com/AOF-Dev/MCinaBox/releases/download/v0.1.0/aarch32_runtime_20200328.tar.xz

**Comment by pedrosouzabrasil** [comment]
I tested both dont work..need to update something inside aarch32_runtime_20200328.tar.xz(gl4es)

**Comment by hamid12121** [comment]
I will fix this

**Comment by pedrosouzabrasil** [comment]
Ok..

**Comment by pedrosouzabrasil** [comment]
Really appreciate your effort..

**Comment by friendlyfredward** [comment]
I had a similar problem with 1.16.2 with the textures not loading, I was able to get around 40fps with mipmap levels set to 1 and the textures loaded

![Screenshot_20200818_125727_com.aof.mcinabox.jpg](https://user-images.githubusercontent.com/72116427/94879511-bbb03600-04a3-11eb-889e-ea50363f925c.jpg)

**Comment by friendlyfredward** [comment]
I also noticed that the fps is 0 after joining a world but refreshing textures after a few seconds fixes it. Press F3+T on the virtual keyboard

**Comment by pedrosouzabrasil** [comment]
Impossible..
![Screenshot_20201002-013641_MCinaBox](https://user-images.githubusercontent.com/63176856/94889130-8549cb00-0451-11eb-9787-bdfda3c807c2.jpg)
![Screenshot_20201002-013751_MCinaBox](https://user-images.githubusercontent.com/63176856/94889149-8da20600-0451-11eb-9872-f950afe148d4.jpg)
![Screenshot_20201002-013909_MCinaBox](https://user-images.githubusercontent.com/63176856/94889155-95fa4100-0451-11eb-91b3-2adf7e4f4df8.jpg)

**Comment by friendlyfredward** [comment]
![image](https://user-images.githubusercontent.com/72116427/94889937-3176ca80-04c1-11eb-838c-6860bd839c08.png)
Change this to 1, your textures will come back.

**Comment by pedrosouzabrasil** [comment]
Yes ..but 0fps

**Comment by pedrosouzabrasil** [comment]
Thanks for the tip..already know that

**Comment by pedrosouzabrasil** [comment]
You  used the original aarch32...?

**Comment by friendlyfredward** [comment]
Yes, `aarch32_runtime_20200328.tar.xz` with 1.16.2. I get 0fps initially but after doing F3+T it goes up. I'll see if I can recreate this and record a video.

**Comment by pedrosouzabrasil** [comment]
Thanks for help..

**Comment by friendlyfredward** [comment]
I just completely removed everything - reinstalled MCinaBox 0.1.3 from scratch, copied in my old keyboard layout and imported the original aarch32 runtime. Vanilla 1.16.2 (not 1.16.3 because I wanted to test on a server that still runs on 1.16.2, but I doubt there'd be much difference between the two versions) worked fine at around 40fps on all the default settings (fancy graphics, 8 chunk render distance, maximum smooth lighting) except I just had to disable raw mouse input to fix the movement bug.

[**Here's a video of everything I did.**](http://mcinabox.fredward.xyz/1.16.2-demo.mp4) I'm on a Huawei Mate 20 Pro, Kirin 980. I do actually remember having this 0fps issue before and the way I fixed it was by changing some random thing in the render settings (doesn't matter what it is, just anything that forces the game to reload) and pressing F3+T. Now the issue seems to have gone entirely, so maybe just try reinstalling it? I also recommend lowering your screen resolution in device settings, 2560x1660 is higher than most desktop monitors, you definitely don't need to be rendering the game in such high detail.

**Comment by hamid12121** [comment]
may be this is an Bug... 
this will fix when new runtime come out

**Comment by pedrosouzabrasil** [comment]
Thanks for the vídeo....

**Comment by pedrosouzabrasil** [comment]
Like i said on mediatek ,kirin and exynos the game works fine.

**Comment by HerobrineM** [comment]
How do I Get Sodium Mod to work on Minecraft 1.16.2?

**Comment by HerobrineM** [comment]
Is there a way? I really wanna get some fps. It runs at 27 (max)! And it just runs  like an Idiot! SOMETIMES 0 frames and sometimes 24 frames and if I am lucky 27 fps...

**Comment by KUALALUM** [comment]
> ![Screenshot_20201001-173750_MCinaBox](https://user-images.githubusercontent.com/63176856/94861356-c5875a00-040d-11eb-99b2-37ae239cdedc.jpg)
> ![Screenshot_20201001-174109_MCinaBox](https://user-images.githubusercontent.com/63176856/94861380-cfa95880-040d-11eb-9a17-c3a99894a5ca.jpg)
> 
> Hi..i just want to know why this only happen to snapdragon processors...i have a s20(exynos)...it is playable (20-25fps)...have a blessed day/night..edit....i tried every conf..resource pack..etc..

Can u give me this runtime

**Comment by pedrosouzabrasil** [comment]
I cannot share the file here (over 10mb)but..i can share the archive that is diferent inside of aarch32_runtime_20200328.tar.xz...

[libGL.so.1.zip](https://github.com/AOF-Dev/MCinaBox/files/5320078/libGL.so.1.zip)

Erase .zip..

**Comment by KUALALUM** [comment]
> I cannot share the file here (over 10mb)but..i can share the archive that is diferent inside of aarch32_runtime_20200328.tar.xz...
> 
> [libGL.so.1.zip](https://github.com/AOF-Dev/MCinaBox/files/5320078/libGL.so.1.zip)
> 
> Erase .zip..
> 
> It update gl4es...and fixes textures ( mipmap 0) ...but still 0 fps

Thx

**Comment by KUALALUM** [comment]
Its say this how
![Screenshot_20201003_051032](https://user-images.githubusercontent.com/67228223/94970463-4beb8b00-0537-11eb-9db0-c10ee3c5f061.jpg)

**Comment by KUALALUM** [comment]
how
![Screenshot_20201003_052502](https://user-images.githubusercontent.com/67228223/94971285-47c06d00-0539-11eb-9ec2-22a741e7eece.jpg)
![Screenshot_20201003_052458](https://user-images.githubusercontent.com/67228223/94971295-4a22c700-0539-11eb-885a-6eb8621eca0d.jpg)

**Comment by KUALALUM** [comment]
> I cannot share the file here (over 10mb)but..i can share the archive that is diferent inside of aarch32_runtime_20200328.tar.xz...
> 
> [libGL.so.1.zip](https://github.com/AOF-Dev/MCinaBox/files/5320078/libGL.so.1.zip)
> 
> Erase .zip..
> 
> It update gl4es...and fixes textures ( mipmap 0) ...but still 0 fps

Can u share the runtime by using media fire

**Comment by pedrosouzabrasil** [comment]
Ok wait

**Comment by pedrosouzabrasil** [comment]
http://www.mediafire.com/file/ksf38cl6h7jlgor/aarch32_runtime_20200830.tar.xz/file

**Comment by KUALALUM** [comment]
> http://www.mediafire.com/file/ksf38cl6h7jlgor/aarch32_runtime_20200830.tar.xz/file

is this runtime can use in 0.1.4

**Comment by pedrosouzabrasil** [comment]
Yes ...try

**Comment by pedrosouzabrasil** [comment]
@longjunyu2 ...

**Comment by CosineMath** [comment]
Maybe snap 865 has some shortcomings. We try to fix this by ignoring mipmap in new version. 

Please just close 454.

**Comment by pedrosouzabrasil** [comment]
Ok i will thanks

**Comment by pedrosouzabrasil** [comment]
How to ignored mipmap on v0.1.3?change line code ?please tell me

**Comment by pedrosouzabrasil** [comment]
After that i will close issue
