### ISSUE TITLE
MCinabox 0.1.4 how can I install Forge

### ISSUE THREAD

**Issue by OGO06** [AOF-Dev/MCinaBox#455]
Whenever I try install forge I get this error

![Screenshot_2020-10-02-11-34-38-097_com.aof.mcinabox.jpg](https://user-images.githubusercontent.com/66295090/94903980-45133880-04a3-11eb-894f-72859ab222dd.jpg)

**Comment by OGO06** [comment]
> Forge yüklemeyi denediğimde bu hatayı alıyorum
> 
> ![Screenshot_2020-10-02-11-34-38-097_com.aof.mcinabox.jpg](https://user-images.githubusercontent.com/66295090/94903980-45133880-04a3-11eb-894f-72859ab222dd.jpg)

Oh sorry i forget chance server 😄😄

**Comment by NicCrimson** [comment]
> > Forge yüklemeyi denediğimde bu hatayı alıyorum
> > ![Screenshot_2020-10-02-11-34-38-097_com.aof.mcinabox.jpg](https://user-images.githubusercontent.com/66295090/94903980-45133880-04a3-11eb-894f-72859ab222dd.jpg)
> 
> Oh sorry i forget change server 😄😄

Did you get through? Cause I switched servers but the app crashes.
