### ISSUE TITLE
Forge installer Location for mcinabox 0.1.4

### ISSUE THREAD

**Issue by Tayoikoo** [AOF-Dev/MCinaBox#458]
Is there a forge installer folder? I cannot find in gamedir.

![Screenshot_20201003_045715](https://user-images.githubusercontent.com/67594827/94973230-4ee57c00-0535-11eb-9daf-d434e5493c6c.jpg)

**Comment by Mateus13000** [comment]
Go to; Android/data/com.aof.mcinabox/files/Mcinabox/forge and put the forge installer!!!
If the installer does not work, try the universal
