### ISSUE TITLE
minecraft 1.7.10 with forge does not work

### ISSUE THREAD

**Issue by Lucasma123** [AOF-Dev/MCinaBox#459]
every time I try to play he leaves

**Comment by leetmussc** [comment]
Yeah same

**Comment by SnowNF** [comment]
please give a log.

**Comment by Kotarou2k4** [comment]
@SnowNF every version below 1.8 will crash if you using forge but normal version still working, and it don't give crash report or log

**Comment by longjunyu2** [comment]
I have fixed this bug. See #398 . Please wait for p4, or you can build the project by your self.
I still have another solution.
You can open the [version-forge].json, such as ```1.7.10-Forge10.13.4.1558-1.7.10.json```.
Then you need to search `guava` in the file.
Then you will find `guava` and remember its version, such as `17.0`
Then you need to open [version.json], such as ```1.7.10.json```, and search `guava` in it.
Finially, you need to change all versions of guava to forge's and save the file.

**Comment by leetmussc** [comment]
That didn't work

**Comment by longjunyu2** [comment]
> That didn't work

ok, then please wait for p4. I am sure that the commit works.

**Comment by Kotarou2k4** [comment]
@longjunyu2 it's worked, now i can play 1.7.10 with forge

**Comment by leetmussc** [comment]
Yes, same I fixed it and now forge can run

**Comment by longjunyu2** [comment]
ok

**Comment by RaydanOMGr** [comment]
> I have fixed this bug. See #398 . Please wait for p4, or you can build the project by your self.
> I still have another solution.
> You can open the [version-forge].json, such as `1.7.10-Forge10.13.4.1558-1.7.10.json`.
> Then you need to search `guava` in the file.
> Then you will find `guava` and remember its version, such as `17.0`
> Then you need to open [version.json], such as `1.7.10.json`, and search `guava` in it.
> Finially, you need to change all versions of guava to forge's and save the file.

It dont works, but i dont like update to p4 cause the text field dont works
