### ISSUE TITLE
無法登錄正版帳號

### ISSUE THREAD

**Issue by Shuaiouke** [AOF-Dev/MCinaBox#463]
一加7pro
Android 10
8Gb
SD855

任何官方登錄都會被認成以登錄email為用戶名的線下帳號
![Screenshot_20201004-024848__01](https://user-images.githubusercontent.com/47144701/94999489-4a2fcf00-05ec-11eb-9207-c37a397d9880.jpg)
![Screenshot_20201004-024844__01](https://user-images.githubusercontent.com/47144701/94999493-4d2abf80-05ec-11eb-8009-394d90666b3a.jpg)

**Comment by Shuaiouke** [comment]
手機沒法加label

**Comment by hamid12121** [comment]
Don't use online mod

**Comment by Shuaiouke** [comment]
Wait what online mod

**Comment by NidzGamingTV** [comment]
There's still a bug using online method/Genuin login wait for the next release

**Comment by NidzGamingTV** [comment]
You can use online using forge version and Reauth mod

**Comment by longjunyu2** [comment]
我本来认为登陆的bug已经在0.1.4-p3解决了，但是后来我发现0.1.4-p3并没有完全解决，实际上登陆功能真正得到修复的commit在0.1.4-p3之后。 我看到discord上有人放出了包含登陆功能的版本(比p3要新)，如果需要的话，你可以去找找看。或者你可以等待p4。
