### ISSUE TITLE
Minecraft :'( pls help

### ISSUE THREAD

**Issue by ACHREF999** [AOF-Dev/MCinaBox#468]
please help me fix this bug 
all blocks are black 
any version higher than 1.14.4 have this bug 
i can play on 1.14.4 but not on any higher version
tried tweaking mipmaps ,update graphic driver ,tried to paste  1.14.4 tags folder in the 1.16.3 tried to uninstal and reinstall it plenty of times 
but once i tried another computer i think it worked 
I WOULD BE VERY THANKFULL IF SOMEONE HELPS! i didnt play for real minecraft since december  it  is almost a year  and im frustrated pls help me 
PS:i currently cant access the other computer for a long time probably 
![2020-10-03_23 55 49](https://user-images.githubusercontent.com/72345032/95017082-ef7b8f00-064e-11eb-9a60-f40f96376180.png)
![2020-10-03_23 55 52](https://user-images.githubusercontent.com/72345032/95017083-f0acbc00-064e-11eb-9aae-febe3448ffca.png)

![2020-10-03_23 53 33](https://user-images.githubusercontent.com/72345032/95017022-ae837a80-064e-11eb-888f-6f1d98b05edd.png)
![2020-10-03_23 53 38](https://user-images.githubusercontent.com/72345032/95017025-b3e0c500-064e-11eb-89d3-adc50fdedde7.png)
![2020-10-03_23 53 41](https://user-images.githubusercontent.com/72345032/95017030-b80ce280-064e-11eb-89ef-eb1a7afdc440.png)
![2020-10-03_23 53 53](https://user-images.githubusercontent.com/72345032/95017032-bc390000-064e-11eb-98bc-cc21ed07c0f7.png)
![2020-10-03_23 53 56](https://user-images.githubusercontent.com/72345032/95017034-bf33f080-064e-11eb-9195-00ad08e6c764.png)
![2020-10-03_23 54 01](https://user-images.githubusercontent.com/72345032/95017037-c22ee100-064e-11eb-905d-376c73ab8b1c.png)
![2020-10-03_23 54 09](https://user-images.githubusercontent.com/72345032/95017042-c5c26800-064e-11eb-8e1f-c044fe0322c7.png)
![2020-10-03_23 54 18](https://user-images.githubusercontent.com/72345032/95017045-c8bd5880-064e-11eb-9a3c-7602339224a6.png)
![2020-10-03_23 54 21](https://user-images.githubusercontent.com/72345032/95017047-cb1fb280-064e-11eb-98d9-7f41ee8e2e69.png)
![2020-10-03_23 54 26](https://user-images.githubusercontent.com/72345032/95017053-cfe46680-064e-11eb-8b82-999869c45a76.png)
![2020-10-03_23 54 29](https://user-images.githubusercontent.com/72345032/95017055-d246c080-064e-11eb-8d40-8f230933e394.png)
![2020-10-03_23 54 37](https://user-images.githubusercontent.com/72345032/95017057-d4a91a80-064e-11eb-8209-16d9efe6118d.png)

![2020-10-03_23 55 18](https://user-images.githubusercontent.com/72345032/95017072-e985ae00-064e-11eb-8103-c0c468e8fa59.png)
![2020-10-03_23 55 20](https://user-images.githubusercontent.com/72345032/95017077-eb4f7180-064e-11eb-983e-9a1a21a5b8d5.png)
![2020-10-03_23 55 31](https://user-images.githubusercontent.com/72345032/95017078-ec809e80-064e-11eb-9d04-5ed47b2de23f.png)
![2020-10-03_23 55 47](https://user-images.githubusercontent.com/72345032/95017081-edb1cb80-064e-11eb-8204-e769d69e064e.png)

**Comment by ACHREF999** [comment]
when you see the lava the mipmaps are on 3 i guess

**Comment by ACHREF999** [comment]
up
up 
up

**Comment by ACHREF999** [comment]
up up up up upup

**Comment by ACHREF999** [comment]
a pc version btw

**Comment by Kotarou2k4** [comment]
You should try versions older than 1.13,  and also you will need a high specs phone to run 1.14+ smooth. They are trying to fix graphic bug on 1.14+ so you need to wait

**Comment by ACHREF999** [comment]
im not on the phone
on pc

**Comment by ACHREF999** [comment]
its on a pc
a pc version on a pc
