### ISSUE TITLE
Mcinabox Discord Server

### ISSUE THREAD

**Issue by NidzGamingTV** [AOF-Dev/MCinaBox#471]
We need an official Discord server handled by @longjunyu2 so that we may able to help new users a guide and give other a support.

**Comment by TSaltedfishKing** [comment]
ee

**Comment by longjunyu2** [comment]
Hi. This is a good idea. I 'd like to handle an office Discord server. 
But I do not know why I can not open the website of discord.

**Comment by longjunyu2** [comment]
I even can not download the Discord app..
It says I can download it from Google Play, but HUAWEI seems to not support Google Play.
And I can not open the website of Google Play either..

**Comment by pedrosouzabrasil** [comment]
Hi @longjunyu2 ...i know its not related here (maybe )but news about aarch64 on 1.13plus and snapdragon fps problem (gl4es)?

**Comment by pedrosouzabrasil** [comment]
Maybe using discord on pc(on huawei not supported yet)

**Comment by NidzGamingTV** [comment]
> I even can not download the Discord app..
> It says I can download it from Google Play, but HUAWEI seems to not support Google Play.
> And I can not open the website of Google Play either..

Hello @longjunyu2 you can download it here https://www.google.com/amp/s/m.apkpure.com/discord-talk-video-chat-hang-out-with-friends/com.discord/amp

**Comment by TSaltedfishKing** [comment]
Mainland China cannot access certain websites for special reasons.Therefore, some software can not be accessed or loaded slowly.

**Comment by Malaska678** [comment]
@longjunyu2 You can use vpn.

**Comment by TheWithCommands** [comment]
No, Steamcommunity 302

**Comment by NidzGamingTV** [comment]
Maybe a direct link?

**Comment by TheWithCommands** [comment]
> Maybe a direct link?

https://www.dogfight360.com/blog/686/

**Comment by NidzGamingTV** [comment]
https://download.apkpure.com/b/APK/Y29tLmRpc2NvcmRfMTI3N184NzUxMjNhNQ?_fn=RGlzY29yZCBUYWxrIFZpZGVvIENoYXQgSGFuZyBPdXQgd2l0aCBGcmllbmRzX3Y0MC44X2Fwa3B1cmUuY29tLmFwaw&as=93991687be4021f2564f824dc9bbada35f7b330f&ai=879549149&at=1601909399&_sa=ai%2Cat&k=2e2ef647945e19575584c654ee569aa85f7dd597&_p=Y29tLmRpc2NvcmQ&c=1%7CCOMMUNICATION%7CZGV2PURpc2NvcmQlMjBJbmMuJnQ9YXBrJnM9NzA1NDYxNjgmdm49NDAuOCZ2Yz0xMjc3&w=1

**Comment by JohnsonLi06** [comment]
# @NidzGamingTV  I can not open this website
ps:I am from China

**Comment by TheWithCommands** [comment]
> # @NidzGamingTV I can not open this website
> ps:I am from China

Use Steamcommuntiy 302

**Comment by longjunyu2** [comment]
OK. Thanks for yours help..
I will.try to open discord visa Steamcommunity 302.
But I many courses today XD.
So it will be a little late.

**Comment by NidzGamingTV** [comment]
I will close this now. @longjunyu2 please update us if you already have discord server so we can join 😊 sorry for the ping. Tnx 🙂

**Comment by longjunyu2** [comment]
@NidzGamingTV 
Hi.
 I have sigined.in a discord account successfully.
And I have created a topic for mcinabox.
But ... I can not verify my email.. this is strange.
I think it is difficult to use discord in China..

So, we need another solution I think.
Would you like to create a discord server for MCinaBox with your account?

**Comment by pedrosouzabrasil** [comment]
Hi @longjunyu2 i had created one ...please join us https://discord.gg/BJqS8M8

**Comment by longjunyu2** [comment]
@pedrosouzabrasil 
Oh OK!
But it is 0:33 in Beijing now.
My school not allows us to use electricity after 0:00 until 6:00.
So I have to accept your invitation on my computer with VPN in the morning.XD.

**Comment by pedrosouzabrasil** [comment]
Thank you so much !waiting so..
