### ISSUE TITLE
Could you technically get forge working with this?

### ISSUE THREAD

**Issue by J-a-d-i** [AOF-Dev/MCinaBox#473]
Just curious as to if you import a forge binary you'd be able to play with mods?

**Comment by TSaltedfishKing** [comment]
？？？
You can run mods on this

**Comment by J-a-d-i** [comment]
I just found it haha, you're honestly god tier. I hope you continue to support this as just the concept of running java binaries on android is mind blowing

**Comment by J-a-d-i** [comment]
I cant seem to install runtimes

**Comment by J-a-d-i** [comment]
Sorted, ty
