### ISSUE TITLE
Forge Installer File

### ISSUE THREAD

**Issue by bluetoot420** [AOF-Dev/MCinaBox#474]
Every time i try downloading any forge file it says that an error occured but i made sure everything was right, the source file, if it was really the file i needed and i tried again and it still says that an error occured. And now whenever i launch and version with mcinabox its corrupt, and i cant go to any online servers bcos the online login is actually also broken. I tried this is 0.1.3 and 0.1.4 pls help me. Also i used the universal forge file

**Comment by NidzGamingTV** [comment]
Do not use official download source

**Comment by bluetoot420** [comment]
I did not use the official download source. And it said download failed. Im currently trying out other forge files just in case they work

**Comment by NidzGamingTV** [comment]
Try find different universal forge site

**Comment by NidzGamingTV** [comment]
I'm using 1.12.2

**Comment by bluetoot420** [comment]
i tried 1.8.9 it doesnt work

**Comment by NidzGamingTV** [comment]
> i tried 1.8.9 it doesnt work

There's a bug crash when installing forge in that version. I saw a commit that will be fixed in p4

**Comment by bluetoot420** [comment]
> > i tried 1.8.9 it doesnt work
> 
> There's a bug crash when installing forge in that version. I saw a commit that will be fixed in p4

So basically i should, just try another file than universal and other versions. Well actually i tried 1.16.3 also it didnt work but ill try 1.12.idk, to see if it works

**Comment by Bean3571** [comment]
I think it's impossible to install forge because Mcinabox doesn't show game versions when unofficial download source is selected. I was trying to install forge on 1.11.2
I can't connect to any servers too

**Comment by bluetoot420** [comment]
So i just tried 1.12.2 forge it stikk doesnt work so wtf

**Comment by gamecss** [comment]
+1

**Comment by bluetoot420** [comment]
> +1

?

**Comment by gamecss** [comment]
=me too

**Comment by bluetoot420** [comment]
Ok good news is that i updated to 0.1.4 the 1.8.9 forge worked
