### ISSUE TITLE
Can anyone who succesfully installed Optifine/Forge/Sodium for 1.16.3 send me the file?

### ISSUE THREAD

**Issue by NicCrimson** [AOF-Dev/MCinaBox#476]

**Comment by bluetoot420** [comment]
Sorry i cant install froge either, i tried a kot of versions. So maybe try o.1.4?

**Comment by KeyzGames** [comment]
I think MCinaBox isn't support 1.16.3, how did you do that?

**Comment by NicCrimson** [comment]
Try again, it works fine beside the lag, but I found raising the memory helps. If only I could install OptiFine/Sodium.

**Comment by NicCrimson** [comment]
> I think MCinaBox isn't support 1.16.3, how did you do that?
Try again, it works fine beside the lag, but I found raising the memory helps. If only I could install OptiFine/Sodium.

**Comment by bluetoot420** [comment]
> > I think MCinaBox isn't support 1.16.3, how did you do that?
> 
> Try again, it works fine beside the lag, but I found raising the memory helps. If only I could install OptiFine/Sodium.
> 

How did you install forge???

**Comment by NicCrimson** [comment]
> > > I think MCinaBox isn't support 1.16.3, how did you do that?
> > 
> > 
> > Try again, it works fine beside the lag, but I found raising the memory helps. If only I could install OptiFine/Sodium.
> 
> How did you install forge???

I didn't install forge, I installed 1.16
3.

**Comment by KUALALUM** [comment]
Import it the forge folder version and libraries from ur pc to ur phone

**Comment by NicCrimson** [comment]
> Import it the forge folder version and libraries from ur pc to ur phone

Don't have access to a PC currently, that's why I asked.

**Comment by KUALALUM** [comment]
Ooo

**Comment by bluetoot420** [comment]
Good news, i tried 1.8.9 forge in 0.1.4 mcinabox and it works but i cant actually launch any fking version
