### ISSUE TITLE
Installing forge 1.16.x says "Download failed"

### ISSUE THREAD

**Issue by MrCHB1** [AOF-Dev/MCinaBox#481]
How the heck do I get it to download forge 1.16.x?
![Screenshot_2020-10-06-16-47-11-593](https://user-images.githubusercontent.com/65914773/95263627-af094600-07f3-11eb-9f40-fafeeab9b46f.jpeg)

**Comment by TSaltedfishKing** [comment]
do not use bmclapi and mcbbs

**Comment by KeyzGames** [comment]
> do not use bmclapi and mcbbs

bro, we only have official, bmclapi and mcbbs. We cannot download that forge with a official download source.

**Comment by NicCrimson** [comment]
> > do not use bmclapi and mcbbs
> 
> bro, we only have official, bmclapi and mcbbs. We cannot download that forge with a official download source.
> 
> oh wait, this is 0.1.3

Does it work in 0.1.4?
