### ISSUE TITLE
help me How to fix the error of the mod Immersive Engineering

### ISSUE THREAD

**Issue by lephuc0167283** [AOF-Dev/MCinaBox#483]
mod 
![Screenshot_2020-10-07-12-27-34-898_com aof mcinabox](https://user-images.githubusercontent.com/68628569/95291199-2f35b700-0899-11eb-8157-329c9cc4b9be.jpg)
![Screenshot_2020-10-07-12-27-24-185_com aof mcinabox](https://user-images.githubusercontent.com/68628569/95291205-31981100-0899-11eb-8531-626da8747ae7.jpg)

Immersive Engineering  it's an image error

**Comment by lephuc0167283** [comment]
làm sao để sửa nó . Thank

**Comment by lephuc0167283** [comment]
Forge 1.12.2

**Comment by artdeell** [comment]
Try to change GUI size in game settings

ср, 7 окт. 2020 г., 12:56 lephuc0167283 <notifications@github.com>:
