### ISSUE TITLE
Cant install minecraft 1.15.2 forge

### ISSUE THREAD

**Issue by MCG027yT** [AOF-Dev/MCinaBox#485]

**Comment by Kotarou2k4** [comment]
Version higher than 1.13 can't install forge

**Comment by bluetoot420** [comment]
> Version higher than 1.13 can't install forge

I tried 1.12.2 it dont work y?

**Comment by CosineMath** [comment]
Forge for Minecraft 1.15.2 not supported.

**Comment by pedrosouzabrasil** [comment]
@cosinemath sorry to ping..(blessed day for you)i would be really glad if you join our discord for mcinabox (longjunyu2  will)so we can discuss in a good way and everybody could share experiences playing minecraft..(wrong topic also   ..so sorry) https://discord.gg/nZ6tt5

**Comment by Kotarou2k4** [comment]
@bluetoot420 try older forge version for 1.12.2, you can install version 14.23.5.2847
