### ISSUE TITLE
Mcinabox (0.1.3)texture fix

### ISSUE THREAD

**Issue by pedrosouzabrasil** [AOF-Dev/MCinaBox#488]
Hi....i was wondering how to fix textures on 1.13 plus versions...because i saw a commit(recently)that fixes that...@longjunyu2 can you help me ?its a line of code and i dont know how to add that to that version of the game...

**Comment by longjunyu2** [comment]
@pedrosouzabrasil 
Hi.
I will release the p4 version with the lastest codes this afternoon(after courses..) in time of Beijing.

**Comment by longjunyu2** [comment]
I have tested the lastest code. And minecraft 1.15+ have no texture issues.. But now only aarch32 can launch it..(The new runtime for aarch64 still needs some time.)
And I will divided MCinaBox into tow version with platform. Then aarch64 device can also use aarch32 runtime.

**Comment by pedrosouzabrasil** [comment]
Ok!thanks for let me know..we are waiting for you tô join our group!(discord)blessed day.

**Comment by pedrosouzabrasil** [comment]
Still release today?

**Comment by pedrosouzabrasil** [comment]
@longjunyu2?..maybe tomorrow..or these weekend
