### ISSUE TITLE
mcinabox v0.1.4-p3 forge 1.12.2 installation problem

### ISSUE THREAD

**Issue by Androser420** [AOF-Dev/MCinaBox#496]
Look in the comments.

**Comment by Androser420** [comment]
So I was playing a bit, and then I thought to myself, maybe I should install forge 1.12.2 and play with optifine for better FPS. 1.12.2 works perfectly fine, but, when I tried to install forge 1.12.2 an error occurred. I already installed all the mods and stuff then an error (lol I died at that point). So please, find an solution for this install error.
![Screenshot_20201008-231838_MCinaBox](https://user-images.githubusercontent.com/72580260/95515594-2ee30c00-09be-11eb-98b3-8115f6b1fab8.png)

**Comment by Androser420** [comment]
So I was playing a bit, and then I thought to myself, maybe I should install forge 1.12.2 and play with optifine for better FPS. 1.12.2 works perfectly fine, but, when I tried to install forge 1.12.2 an error occurred. I already installed all the mods and stuff then an error (lol I died at that point). So please, find an solution for this install error.
![Screenshot_20201008-231838_MCinaBox](https://user-images.githubusercontent.com/72580260/95515830-85e8e100-09be-11eb-86e0-ef17db739203.png)

**Comment by Kuprik007** [comment]
Download other forge

**Comment by Kuprik007** [comment]
Here try
https://drive.google.com/file/d/1PZvct98W_YigGuEq4dfMwEdDwkRYY0_C/view?usp=drivesdk

https://drive.google.com/file/d/1PYqbAITHPmS2NzhHDDdwq2GOqNi9oydZ/view?usp=drivesdk

https://drive.google.com/file/d/1PWgpR3CXvgJ6pu_dumU42VBPyGnZTIWE/view?usp=drivesdk

**Comment by Androser420** [comment]
Thank you soo much! It worked.

**Comment by CloserPopcorn20** [comment]
If you still want to install final version of forge:
Install forge in Minecraft launcher
Copy: forge version and libraries folder
Enjoy!

**Comment by ntk8en8112k7** [comment]
> Here try
> https://drive.google.com/file/d/1PZvct98W_YigGuEq4dfMwEdDwkRYY0_C/view?usp=drivesdk
> 
> https://drive.google.com/file/d/1PYqbAITHPmS2NzhHDDdwq2GOqNi9oydZ/view?usp=drivesdk
> 
> https://drive.google.com/file/d/1PWgpR3CXvgJ6pu_dumU42VBPyGnZTIWE/view?usp=drivesdk

Thanks you is work but i think link 2 is ok
