### ISSUE TITLE
What are the best Launcher settings for 1.12.2 forge? 

### ISSUE THREAD

**Issue by leetmussc** [AOF-Dev/MCinaBox#497]
I know some people can't run forge 1.12.2 so, I was wondering if there were any settings that would have to be turned on or off for the forge to run the mods.

P. S. My phone was able to run over 100 mods on MCinaBox 0.1.3.

**Comment by leetmussc** [comment]
With forge 1.12.2

**Comment by leetmussc** [comment]
And it was able to run two mod packs at once at a good 30fps without any fps boost mods

**Comment by KeyzGames** [comment]
wow you had a high-end device. i cannot run 100 mods, i tried it once and it just stuck in generating world screen

**Comment by KUALALUM** [comment]
> wow you had a high-end device. i cannot run 100 mods, i tried it once and it just stuck in generating world screen

If u stuck at world loading screen try to off ur data

**Comment by SmeraldoKEKW** [comment]
what is your phone?

**Comment by minerchino** [comment]
@SmeraldoKEKW  i suggest your phone to be realme c3 or realme 5i of you want 1.12.2 forge with alot of mods
