### ISSUE TITLE
mouse and keyboard support. 

### ISSUE THREAD

**Issue by DaviF19** [AOF-Dev/MCinaBox#498]
Does version 0.1.4-p3 support aouse and keyboard?

**Comment by leetmussc** [comment]
There might be, wait and see

**Comment by KUALALUM** [comment]
Use octopus app to use mouse and keyboard

**Comment by jak0bkrienitz** [comment]
The octopus app doesnt work. The app opens through it but when you go to play a version of the game it crashs. not to mention that you have to watch 15 billion ads before you can even open the app.

**Comment by Matryx0207w** [comment]
Hi, I wanted to ask you why you don't have mouse support with android 8 to play with keyboard and mouse on android to make it more comfortable I hope you hear my request :)

**Comment by longjunyu2** [comment]
Have supported mouse and keyboard with android8 and higher.
