### ISSUE TITLE
I can't change my memory high that 334

### ISSUE THREAD

**Issue by SmeraldoKEKW** [AOF-Dev/MCinaBox#509]
Hello dear friends. 
When I want to start minecraft 1.12.2 (forge) with it goes good, but if i start with mod TerraFirmaCraft minecraft crushed. I think, that this is because my memory only 334 mb (on 1.7.10 I played good with 1000mb)
Also your app send, that this can crush JVM, but on 1.7.10 I hadn't crush at all.
Next you have setting "Don't check compatibility of JVM", and if i turn on i can't change my mb higher than 339 (if i change it to 400+, i can't run minecraft at all)
I think that you need to delete this compatibility...
But your app is very good :)

**Comment by SmeraldoKEKW** [comment]
I downloaded 0.1.3 , give 1100 mb  of memory and played good, but i had some troubles

**Comment by CosineMath** [comment]
It is up to your device. Using 64bit version might help.
