### ISSUE TITLE
Add optifine installer version

### ISSUE THREAD

**Issue by minerchino** [AOF-Dev/MCinaBox#513]
Can you add optifine installer on mcinabox because i have to import the optifine version and the libraries every time i want to have a optifine version this is just suggestion

**Comment by davidii12** [comment]
I already have problems with installing forge.
Because it stops at 5% and says download failed.

**Comment by minerchino** [comment]
@davidii12 no the optifine version not with forge

**Comment by longjunyu2** [comment]
@minerchino 
oh, this is a good idea.
