### ISSUE TITLE
添加BMCLAPI的捐赠链接

### ISSUE THREAD

**Issue by longjunyu2** [AOF-Dev/MCinaBox#514]
目前BMCLAPI为国内(中国)的Minecraft和forge等营造了一个高速的下载环境。
BMCLAPI是一个公益性质的项目，它并没有要求使用者必须为其提供的服务付费。
因此它的运行成本由其开发者和捐赠者们承担。

为了支持BMCLAPI继续提供高效、便利的下载服务，我们决定在MCinaBox中添加BMCLAPI的捐赠链接。

发出此贴主要是征求意见，包括捐赠链接放置的位置和布局，以及如何引导用户正确理解捐赠的概念。

**Comment by Malaska678** [comment]
Well what he mean is bmclapi is providing fast download and its free. And money involved in it is provided by  it devs and donor. So they put link to donation site.

**Comment by Malaska678** [comment]
Translated

**Comment by artdeell** [comment]
bmclapi & mcbbs is sus
trust only mojang

пн, 12 окт. 2020 г., 15:18 Malaska678 <notifications@github.com>:

**Comment by Malaska678** [comment]
Nope becoz it will slow for china ppl

**Comment by artdeell** [comment]
for china ppl
but for us it's not
so, leave user a choice and don't force users to install forge from slow and unknown chinese mirrors
