### ISSUE TITLE
Aarch64 on 0.1.4p4 for minecraft version 1.13+?

### ISSUE THREAD

**Issue by pedrosouzabrasil** [AOF-Dev/MCinaBox#517]
Waiting for some news regarding this...thanks..

**Comment by LegacyGamerHD** [comment]
well yes i woeld love that lol i need 1.16.3

**Comment by NidzGamingTV** [comment]
I hope they also add the possible fix for snapdragon in aarch64 posted by @pedrosouzabrasil so 1.16 3 will run much better 😁

**Comment by longjunyu2** [comment]
@pedrosouzabrasil 
Not yet. Please wait.

**Comment by longjunyu2** [comment]
I am working on building new runtime for aarch64.

**Comment by pedrosouzabrasil** [comment]
Thanks dev !

**Comment by NidzGamingTV** [comment]
Up

**Comment by CosineMath** [comment]
Might be fixed soon.
