### ISSUE TITLE
version 1.7.10 with forge crashes and tips for improvements.

### ISSUE THREAD

**Issue by IranDoGrauUu** [AOF-Dev/MCinaBox#518]
version 1.7.10 with forge crashes. please fix the 1.7.10 bug with forge crash. and I could fix the keyboard editing way I liked the idea of ​​editing the controller while playing, but it took me a while to figure out how to make the controller work. and I wanted the forge installation procedure to be simpler, like installing the runtime, which is basically pressing the import button, if possible.

**Comment by artdeell** [comment]
idk, i wanted to do the button for forge too, but they changed the codebase

вт, 13 окт. 2020 г., 03:11 IranDoGrauUu <notifications@github.com>:

**Comment by IranDoGrauUu** [comment]
don't forget that version 1.7.10 with forge crashes
