### ISSUE TITLE
Suggestion: Make an issue template to guide people how to report bugs

### ISSUE THREAD

**Issue by Kotarou2k4** [AOF-Dev/MCinaBox#520]
You can see in the pictures below
![IMG_20201013_202844](https://user-images.githubusercontent.com/65490046/95866999-d41d2c00-0d92-11eb-94cb-5c837a4cc239.jpg)
![IMG_20201013_202902](https://user-images.githubusercontent.com/65490046/95867015-d97a7680-0d92-11eb-8be0-6658053417ff.jpg)
This will be working as a guide, you can add logs and crash reports file path so they can find them
This is Osu!lazer project on github: https://github.com/ppy/osu
(And I also have mentioned this in #484 )

**Comment by LegacyGamerHD** [comment]
why not pull reqeast it

**Comment by Kotarou2k4** [comment]
@AyHa1810 thanks
