### ISSUE TITLE
0.1.4p4 arm32 bug

### ISSUE THREAD

**Issue by pedrosouzabrasil** [AOF-Dev/MCinaBox#526]
![Screenshot_20201013-200637_MCinaBox](https://user-images.githubusercontent.com/63176856/95925715-e1d1b200-0d90-11eb-8c2f-ac2274ecb88b.jpg)

Hi developer...my keyboard is not working properly on  latest release..(the buttons are not saving so i cannot play)...

My device is a Samsung tab s7..(64 bit)...also the arrow keys are not working..cannot move!

**Comment by Muratsoyler** [comment]
Hello! İ am developer murat_soyler i have been searching trough the bug list! And most people have this issue i am going to try fixing it on the lastest relesae also there is a way to fix you'r keyboard you have to use mcinabox (0.1.3) or you can rename the app to "MCİNABOX LAUNCHER" and it will work on (0.1.4.p4) thanks for the bug!
