### ISSUE TITLE
Remains of translation bug

### ISSUE THREAD

**Issue by AyHa1810** [AOF-Dev/MCinaBox#527]
**Bug Description**
It's the text above the 'Home' and the second section's title in the settings menu that is in chinese which should be in any language we set, or default as English.

**To Reproduce**
1. Well, it is on the home screen.
2. In the settings menu
3. In the game menu

**Expected behavior**
It should show in the language we set.

**Screenshots**
![IMG_20201014_082714](https://user-images.githubusercontent.com/63386848/95938676-fd23d800-0df7-11eb-9ee0-6bedba0aad7a.jpg)
![IMG_20201014_084440](https://user-images.githubusercontent.com/63386848/95939481-d070c000-0df9-11eb-800f-afeadec65c31.jpg)
![IMG_20201014_084938](https://user-images.githubusercontent.com/63386848/95939783-80462d80-0dfa-11eb-9032-857a8d9465cd.jpg)

**Smartphone (please complete the following information):**
 - Device: Oppo A9 2020
 - OS: Android 10; ColorOS V7.1
 - App Version v0.1.4-p4

**Additional context**
No additional context here, but this is the first issue with template used.

**Comment by Mhowser** [comment]
![Screenshot_20201013-104500](https://user-images.githubusercontent.com/24195572/95941997-f6b14400-0d96-11eb-8423-3dfd1d132f3a.png)
Also this dialogue box, I have no ideas what it says.

**Comment by AyHa1810** [comment]
@Mhowser I think @longjunyu2 already fixed it because I saw a commit on it. Here's the commit [bc26ba9](https://github.com/AOF-Dev/MCinaBox/commit/bc26ba9607e341574ccdc6c11a76583e7aacd69e).

**Comment by Mhowser** [comment]
Ah thanks.

**Comment by longjunyu2** [comment]
OK ,got it.

**Comment by AyHa1810** [comment]
Ok, it seems like those problems were solved.
