### ISSUE TITLE
在使用yggdrasil登陆时出现错误

### ISSUE THREAD

**Issue by AdminUndead** [AOF-Dev/MCinaBox#530]
手机版本 安卓10
mcinabox版本 p4
-
问题：
在使用登陆账号后出现问题
提示:
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
-
#这不会是没使用https的问题吧？
无法使用yggdrasil登陆账户
-
推荐在页面那整一个提示
例如：不带http://
-
测试使用 http://网站地址/api/yggdrasil 时客户端会闪退
而不用http登陆会有报错

**Comment by longjunyu2** [comment]
按照规范应该使用https, 启动器在自动补全的时候会优先选择https，但是考虑到有部分服务器可能依旧使用http，因此启动器仍然允许使用http
是什么导致的崩溃？你能否提供调试信息。(logcat)

**Comment by longjunyu2** [comment]
另外，这个提示是在什么时候出现的？
能否提供一些截图。

**Comment by longjunyu2** [comment]
我觉得问题可能出在服务器端。
我已经测试过了几个支持外置登陆的服务器，通过他们的验证服务器创建用户，均为出现上述信息。

**Comment by AdminUndead** [comment]
> 按照规范应该使用https, 启动器在自动补全的时候会优先选择https，但是考虑到有部分服务器可能依旧使用http，因此启动器仍然允许使用http
> 是什么导致的崩溃？你能否提供调试信息。(logcat)

调试信息在哪查看，开启了调试模式操作了一遍
-
http://login.mcsld.top/api/yggdrasil这是我外置验证地址
-
这个我在地址栏添加了这个登陆后就会闪退

**Comment by longjunyu2** [comment]
好的，接下来会对这个验证地址进行测试，调试的工作交给我我完成即可。

**Comment by longjunyu2** [comment]
好的，以确认是启动器的bug，由于缺少一个else结构，导致产生了一个空对象。
感谢反馈。
请等待下一次更新(明天的紧急更新，原定修复输入框的bug)

**Comment by longjunyu2** [comment]
所以明天会连同这个bug一起修复。

**Comment by AdminUndead** [comment]
> 所以明天会连同这个bug一起修复。

好的👌感谢~
