### ISSUE TITLE
Crash when pressing on the configure button ingame or the left arrow, all other buttons are fine.

### ISSUE THREAD

**Issue by diademiemi** [AOF-Dev/MCinaBox#540]
When I press the configure button ingame or on the left arrow on the DPad, the game crashes. 
I am running the 32 bit version of v0.1.4-p4 with the aarch32-20200928.tar.xz runtime, because I want to play 1.16.3 and that does not even launch on the 64 bit version.

Relevant log:
`[ 10-15 15:02:17.865 10721:10721 E/mcinabox ]
Updata Setting.

[ 10-15 15:02:17.856 10721:10721 W/com.aof.mcinabox ]
type=1400 audit(0.0:8196): avc: denied { read } for comm=52656E64657220746872656164 name="cpu.shares" dev="cgroup" ino=8 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:cgroup:s0 tclass=file permissive=0 app=com.aof.mcinabox

[ 10-15 15:02:17.879 10721:10721 E/mcinabox ]
Updata Setting.

[ 10-15 15:02:18.016 10721:10721 I/chatty   ]
uid=10179(com.aof.mcinabox) identical 1 line

[ 10-15 15:02:18.158 10721:10721 E/mcinabox ]
Updata Setting.

[ 10-15 15:02:18.360 10721:14758 E/OtgKeyboard ]
Type: 11 KeyName: null Pressed: true

[ 10-15 15:02:18.361 10721:14758 E/AndroidRuntime ]
FATAL EXCEPTION: Thread-43
Process: com.aof.mcinabox, PID: 10721
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at com.aof.mcinabox.gamecontroller.controller.HardwareController.sendKey(HardwareController.java:65)
	at com.aof.mcinabox.gamecontroller.input.otg.Keyboard.sendKeyEvent(Keyboard.java:65)
	at com.aof.mcinabox.gamecontroller.input.otg.Keyboard.onKey(Keyboard.java:76)
	at com.aof.mcinabox.gamecontroller.controller.HardwareController.dispatchKeyEvent(HardwareController.java:118)
	at cosine.boat.BoatActivity.dispatchKeyEvent(BoatActivity.java:284)
	at cosine.boat.BoatInput.dispatchKeyEvent(BoatInput.java:61)

[ 10-15 15:02:18.383 10721:14758 I/Process  ]
Sending signal. PID: 10721 SIG: 9
`

Does anyone know how to fix this or if this is an issue with the code I can build and test it.

**Comment by rApHaEL1211** [comment]
Yeah me too I have that issue

**Comment by Iscle** [comment]
Yep, that's a weird issue! I have it too, I was able to patch it, but I want to find the root of the problem before pushing it here.

**Comment by diademiemi** [comment]
I just built the dev branch (Did build 32 bit, it starts with my build) but still same issue as described here. You probably already knew but just saying it is not fixed on current dev branch.

**Comment by diademiemi** [comment]
I just built the dev branch and it no longer crashes when I press the left arrow, the configure button does still crash though.

**Comment by diademiemi** [comment]
Setting the app to use full screen mode in the android settings fixed the configure button crash too! My phone has a 19.5:9 aspect ratio.
