### ISSUE TITLE
It wont let you type on the typing box

### ISSUE THREAD

**Issue by ghost** [AOF-Dev/MCinaBox#547]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy J6]
 - OS: [e.g. Android 8.1]
 - App Version [e.g. v0.1.3]

**Additional context**

**Comment by Mynameispoop** [comment]
Hello its me piketastic yur friend in discord :D

**Comment by RobTopFreak** [comment]
Oh hey

**Comment by Mynameispoop** [comment]
Sorry i didnt reply my notification didnt ring 😅
