### ISSUE TITLE
64bit Application Crashes on Boot

### ISSUE THREAD

**Issue by Always-Wipe** [AOF-Dev/MCinaBox#550]
**Describe the crash**
When you install the 64 bit version of the software, install 64 bit runtime, and run game the game will boot up and crash after 3-5 seconds. 

**To Reproduce**
Steps to reproduce the crash:
1. Download 64 Bit version of software and runtime libraries
2. Install 1.16.3 Minecraft 
3. Try to run game
4. Game will crash after a few seconds

**Expected behavior**
Game to boot up and play. 

**Screenshots**
https://streamable.com/ai4jd6

Video of crash

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Fold 2
 - OS: Android 10
 - App Version v0.1.4.4]

**Comment by Iscle** [comment]
This is a known bug. The maximum supported version right now is 1.12.

**Comment by Always-Wipe** [comment]
Is there a wiki we can contribute to? At least as English speakers to consolidate known bugs per version?

**Comment by WuJiayiSH** [comment]
same on honor v20 with v0.1.4-p4, but it works with arm32 apk and arm32 runtime. 
I guess this issue is duplicated but I cannot find the original one

**Comment by CosineMath** [comment]
It might be fixed soon.
