### ISSUE TITLE
what phone do i need to play Minecraft 1.16?

### ISSUE THREAD

**Issue by IranDoGrauUu** [AOF-Dev/MCinaBox#551]
i want to buy a new phone and then i wanted to know what phone i need to play Minecraft 1.16.3 i also wanted to play the datapacks so i would like to know a good phone for this.

**Comment by artdeell** [comment]
So, i can say that you should prefer Windows tablets irst, but if you need
a phone, your selection should be only recent flagships.

пт, 16 окт. 2020 г., 15:52 IranDoGrauUu <notifications@github.com>:

**Comment by FreddyFeuerstein** [comment]
raspberry pi 4 with touch display and usb sim card reader.

**Comment by artdeell** [comment]
lmao

пт, 16 окт. 2020 г., 17:45 Freddy Feuerstein <notifications@github.com>:

**Comment by minerchino** [comment]
Redmi note 9 pro 12-30 fps

**Comment by artdeell** [comment]
mi 8 stable 30 (0.1.3 community runtime)

вт, 20 окт. 2020 г., 13:03 minerchino <notifications@github.com>:

**Comment by minerchino** [comment]
> raspberry pi 4 with touch display and usb sim card reader.

Hello uhhm does this have touch controls or ????

**Comment by FreddyFeuerstein** [comment]
> > raspberry pi 4 with touch display and usb sim card reader.
> 
> Hello uhhm does this have touch controls or ????

Yes, it can run MCinaBox with touch controlls in android 9.
Or the official java launcher in ubuntu server 18.04 with xfce. But then it will not work with touch. You would need joycons or a keyboard for playing.

**Comment by AjGamingPHOfficial** [comment]
My phone is VivoY20i
I can run MCinabox 1.16.2
Infinite world- about 90 fps
Flat world about- 170fps
