### ISSUE TITLE
The Input Box Does not work in mcinabox aarch32

### ISSUE THREAD

**Issue by KUALALUM** [AOF-Dev/MCinaBox#553]
Input Box Does not work

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Vivo Y55L]
 - OS: [e.g. Android 6.0.1]
 - App Version [e.g. v0.1.4 p4 32]

**Additional context**
Pls Fix This Fast. Because i cant write a command and server ip plsss

**Comment by Muratsoyler** [comment]
You must open the text chat place not the keyboard if you are using the chat i dont know i will try to fix it though

**Comment by KUALALUM** [comment]
> You must open the text chat place not the keyboard if you are using the chat i dont know i will try to fix it though

Not work
