### ISSUE TITLE
I can't luanch minecraft 

### ISSUE THREAD

**Issue by Flameagle** [AOF-Dev/MCinaBox#558]
when I launch minecraft it displays Chinese text with two options and neither of them works and  I am  luanched back to mcinabox 

![Screenshot_2020-10-15-00-26-13](https://user-images.githubusercontent.com/70420942/96297620-69b5f700-0ff1-11eb-9172-ac6fdd85f4f9.png)

**Comment by TheGameYIYI** [comment]
@Flameagle Trataste de traducir lo que dice el mensaje?
