### ISSUE TITLE
What keyboard works for the text box?

### ISSUE THREAD

**Issue by TheGameYIYI** [AOF-Dev/MCinaBox#559]
The box on the upper left, will not open or the keyboard appears, some type of external keyboard that works in this case to have a pleasant experience? ...

**Comment by Tayoikoo** [comment]
You can use PC virtual keyboard, there are option that enable typing at right corner keyboard

![Screenshot_20201018_220857](https://user-images.githubusercontent.com/67594827/96371935-994e3600-118e-11eb-9d98-9e49e71132e1.jpg)
