### ISSUE TITLE
Problem on Installing Forge 1.16

### ISSUE THREAD

**Issue by Tayoikoo** [AOF-Dev/MCinaBox#561]
> This Problem when i install forge 1.16 (universal)
It seems that newer version of forge is incompatible.
I am using mcinabox v0.1.4p4 (arm32) and the forge version is 1.16.1-32.0.108

![Screenshot_20201017_070831](https://user-images.githubusercontent.com/67594827/96323936-677f8700-1049-11eb-804c-d1e1ea45d447.jpg)

**Comment by Always-Wipe** [comment]
Apparently only versions 1.12 and below work on the 64bit version but if you're running the 32 bit version, a workaround is to install it on your PC and copy/paste your minecraft folder into your phone and try. You just need to disable the forge splash screen
