### ISSUE TITLE
Mcinabox 0.1.4 p4 version bug

### ISSUE THREAD

**Issue by ArnaldoGame** [AOF-Dev/MCinaBox#563]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy J6]
 - OS: [e.g. Android 8.1]
 - App Version [e.g. v0.1.3]

**Additional context**

**Comment by ArnaldoGame** [comment]
.

**Comment by LegacyGamerHD** [comment]
more info needed closed for now
