### ISSUE TITLE
I have an important question.

### ISSUE THREAD

**Issue by Androser420** [AOF-Dev/MCinaBox#566]
1. Does MCinaBox 0.1.4 have keyboard and mouse support?

2. If it does how can I use it?

**Comment by AyHa1810** [comment]
Answers
1. Not currently, but will be available in future releases.

2. You cannot use it right now, wait for the future releases.

**Comment by Androser420** [comment]
> Answers
> 
> 1. Not currently, but will be available in future releases.
> 2. You cannot use it right now, wait for the future releases.

Ok thanks for the response
