### ISSUE TITLE
Input Box

### ISSUE THREAD

**Issue by leetmussc** [AOF-Dev/MCinaBox#568]
**Describe the bug**

**To Reproduce**
1. Go to Mcinabox menu (in game)
2. Click on input box
3. See error

**Expected behavior**
Pull up device keyboard

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Huawei y7 2019 DUB LX1
 - OS: Android 8.1.0 Emui
 - App Version v0.1.4p4 arrch 32

**Additional context**

**Comment by leetmussc** [comment]
Whens the realese to fix this bug??!!

**Comment by ArnaldoGame** [comment]
My device is having this same problem: J2 prime

**Comment by stacode123** [comment]
Same
