### ISSUE TITLE
我该如何安装optifine或forge？

### ISSUE THREAD

**Issue by jiajia229** [AOF-Dev/MCinaBox#569]
![Screenshot_20201018_114734_com aof mcinabox](https://user-images.githubusercontent.com/69904786/96358285-0e425100-1138-11eb-9a03-01b9a63cc6b7.jpg)
我一直卡在这儿，是有什么文件不支持下载吗？
我是安卓十）
请问未来会支持安卓十吗？
我有没有什么办法安装高清修复？（我是买了披风的。。。。）

**Comment by AdminUndead** [comment]
高清修复装模组不就完了嘛

**Comment by jiajia229** [comment]
等于没答
