### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by NidzGamingTV** [AOF-Dev/MCinaBox#570]
**Is your feature request related to a problem? Please describe.**
Please make 64bit runtime that support 1.16.3 also forge or optifine

**Describe the solution you'd like**
Just like the old method, copy the file from your pc and paste to mcinabox folder

**Describe alternatives you've considered**

**Additional context**
We really need this before 1.17 beta release

**Comment by NidzGamingTV** [comment]
@longjunyu2 @Iscle

**Comment by artdeell** [comment]
~~check out pojavlauncher~~
just sayin

**Comment by LegacyGamerHD** [comment]
sapmming that wont help

**Comment by LegacyGamerHD** [comment]
also dublicted of #517
