### ISSUE TITLE
replace the input box with a virtual keyboard

### ISSUE THREAD

**Issue by IranDoGrauUu** [AOF-Dev/MCinaBox#574]
in the current version of mcinabox (0.1.4-p4) there is a bug that when you activate the input box (used to write) the cell phone's keyboard does not appear, so I suggest changing the input box for a mcinabox keyboard  an option called "PC keyboard" but it doesn't work for writing, so it would be better to add another keyboard but this one would be exclusively for writing.

**Comment by CosineMath** [comment]
The input box would be kept as it is very convenient to input non-latin characters such as Chinese.

**Comment by IranDoGrauUu** [comment]
I got it, thanks

**Comment by IranDoGrauUu** [comment]
@CosineMath  I got it, thanks
