### ISSUE TITLE
pls help with mcinabox

### ISSUE THREAD

**Issue by elyesishere** [AOF-Dev/MCinaBox#575]
**Describe the crash**
when i pressed start game after installing runtime and the version (it is 1.12.2 btw) the screen is black after 5-10 seconds it crashed pls help

 - Device: [infinix hot 8]
 - OS: [android 9]
 - App Version [v0.1.4-pre4]

pls i need to play with my friends on a simple server

**Comment by Taki15** [comment]
which version of the runtime did you download? download and install the one that suits your CPU

If ur cpu have 64bit, download runtime64
If 32bit, runtime32.

**Comment by elyesishere** [comment]
my phone has 64 bit so i installed the aarch64 runtime and it crashed

**Comment by Taki15** [comment]
> my phone has 64 bit so i installed the aarch64 runtime and it crashed

Same with me. So I dunno..
