### ISSUE TITLE
扳手未顯示。

### ISSUE THREAD

**Issue by Mynameispoop** [AOF-Dev/MCinaBox#576]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy J6]
 - OS: [e.g. Android 8.1]
 - App Version [e.g. v0.1.3]

**Additional context**

**Comment by longjunyu2** [comment]
@Mynameispoop 你好！ 请您提供您的手机型号、安卓版本，如果有的话，我还需要您的OS版本。还需要您使用的启动器版本。
并且我需要知道，如果您使用的是0.1.4-p4，这个问题是否曾出现在p3？

**Comment by Mynameispoop** [comment]
p4 扳手沒有顯示在 p3 它的確定, 請快速修復它, 我不能正常播放。
