### ISSUE TITLE
Crash forge

### ISSUE THREAD

**Issue by alex9900123** [AOF-Dev/MCinaBox#577]
hello what happens is that when I want to open the forge in any version the app closes 

Pd*plss help me

**Comment by alex9900123** [comment]
They help me?

**Comment by LegacyGamerHD** [comment]
this is more of qeastion then a bug

**Comment by alex9900123** [comment]
Ok?

**Comment by alex9900123** [comment]
But what I want is to install forge on 1.7.10 but when you open it closes

**Comment by LegacyGamerHD** [comment]
> But what I want is to install forge on 1.7.10 but when you open it closes

use the universal installer

**Comment by alex9900123** [comment]
I use tath
