### ISSUE TITLE
Mouse and keyboard input bug

### ISSUE THREAD

**Issue by AyHa1810** [AOF-Dev/MCinaBox#579]
**Bug Description**
I am not able to use MCPE keys and mouse in MC 1.16.3. The keys and mouse input isn't working.

**To Reproduce**
1. Select 1.16.3 and start it (Same device as me, maybe others also)
2. Then the mouse input will be slightly off in the home.
3. Start any world
4. The keys and mouse input will not work.

**Expected behavior**
Mouse and keys input should work.

**Screenshots**
Screenshots cannot be applicable for this issue.

**Smartphone (please complete the following information):**
 - Device: OPPO A9 2020 (4GB/256GB) (aarch64)
 - OS: Android 10
 - App Version v0.1.4-p4-aarch32 (runtime: aarch32)

**Additional context**
Also, there are some texture bugs here and there.

**Comment by AyHa1810** [comment]
@Iscle, @longjunyu2 wanted to build two different apks for aarch32 and aarch64 devices to install the aarch32 apk directly to the aarch64 devices. This way, you can install the aarch32 runtime (whose graphics issue has been almost fixed) and play MC 1.14+. The

**Comment by AyHa1810** [comment]
@Iscle, @longjunyu2 wanted to build two different apks for aarch32 and aarch64 devices to install the aarch32 apk directly to the aarch64 devices. This way, you can install the aarch32 runtime (whose graphics issue has been almost fixed) and play MC 1.14+. The graphics issue and the crash bug (of the MCJE 1.14+) isn't fixed yet for the aarch64 runtime.

**Comment by Iscle** [comment]
That can be accomplished with a single .apk too! It's just a matter of manually selecting the library to be loaded at runtime.

Either way, it's not a perfect fix. What we're aiming to is to have proper aarch64 support 😁

**Comment by AyHa1810** [comment]
@Iscle that doesn't works. Instead, it crashes.

**Comment by AyHa1810** [comment]
@Iscle also, you should checkout the projects section of this organization.

**Comment by Iscle** [comment]
> @Iscle also, you should checkout the projects section of this organization.

What's up with them?

**Comment by Iscle** [comment]
> @Iscle also, you should checkout the projects section of this organization.

What's the matter with it?

**Comment by LegacyGamerHD** [comment]
well i know that thats why i build it sepret but he didnt listen

**Comment by Iscle** [comment]
I know, trying to run arm32 libraries from arm64 native binaries will crash. You are right, but what I'm trying to say is that it should be possible to force android into loading the arm32 native binaries from a single APK at runtime.

Either way, this is not a proper fix, just a workaround. We should focus our efforts into fixing the root cause of the issue.

**Comment by LegacyGamerHD** [comment]
@Iscle why not use the work around rn and fix it later

**Comment by Iscle** [comment]
> @Iscle why not use the work around rn and fix it later

I mean, if that's what you want, we can. But this will only confuse people even more. Considering most of them are 14yo with no computer science knowledge, we'll only get more and more issues opened (like we have now). Since this project is still in an alpha state, I think we're okay to say "it does not work yet" and for people to wait.

Of course, that's just my opinion. We can do either and keep working on it 👍

**Comment by LegacyGamerHD** [comment]
> > @Iscle why not use the work around rn and fix it later
> 
> I mean, if that's what you want, we can. But this will only confuse people even more. Considering most of them are 14yo with no computer science knowledge, we'll only get more and more issues opened (like we have now). Since this project is still in an alpha state, I think we're okay to say "it does not work yet" and for people to wait.
> 
> Of course, that's just my opinion. We can do either and keep working on it 👍

sure but most devices by now are 64 bit even when i was 14 i knew the difrences between them and i knew what my devices arcitect were

**Comment by LegacyGamerHD** [comment]
> @Iscle, @longjunyu2 wanted to build two different apks for aarch32 and aarch64 devices to install the aarch32 apk directly to the aarch64 devices. This way, you can install the aarch32 runtime (whose graphics issue has been almost fixed) and play MC 1.14+. The graphics issue and the crash bug (of the MCJE 1.14+) isn't fixed yet for the aarch64 runtime.

did it work on my dev builds

**Comment by AyHa1810** [comment]
@Iscle lol you guessed the correct age of mine! And about computer science knowledge, I have some, since I have a pc (which is a F**king piece of $#!t). What did you thought who I am? And about the project section, @longjunyu2 mentioned something about OpenJDK 14 aarch32 build. [Here](https://github.com/orgs/AOF-Dev/projects/2) is the project link.

**Comment by AyHa1810** [comment]
@LegacyGamerHD no, it didn't work. It crashes.

**Comment by Iscle** [comment]
> @Iscle lol you guessed the correct age of mine! And about computer science knowledge, I have some, since I have a pc (which is a F**king piece of $#!t). What did you thought who I am? And about the project section, @longjunyu2 mentioned something about OpenJDK 14 aarch32 build. [Here](https://github.com/orgs/AOF-Dev/projects/2) is the project link.

Haha wow, it's nice that you have such knowledge at your age already :) However not everyone is like you (I hope they were lol). Of course I was not complaining about you, but the other 200+ issues in the repository.

I have taken a look at the OpenJDK aarch32 source, but I can't get it to build on my computer. I will need some feedback from @longjunyu2 on how he made it to compile before I can clean it up and upstream it a bit.

I'm now taking a look at glfw and lwjgl as that needs some work too. Hopefully, once I get everything building, I can create some GitHub actions to automatically embed it in our project and have a more seamless experience, as well as fix some of the Android security issues 💯

**Comment by LegacyGamerHD** [comment]
> @LegacyGamerHD no, it didn't work. It crashes.

did install right runtime on right apk

**Comment by LegacyGamerHD** [comment]
do pedro said it fixes the mouse bug without crashes

**Comment by LegacyGamerHD** [comment]
> @Iscle lol you guessed the correct age of mine! And about computer science knowledge, I have some, since I have a pc (which is a F**king piece of $#!t). What did you thought who I am? And about the project section, @longjunyu2 mentioned something about OpenJDK 14 aarch32 build. [Here](https://github.com/orgs/AOF-Dev/projects/2) is the project link.

that doesnt work as mcinthebox use faster garbage collecter on there java so if we switch java it woeld be slow as pojav v3

**Comment by LegacyGamerHD** [comment]
this is last commit that works

**Comment by Iscle** [comment]
> > @Iscle lol you guessed the correct age of mine! And about computer science knowledge, I have some, since I have a pc (which is a F**king piece of $#!t). What did you thought who I am? And about the project section, @longjunyu2 mentioned something about OpenJDK 14 aarch32 build. [Here](https://github.com/orgs/AOF-Dev/projects/2) is the project link.
> 
> that doesnt work as mcinthebox use faster garbage collecter on there java so if we switch java it woeld be slow as pojav v3

As far as I know, MCinaBox uses that Java build in the runtime package!

**Comment by LegacyGamerHD** [comment]
> > > @Iscle lol you guessed the correct age of mine! And about computer science knowledge, I have some, since I have a pc (which is a F**king piece of $#!t). What did you thought who I am? And about the project section, @longjunyu2 mentioned something about OpenJDK 14 aarch32 build. [Here](https://github.com/orgs/AOF-Dev/projects/2) is the project link.
> > 
> > 
> > that doesnt work as mcinthebox use faster garbage collecter on there java so if we switch java it woeld be slow as pojav v3
> 
> As far as I know, MCinaBox uses that Java build in the runtime package! But yes Pojav is very slow...

ugh it compiled from special source ...

**Comment by LegacyGamerHD** [comment]
but i guesh we will see wo is right and then i warned you

**Comment by CosineMath** [comment]
Oh, note that the source codes of runtime pack are stored in my repositories. You might have a look on my github page.

**Comment by Iscle** [comment]
> Oh, note that the source codes of runtime pack are stored in my repositories. You might have a look on my github page.

Yep! I know :) I'm trying to build all of them, including openal-soft (which is not on your account) with no luck. Could you shine a bit of light on me?

What are the commands and toolchains required to build?

**Comment by CosineMath** [comment]
It required a standalone ndk toolchain (I use ndk r10e) to build. As for the config&build command, I have write a Makefile including all commands. I might release the Makefile later.

**Comment by Iscle** [comment]
> It required a standalone ndk toolchain (I use ndk r10e) to build. As for the config&build command, I have write a Makefile including all commands. I might release the Makefile later.

I tried r10e but it had issues during ./configure for the OpenJDK build. I had to set CUPS, X11, FREETYPE and FONTCONFIG as not needed just to get past that step. Then during the build, more issues about missing header files showed up.

**Comment by CosineMath** [comment]
OpenAL-soft and gl4es are not modified for Boat/MCinaBox so not in my repos.

**Comment by Iscle** [comment]
> OpenAL-soft and gl4es are not modified for Boat/MCinaBox so not in my repos.

Yep, I know! It's just that I can't get them to compile either... But thanks :) Looking forward for more info or the makefile

**Comment by AyHa1810** [comment]
@LegacyGamerHD ah, ok. I think I might have to live with the latest released version.

**Comment by AyHa1810** [comment]
@Iscle well, you can close most of the stupid issues. But sorry, I am not a programmer though. Maybe I would learn it someday, and contribute to this project.

**Comment by 1stS1d** [comment]
As far as the input issues go, I found that for some reason the default keybinding for the MCPE keyboard does not work in 1.16.x.  To fix this, go into Minecraft Controls and rebinding them.  For the mouse, make sure that Raw Input is turned off in Mouse Settings under Controls.

**Comment by AyHa1810** [comment]
@1stS1d well yeah, but default setting should also work normally.

**Comment by CosineMath** [comment]
@Iscle I have pushed the Makefile for building runtime pack in [Boat-reference-material](https://github.com/CosineMath/Boat-reference-material)

**Comment by Iscle** [comment]
> @Iscle I have pushed the Makefile for building runtime pack in [Boat-reference-material](https://github.com/CosineMath/Boat-reference-material)

Thanks! I managed to build lwjgl2 with the latest NDK and it's working perfectly so far. However, I'm trying to clean some things up as well as add some missing features (like URL opening) :) However, your work is amazing! Thanks!

**Comment by AyHa1810** [comment]
@Iscle, is your new layout is done? If it is, then merge it with the main repo. I wanna see the new layout working!

**Comment by Iscle** [comment]
> 
> 
> @Iscle, is your new layout is done? If it is, then merge it with the main repo. I wanna see the new layout working!

Thanks for your interest :D However, yesterday I lost the changes I made for the new UI, so I have to re-create it again. It's not too much work, less than 1 hour. 

However, the issue is that with the new layout I'm planning to also clean up some hacks that are currently making the app work, with proper implementations, so it's just not as easy as swapping one for the other.

That said, I'm working on it and I'm hoping it does not take much more time.

**Comment by AyHa1810** [comment]
If there aren't any final solution, then I am closing this issue. I hope if it gets solved soon.
