### ISSUE TITLE
Non installa forge sulle versioni 1.12 in sù dice download failed perfavore risolvere

### ISSUE THREAD

**Issue by maxhjchg** [AOF-Dev/MCinaBox#584]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy J6]
 - OS: [e.g. Android 8.1]
 - App Version [e.g. v0.1.3]

**Additional context**

**Comment by LegacyGamerHD** [comment]
follow the the issue template also english or chinese
