### ISSUE TITLE
Pasting not working

### ISSUE THREAD

**Issue by stacode123** [AOF-Dev/MCinaBox#585]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy J6]
 - OS: [e.g. Android 8.1]
 - App Version [e.g. v0.1.3]

**Additional context**

**Comment by LegacyGamerHD** [comment]
dublicated of #568

**Comment by LegacyGamerHD** [comment]
also follow the issue template
