### ISSUE TITLE
bugs：

### ISSUE THREAD

**Issue by MCMAKO** [AOF-Dev/MCinaBox#587]
错误机型红米k30；系统版本MIUI12，安卓10；游戏版本0.1.4-p3；首先0.1.4-p4的输入框在更新后几个小时发现接下来不能够唤醒键盘，各种方法都无效，包括清除数据并重建重装软件、重启手机，只能退回0.1.4-p3继续使用。

1、0.1.4-p3颜色代码出错会导致崩溃：
2、MIUI的通知栏消息在屏幕上方弹出来之后，整体按键会偏移往下方（软件触摸部分位置偏移，鼠标位置不偏移）；
3、希望可以解决后台切换回来软件不重启。

**Comment by vlad13310** [comment]
I need help<!-- Error while uploading SVID_20201023_161911_1.mp4

**Comment by longjunyu2** [comment]
已解决，See the lastest release.
