### ISSUE TITLE
Input box not functional.

### ISSUE THREAD

**Issue by IYeet205** [AOF-Dev/MCinaBox#588]
**Describe the bug**
The input box does not work at all. When I click it, the keyboard does not get pulled up.

**To Reproduce**
1. Go to the input box
2. Click it
3. See error

**Expected behavior**
The keyboard was supposed to pull up, allowing me to input letters into minecraft.

**Smartphone (please complete the following information):**
 - Device:Honor 10x
 - OS: Android 10
 - App Version v0.1.4 pre release 4

**Comment by LegacyGamerHD** [comment]
dublicated of #555
