### ISSUE TITLE
forge 1.7.10下载失败

### ISSUE THREAD

**Issue by slimeeeqaq** [AOF-Dev/MCinaBox#590]
RedmiK30
aarch64
![Screenshot_2020-10-23-19-08-46-975_com aof mcinabox](https://user-images.githubusercontent.com/73342071/96996931-54961680-1563-11eb-9111-46c6d4285e26.jpg)

**Comment by alex9900123** [comment]
Did you install version 1.7.10 first?

**Comment by slimeeeqaq** [comment]
installed
