### ISSUE TITLE
I Liked Mcinabox 0.1.3 But Needs 64RuntimePack

### ISSUE THREAD

**Issue by YGJumperli** [AOF-Dev/MCinaBox#594]
I rather playing 0.1.3 with aarch 64 i wish
I only played the beta version because of experiencing the
Runtime 64pack but i hope someone makes a Aarch64_Runtime Cuz I Really Need It, Thanks For Reading

**Comment by AyHa1810** [comment]
Well, newer versions are better. So, it would be better if you install it. Developers will not make any aarch64 runtime pack for this particular version. You should keep in mind there are many bugs in almost all versions as of this reply. Some devices have some particular bug, not on others. You can say all releases are in beta phase.  :)

**Comment by Iscle** [comment]
I'm working to make all the versions work. However, older versions get less priority.
