### ISSUE TITLE
Optifine 1.16.2

### ISSUE THREAD

**Issue by SakiKarened** [AOF-Dev/MCinaBox#595]
Hey, I've installed Optifine on my computer then move it to Mcinabox
The problem is that : 
Pojavlauncher run it 
Mcinabox doesn't
I use the aarch32 runtimes 
Someone can help me on how to fix it ?

**Comment by AyHa1810** [comment]
Well, MCinaBox can't run optifine without forge. You should install forge first.

**Comment by SakiKarened** [comment]
Same issues with Forge 1.16.2

**Comment by CosineMath** [comment]
Then you can just use PojavLauncher and wait for fix. Would you mind uploading the minecraft crash report to help fix this?

**Comment by SakiKarened** [comment]
Actually I can't because the game doesn't even launch then Mcinabox crash
(like 3 seconds on a black screen)

Le dim. 25 oct. 2020 à 02:26, CosineMath <notifications@github.com> a
écrit :

**Comment by KUALALUM** [comment]
> Hey, I've installed Optifine on my computer then move it to Mcinabox
> The problem is that :
> Pojavlauncher run it
> Mcinabox doesn't
> I use the aarch32 runtimes
> Someone can help me on how to fix it ?

Try 1.12.2 it might works

**Comment by SakiKarened** [comment]
But I need the 1.16.2 I know that 1.12.2 works
