### ISSUE TITLE
Can i install Forge and Optifine on MCinaBox 0.1.4 p4?

### ISSUE THREAD

**Issue by PeterScorPioN** [AOF-Dev/MCinaBox#606]
I wanted to install at least some mods on 1.8.9 (which version runs pretty good on my phone.) And when i go to install its Forge, it says "Failed to install" or something like that... Please tell me if there is a possible way to play with mods in 0.1.4 pre4, or i must wait until you fix that?

My device: Xiaomi Pocophone F1
6GB RAM
64 BIT
SNAPDRAGON 845
ANDRENO 630 GPU
ANDROID 10

Edit: i fixed it and downloaded the Forge 1.8.9. Now the problem is that i cannot install Forge for 1.12.2. i tried everything. The universal package doesn't work and when i try to install it, this error pops up:
![Screenshot_2020-10-28-08-01-48-782_com aof mcinabox](https://user-images.githubusercontent.com/73193067/97404646-1ac86580-18ff-11eb-8efc-4f3402b818c3.jpg)
I tried installer too and it actually installed, but it was crashing on every opening, also telling that there will be no sound in the game.

**Comment by Tol561** [comment]
I tested this version on forge. I have a forge easily installed and I tried a few mods they worked on, but some not. There are several solutions to install. 1) Find the Minecraft 1.12.2 forge file on the sites and download it and move it to the folder in the version. 2) Download the last version of the forge and in the mcinabox find the file that you downloaded and install ( Not which of them is not installed . Try the old versions forge and do as well )

**Comment by Tayoikoo** [comment]
Use this version:
forge 14.23.0.2486. (1.12.2)
If this version cannot install then use this:
forge 14.23.5.2854 (1.12.2)

**Comment by PeterScorPioN** [comment]
Thank you a lot! It worked! I installed some mods and they all work! By the way, another solution can be just copying and pasting a Forge from your PC to your phone.

**Comment by MatheusTgamerPro** [comment]
Qual Forge Funcionaram no seus Laucher!! poderia passar algumas versoes do forge que funcionarao? Tipo a 1.7.10 e a 1.8.9?

**Comment by PeterScorPioN** [comment]
> Qual Forge Funcionaram no seus Laucher!! poderia passar algumas versoes do forge que funcionarao? Tipo a 1.7.10 e a 1.8.9?

Firstly i speak English (or Russian). Secondly, every Forge, from 1.6.x to 1.12.x works on my phone. I just did the installation wrong.

**Comment by ThatMG393** [comment]
How To Install Optifine On v0.1.4-pre3 I lnow how to install it on v0.1.3 but on v0.1.4-pre3 i dunno how. Please Help
