### ISSUE TITLE
Will there ever be a arm64 or armhf linux release of the touch controller?

### ISSUE THREAD

**Issue by FreddyFeuerstein** [AOF-Dev/MCinaBox#607]
I have an old Tablet that is running linux and therefor can not run MCinaBox. Running minecraft with the official launcher works. But there are no controlls. A customizable touch keyboard would be nice for everyone not wanting to plug in a keyboard or connect joycons.
I would love to get a linux release of just the customizable virtual keyboard.

**Comment by Malaska678** [comment]
U can flash android there

**Comment by Malaska678** [comment]
But its risky.

**Comment by Malaska678** [comment]
And clear data on your tab

**Comment by Malaska678** [comment]
if have intel inside use android x86 instead of normal android

**Comment by CosineMath** [comment]
(But this is not related to MCinaBox...

**Comment by Malaska678** [comment]
He ask if there would ever be a mcinabox for linux tab

**Comment by FreddyFeuerstein** [comment]
> He ask if there would ever be a mcinabox for linux tab

No, i just want to get touch controlls for linux.

**Comment by FreddyFeuerstein** [comment]
I found something that works for me: https://github.com/nitg16/TabPad
Still has some bugs but nothing i couldn't fix.

**Comment by khanhduytran0** [comment]
Try Anbox, Android for Linux https://github.com/anbox/anbox
