### ISSUE TITLE
Optifine crashes when trying to run SEUS PTGI

### ISSUE THREAD

**Issue by FreddyFeuerstein** [AOF-Dev/MCinaBox#608]
**Describe the bug**
Selecting any shader in Optifine crashes the game when opening a world. No log or error messages will be generated at all.

**To Reproduce**
1. Go to 'Optifine U_HD_F3 1.12.2'.
2. Go to Options.
3. Go to Video settings -> shaders.
4. Select a shader that is not build-in.
5. Open a world or connect to a server.
6. See error

**Expected behavior**
I expected it to load the world, lag a bit and have fancy grafics.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A40
 - OS: Android 9 with 5.4 kernel
 - App Version 0.1.4-p3

**Comment by Malaska678** [comment]
Did u know that it exploded some pc? Do u want to lose your hands?

**Comment by artdeell** [comment]
Shader conversion is still early, shader just won't compile anyway.

вт, 27 окт. 2020 г., 08:56 Freddy Feuerstein <notifications@github.com>:

**Comment by Malaska678** [comment]
But muhd arafat found shader that work

**Comment by Malaska678** [comment]
@artdeell

**Comment by artdeell** [comment]
Yeah, but still, most don't. Including SEUS (i think).

вт, 27 окт. 2020 г., 10:40 Malaska678 <notifications@github.com>:
