### ISSUE TITLE
Mcinabox Work on Lgk50s?

### ISSUE THREAD

**Issue by GusbGamer** [AOF-Dev/MCinaBox#609]
Does Mcinabox work on Lgk50s?

**Comment by PeterScorPioN** [comment]
Dude, i saw your phone's specs and if i found the right phone, you actually can run it, but honestly it will lag. A lot. You cannot expect good performance from a phone for less than 150$. Anyway, if you select an old version, like 1.7.10 and low the graphics down (also recommended Optifine), you can get a kinda good amount of fps. Or you should just, you know, GET A CHEAP FLAGSHIP! I have Xiaomi Pocophone F1 and i get more than 60 fps on 1.12.2 (without Optifine).

**Comment by GusbGamer** [comment]
> Cara, eu vi as especificações do seu telefone e se eu encontrar o telefone certo, você realmente pode executá-lo, mas honestamente ele vai atrasar. Muito. Você não pode esperar um bom desempenho de um telefone por menos de 150 $. De qualquer forma, se você selecionar uma versão antiga, como 1.7.10 e diminuir os gráficos (também recomendado Optifine), você pode obter uma boa quantidade de fps. Ou você deveria, você sabe, OBTER UMA BANDEIRA BARATA! Eu tenho Xiaomi Pocophone F1 e obtenho mais de 60 fps no 1.12.2 (sem Optifine).



> Dude, i saw your phone's specs and if i found the right phone, you actually can run it, but honestly it will lag. A lot. You cannot expect good performance from a phone for less than 150$. Anyway, if you select an old version, like 1.7.10 and low the graphics down (also recommended Optifine), you can get a kinda good amount of fps. Or you should just, you know, GET A CHEAP FLAGSHIP! I have Xiaomi Pocophone F1 and i get more than 60 fps on 1.12.2 (without Optifine).

I Wanted To Know Why I'm Using My Grandma's Cell Phone, The Device I Wore Broke Recently
