### ISSUE TITLE
Close all the stupid issues!

### ISSUE THREAD

**Issue by AyHa1810** [AOF-Dev/MCinaBox#611]
Damn, whats up with you issue makers? It's totally stupid to create a new issue for a basic thing! This project is still in a development phase, so there is a lot of bugs. You can still play Minecraft if you manage to get it work. If you want to create a new issue, then make it about an actual issue, and also think many times about it before making it. If your issue gets solved or you get a right answer to your question, you should close the issue. A developer have to work hard on a project to make it perfect and successful. So you shouldn't blame over them for a stupid problem.

**Comment by LegacyGamerHD** [comment]
I can close them but people will be pist at me

**Comment by AyHa1810** [comment]
well, you can mention this issue.

**Comment by YGJumperli** [comment]
This issue is also a stupid

**Comment by AyHa1810** [comment]
@YGJumperli 
![dsmGaKWMeHXe9QuJtq_ys30PNfTGnMsRuHuo_MUzGCg](https://user-images.githubusercontent.com/63386848/97540644-f0070b80-19e9-11eb-8f6b-1e1da57693b0.jpg)

**Comment by LegacyGamerHD** [comment]
> This issue is also a stupid

i dont think so

**Comment by FrankOu2001** [comment]
> Damn, whats up with you issue makers? It's totally stupid to create a new issue for a basic thing! This project is still in a development phase, so there is a lot of bugs. You can still play Minecraft if you manage to get it work. If you want to create a new issue, then make it about an actual issue, and also think many times about it before making it. If your issue gets solved or you get a right answer to your question, you should close the issue. A developer have to work hard on a project to make it perfect and successful. So you shouldn't blame over them for a stupid problem.

> Damn, whats up with you issue makers? It's totally stupid to create a new issue for a basic thing! This project is still in a development phase, so there is a lot of bugs. You can still play Minecraft if you manage to get it work. If you want to create a new issue, then make it about an actual issue, and also think many times about it before making it. If your issue gets solved or you get a right answer to your question, you should close the issue. A developer have to work hard on a project to make it perfect and successful. So you shouldn't blame over them for a stupid problem.

I'm totally agree with you!

**Comment by YGJumperli** [comment]
Its normal to have a lot of issues because this is not the official minecraft java laucher for android lmao

**Comment by KeyzGames** [comment]
> Its normal to have a lot of issues because this is not the official minecraft java laucher for android lmao

nah yes.

**Comment by Iscle** [comment]
> Its normal to have a lot of issues because this is not the official minecraft java laucher for android lmao

And what's the problem of it not being official? If you don't like it, don't use it.

If you have a serious issue, check is the issue is already reported. Only then, if it's not reported, open a new issue following the template.

Simple.

**Comment by Malaska678** [comment]
> > Its normal to have a lot of issues because this is not the official minecraft java laucher for android lmao
> 
> And what's the problem of it not being official? If you don't like it, don't use it.
> 
> If you have a serious issue, check is the issue is already reported. Only then, if it's not reported, open a new issue following the template.
> 
> Simple.

@Iscle It is very simple that android has alot of limitation making this project hard to be completed. But im agree that in future we can run minecraft java on android with no problem.

**Comment by leetmussc** [comment]
I'll close every issue I have made or opened

**Comment by leetmussc** [comment]
@LegacyGamerHD Can you close some of the issues that don't need to be on here?

**Comment by YGJumperli** [comment]
> > Its normal to have a lot of issues because this is not the official minecraft java laucher for android lmao
> 
> And what's the problem of it not being official? If you don't like it, don't use it.
> 
> If you have a serious issue, check is the issue is already reported. Only then, if it's not reported, open a new issue following the template.
> 
> Simple.

Everything has an issue and its normal to have an issue is that enough?

**Comment by YGJumperli** [comment]
Even the mcpe offcial latest version has an also an issue do you understand that?!

**Comment by artdeell** [comment]
Like, well, there are many duplicates and just "not working" issues

пт, 30 окт. 2020 г., 11:08 YGJumperli <notifications@github.com>:

**Comment by AyHa1810** [comment]
@LegacyGamerHD I don't think this issue has any use, so I am closing it.
