### ISSUE TITLE
Does anyone want a x86 release? Note: I made one anyways.

### ISSUE THREAD

**Issue by FreddyFeuerstein** [AOF-Dev/MCinaBox#613]
I have made an x86 version of MCinaBox with an x86 runtime pack.
Download link: ~~https://drive.google.com/file/d/17bA3sYEJ6l2xmtCiC-ox11tTVIf8Nxtc/view~~
Anyways, have a nice day.
Edit:
Old one was unreliable.
Here is the new link: 
Runtime: https://letsupload.io/4Owwg
APK: https://letsupload.io/4Owwh

**Comment by AjGamingPHOfficial** [comment]
Thxx

**Comment by rApHaEL1211** [comment]
Wait what?!

**Comment by YGJumperli** [comment]
This can be only used for x86 device right??

**Comment by Malaska678** [comment]
It was not needed becoz u can use libhoudini

**Comment by Malaska678** [comment]
If u dont know what is it, it is arm apps on x86 (android)

**Comment by FreddyFeuerstein** [comment]
> This can be only used for x86 device right??

yes.

**Comment by khanhduytran0** [comment]
You copied from Linux/GNU which Android Bionic libc could not execute.

**Comment by khanhduytran0** [comment]
https://github.com/AOF-Dev/MCinaBox/issues/183#issuecomment-638786934

**Comment by FreddyFeuerstein** [comment]
> [#183 (comment)](https://github.com/AOF-Dev/MCinaBox/issues/183#issuecomment-638786934)

I tried this on an old Intel tablet with android x86 and it worked.

**Comment by khanhduytran0** [comment]
![_20201029_121047](https://user-images.githubusercontent.com/40482367/97790692-4e580800-1bfd-11eb-9f06-e2f644f7d75e.jpg)
It didn't link to Android libs, which does not ends with a version number.

**Comment by FreddyFeuerstein** [comment]
> ![_20201029_121047](https://user-images.githubusercontent.com/40482367/97790692-4e580800-1bfd-11eb-9f06-e2f644f7d75e.jpg)
> It didn't link to Android libs, which does not ends with a version number.

I mean if it works then its ok, right?
Doesn't allways have to be pretty.

**Comment by CosineMath** [comment]
> > ![_20201029_121047](https://user-images.githubusercontent.com/40482367/97790692-4e580800-1bfd-11eb-9f06-e2f644f7d75e.jpg)
> > It didn't link to Android libs, which does not ends with a version number.
> 
> I mean if it works then its ok, right?
> Doesn't allways have to be pretty.

Yeah, it is nice but not for MCinaBox.

**Comment by FreddyFeuerstein** [comment]
I finally got around to fix it.
Here is the new link: 
APK: https://letsupload.io/4Owwg
Runtime: https://letsupload.io/4Owwh

**Comment by khanhduytran0** [comment]
JRE9 structures? Let me go deeper. It's easy to detect it's source just by hex editor: https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/307713621
![Screenshot_2020-11-24-12-34-07](https://user-images.githubusercontent.com/40482367/100053030-c6f36280-2e51-11eb-9497-ac80c130a098.png)

**Comment by artdeell** [comment]
Did you STOLE a build?
Like, there's no such thing as stealin in open-source world, but don't you
think that it's kinda douchy to take something and don't mention the
original?

пн, 23 нояб. 2020 г., 19:52 Freddy Feuerstein <notifications@github.com>:

**Comment by SavagePy10** [comment]
@artdeell its not surprising. Mt launcher copies pojav before.

**Comment by SavagePy10** [comment]
Its too obvious that this guy copy someone coz he is phyton coder not C++ coder. (No offense, even phyton can be difficult)
