### ISSUE TITLE
New launcher ui

### ISSUE THREAD

**Issue by KUALALUM** [AOF-Dev/MCinaBox#616]
This ui made by neonz gaming and i just make the issue 
U can watch the video [Right here](https://youtu.be/fc5Ux2LYxIQ) 
Or [This](https://youtu.be/Tsl1iw_Y4So)

**Comment by NeonzGamingYT** [comment]
Ok thanks

**Comment by KUALALUM** [comment]
Welcome

**Comment by Iscle** [comment]
We already have an issue related to this. We're working to make it look as close as posible to the original PC launcher. Check out this issue: https://github.com/AOF-Dev/MCinaBox/issues/560
