### ISSUE TITLE
Could not create EGL context

### ISSUE THREAD

**Issue by Malaska678** [AOF-Dev/MCinaBox#619]
https://hasteb.in/mifojipo.yaml

**Comment by Malaska678** [comment]
@Developers ?

**Comment by Malaska678** [comment]
@AOF-DEV

**Comment by Malaska678** [comment]
Start up bugs like this always affects me

**Comment by Iscle** [comment]
Hi, the link points to an empty file :(

**Comment by Malaska678** [comment]
> Hi, the link points to an empty file :(

Becoz it got expired

**Comment by Malaska678** [comment]
@Iscle

**Comment by Malaska678** [comment]
But the only important thing is it cant create EGL context

**Comment by Malaska678** [comment]
Any fix?

**Comment by SnowNF** [comment]
Sorry,without log file(s), we can't discover problem in detail.

**Comment by Iscle** [comment]
May I know why you have my picture as your profile picture please? @Malaska678

**Comment by Malaska678** [comment]
> May I know why you have my picture as your profile picture please? @Malaska678

@Iscle For joke only

**Comment by Iscle** [comment]
> > May I know why you have my picture as your profile picture please? @Malaska678
> 
> @Iscle For joke only

Change it please. I did not give you permission to usethe picture. This is illegal.

**Comment by Malaska678** [comment]
> > > May I know why you have my picture as your profile picture please? @Malaska678
> > 
> > 
> > @Iscle For joke only
> 
> Change it please. I did not give you permission to usethe picture. This is illegal.

Sure. Why would i keep it?

**Comment by Malaska678** [comment]
> > > May I know why you have my picture as your profile picture please? @Malaska678
> > 
> > 
> > @Iscle For joke only
> 
> Change it please. I did not give you permission to usethe picture. This is illegal.

Sorry

**Comment by Malaska678** [comment]
I didn't want to dissapoint someone.
