### ISSUE TITLE
I have 2 problems.

### ISSUE THREAD

**Issue by SNWCreations** [AOF-Dev/MCinaBox#622]
**Describe the bug**
Two problems:
1.Why did I change the download source and refresh the game download list and crash?
2.My settings are OK, but starting the game will cause the launcher to crash!
(special setting: game directory is "private directory")

My program crashed!
Mobile phone: Redmi Note 5 Plus
System: stable version of MIUI 11.0.3

**To Reproduce**
Problem 1:
1. Enter the starter settings and change the download source
2. Enter the game download page (at this time, it has been loaded once before changing the download source), and click refresh
3. then... And it broke down...

Problem 2:
Start the game directly, and then crash when starting after checking.

**Comment by SkilledHasBadPC** [comment]
Answer to problem 2: Have you tried changing the ram amount? Maybe changing it to a lower amount will help.
also tell me the mcinabox version pls

**Comment by SNWCreations** [comment]
> Answer to problem 2: Have you tried changing the ram amount? Maybe changing it to a lower amount will help.
> also tell me the mcinabox version pls

"Answer to problem 2: Have you tried changing the ram amount?"
I tried, and I still broke down.

"also tell me the mcinabox version pls"
v0.1.4-p4

**Comment by CosineMath** [comment]
Logs please

**Comment by SNWCreations** [comment]
> Logs please

Sorry?
The problem seems impossible to report.
Because I deleted the software and used the old version.
This report may be invalidated.
