### ISSUE TITLE
Cannot connect to servers even If i moved the servers.dat file to .minecraft

### ISSUE THREAD

**Issue by saibot-tsch** [AOF-Dev/MCinaBox#631]
Hello.
As I moved the servers.dat file from my PC to the .minecraft folder to input some servers to MCinaBox as I couldnt type in a address to add a new server.
The servers appear now but I have a problem. I want to connect to hypixel.net for example and it doesnt work even with their IP address 172.65.201.224 as you cant connect over the IP address. 
Is there a way to connect though?
Thanks.

Smartphone Specs:
 - Device: [Samsung Galaxy S7]
 - OS: [Android 8.0.0]
 - App Version: [v0.1.3]

**Comment by SkilledHasBadPC** [comment]
Have you tried the `<>` button yet? It lets you use the system keyboard to type in text boxes in game.

**Comment by saibot-tsch** [comment]
Ive tried it too it doesnt work. The main problem is that after trying connect to servers with the normal address name it gives a Timeout error

**Comment by ReinerPing** [comment]
I also had this problem. I have found an answer on a different post. Go to this Website: https://mxtoolbox.com/SRVLookup.aspx and type in _minecraft._tcp.(*YOUR IP*) then it will tell you an other IP that works.

**Comment by Tommy2678** [comment]
THANK YOU SO MUCH
