### ISSUE TITLE
Make A Hacked Client Installer

### ISSUE THREAD

**Issue by ThatMG393** [AOF-Dev/MCinaBox#638]
Please Make A Hacked Client Installer

**Comment by FreddyFeuerstein** [comment]
You can use pojav launcher and then copy the .minecraft folder over to the /sdcard/MCinaBox/gamedir directory

**Comment by khanhduytran0** [comment]
@FreddyFeuerstein PojavLauncher is not designed for MCinabox.

**Comment by CosineMath** [comment]
Just copy hacked version to .minecraft.
