### ISSUE TITLE
源代码是什么类型？是正念还是我不知道，请告诉我

### ISSUE THREAD

**Issue by Mynameispoop** [AOF-Dev/MCinaBox#640]
1. If you have any questions, you can ask here and wait for the answers.
2. You can also post files or screenshots if it is related to the question.

**Comment by CosineMath** [comment]
很抱歉不知道你在说什么，可以加以解释吗？

**Comment by Mynameispoop** [comment]
我的意思是N-ide

**Comment by Mynameispoop** [comment]
顺便问一下，所有创作者都是在哪里制作该应用的？ PC或Android

**Comment by Mynameispoop** [comment]
我想知道应用程序

**Comment by CosineMath** [comment]
（你的中文好奇怪啊）
这是个Android Studio项目。

**Comment by CosineMath** [comment]
如果你不太会中文，请使用英文。

**Comment by Malaska678** [comment]
> 如果你不太会中文，请使用英文或你的母语。

Chinese is hardest language

**Comment by Mynameispoop** [comment]
非常感谢您告诉我余弦
