### ISSUE TITLE
Longjunyu2!

### ISSUE THREAD

**Issue by AjGamingPHOfficial** [AOF-Dev/MCinaBox#648]
Longjunyu2
Can u make Aarch Runtime 64 bit
Work on 1.13+??

And change the ram limit too for 64 bit :)

Thx

**Comment by NidzGamingTV** [comment]
Up! We badly need this @longjunyu2 @Iscle

**Comment by Iscle** [comment]
Oh really? We didn't know there was an issue with this...

Jokes aside, we're working on it, and it will be published after it works, not before.

**Comment by CosineMath** [comment]
I am working on this. It takes time.

**Comment by AjGamingPHOfficial** [comment]
Ohh
THANKS VERY BIG THANKS😁😁😁

**Comment by AjGamingPHOfficial** [comment]
Ohhh

VERY BIG THANKS
:))
