### ISSUE TITLE
Memory max limit add more

### ISSUE THREAD

**Issue by crazymobile** [AOF-Dev/MCinaBox#650]
MY PHONE IS 6GB RAM 65GB ROM BUT MY
MEMORY MAX IS ONLY 462 PLSS FIX 
IN OLD VERSION I GOT 1.200 GB MEMORY MAX
NOW NEW VERSION MUCH LOWER LIKE
CAN BE PLAYED BECAUSE TO MUCH LOG 
PLSS FIX I WANT TO PLAY 1.16 WITHOUT LOG
OR CRASH

**Comment by PeterScorPioN** [comment]
I have the same RAM and ROM with you and i can put as much, as i want and have. I have dedicated up to 2048 MB and everything works fine.

**Comment by PeterScorPioN** [comment]
Now, about 1.16... You should do some tricks to play in newer versions. I prefer playing in 1.12.2...

**Comment by crazymobile** [comment]
Thank you very very much 🥰 this is great help🥰🥰🥰

**Comment by PeterScorPioN** [comment]
> Thank you very very much 🥰 this is great help🥰🥰🥰

Always welcome.👍

**Comment by crazymobile** [comment]
You send 2048 almost 1000mb now but it's crash can you pls help me how did you do that?

**Comment by PeterScorPioN** [comment]
> help

What version did you select?

**Comment by crazymobile** [comment]
1.12.2

**Comment by PeterScorPioN** [comment]
And you tell me that it crashes with more RAM dedicated. Can you tell me the version of MCinaBox you have and also your phone model?

**Comment by crazymobile** [comment]
Mcinabox latest version xiaomi 9t ram 6 ROM 65

**Comment by PeterScorPioN** [comment]
Well, the same fro me, except that i have Xiaomi Pocophone F1. If you really have the 0.1.4. pre4 and it crashes with more RAM, i don't know what i can halp you with. Just try to find the perfect RAM, for the launcher.

**Comment by crazymobile** [comment]
Ok thanks for the help because you I have 1100 mb 😁

**Comment by matthewdm0816** [comment]
Maybe turn off the "auto memory" option just under the memory seting textbox?

**Comment by crazymobile** [comment]
I already do that is off when I change only 1000mb can't higher anymore 😅

**Comment by matthewdm0816** [comment]
Seems that the repo had written [here](https://github.com/AOF-Dev/MCinaBox/issues/650#issuecomment-724525581), that the maximum memory is limited by system
> 
> 
> I already do that is off when I change only 1000mb can't higher anymore 😅

**Comment by crazymobile** [comment]
So can't be higher memory anymore? Do you have trick how to get high than I have now?

**Comment by manolis07** [comment]
If you have the 32 bit version of the app it limits your ram to about 800 mb but allows you to play 1.15+ but if you are using the 64 bit one the the ram you can put is near to unlimited but you can't play Minecraft 1.15+ because it will just crash but I believe that this will not be the case after some updates I hope I helped you feel free to ask me anything

**Comment by crazymobile** [comment]
Ok I will wait for the update and ask your help😁

**Comment by traver111** [comment]
Worst launcher ever!!
