### ISSUE TITLE
Crash on starting mc 1.7.10

### ISSUE THREAD

**Issue by imlegend3705** [AOF-Dev/MCinaBox#653]
When I start minecraft 1.7.10 forge my phone hang

How to reproduce the crash:-start a du recorder
Recording with phone mic and open mcinabox v0.1.4 p4 and start minecraft 1.7.10 forge with 45 mods and allocate 2000mb ram to mcinabox and your phone must be redmi 3s prime gold 32gb storage and 4gb ram and when the Mojang logo shows up in minecraft the phone hang

Android version:-9
Program version:-0.1.4p4

And also please subscribe to my YouTube channel from this link https://bit.ly/31j0OXd
 Please fix crash I need to record videos for my YouTube channel

**Comment by Adity-png** [comment]
What the fuck
