### ISSUE TITLE
Forge 1.12 does not work:(

### ISSUE THREAD

**Issue by ashurach** [AOF-Dev/MCinaBox#654]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy J6]
 - OS: [e.g. Android 8.1]
 - App Version [e.g. v0.1.3]

**Additional context**

**Comment by SupinePandora43** [comment]
🤦 not reproduceable

**Comment by CosineMath** [comment]
...no more details

**Comment by SupinePandora43** [comment]
i've successfully ran `1.12.2-forge-1.12.2-14.23.5.2847`, using
Max Memory (MB): 1024,
my phone is Redmi Note 9 Pro, with 6 gb of ram
