### ISSUE TITLE
Android 10 Crash

### ISSUE THREAD

**Issue by Neubulae** [AOF-Dev/MCinaBox#655]

**Comment by ITZPGDYT** [comment]
when does the crash happen?

**Comment by MatheusTgamerPro** [comment]
@ITZPGDYT  This occurs when you click on the white key when entering the game

**Comment by Iscle** [comment]
Can you please upload some logs so we can take a look? It works fine for me on Android 11...

**Comment by AjGamingPHOfficial** [comment]
Yeah same
Its working on me
Im android 1p

**Comment by CosineMath** [comment]
No log...
