### ISSUE TITLE
Is it possible to run shaders in MC 1.12.2 (MCinaBox 0.1.4 p4)?

### ISSUE THREAD

**Issue by PeterScorPioN** [AOF-Dev/MCinaBox#656]
If there is a possible way to run a shader in 1.12.2, i would like to know that. I say that, because i can offer this to myself. I have a pretty good phone, so i think it will run at least Chocapic13's Toaster Edition shaders.

My phone's specs:

RAM: 6GB
CPU: Snapdragon 845
GPU: Andreno 630
OS: Android 10
Phone model: Xiaomi Pocophone F1

**Comment by Malaska678** [comment]
Even if u have higher phone, gl4es dont support shader properly. So only simple ones can work.

**Comment by PeterScorPioN** [comment]
> Even if u have higher phone, gl4es dont support shader properly. So only simple ones can work.

So you mean that only shaders without moving shadows can work, right?

**Comment by PeterScorPioN** [comment]
> > Even if u have higher phone, gl4es dont support shader properly. So only simple ones can work.
> 
> So you mean that only shaders without moving shadows can work,

**Comment by Malaska678** [comment]
Yeah.

**Comment by Malaska678** [comment]
One good example is sildurs

**Comment by Malaska678** [comment]
Jk
