### ISSUE TITLE
BUG INPUT BOX MCINABOX 0.1.4-P4

### ISSUE THREAD

**Issue by Cheater2020** [AOF-Dev/MCinaBox#657]
Hai longjunyu2 saya dari indonesia nama saya radit dan saya ingin menyampaikan tentang bug yang saya temukan di mcinabox 0.1.4-p4.
saat Saya Sedang Mengaktifkan input box di mcinabox 0.1.4-p4 dan kemudian saya ingin mengetik itu tidak muncul keyboard android saya mohon segera di perbaiki bug nya saya sangat suka dengan mcinabox 0.1.4-p4 karena bisa memainkan versi 1.16.3 dan juga saya sudah tidak pernah mengalami force close pada mcinabox versi terbaru mohon segera di perbaiki terima kasih😁🙏

**Comment by KUALALUM** [comment]
Guna pc keyboard lepas tu on enable type di pojok atas kanan

**Comment by LegacyGamerHD** [comment]
know isseu there are now 5 up more issue about this use thye latest dev build

**Comment by Cheater2020** [comment]
Apakah laporan saya akan di ditanggapi?

**Comment by KUALALUM** [comment]
Tidak

**Comment by Cheater2020** [comment]
@KUALALUM Anda siapa menjawab seperti itu? Apakah anda bagian dari proyek ini?

**Comment by KUALALUM** [comment]
Tidak

**Comment by Cheater2020** [comment]
Terserah

**Comment by LegacyGamerHD** [comment]
Saya ingin sekali jika bahasa Inggris diucapkan ada 6 obat masalah yang sama, ini adalah salah satunya

**Comment by Cheater2020** [comment]
@LegacyGamerHD saya minta maaf karena tidak memakai bahasa inggris itu karena saya tidak bisa bahasa inggris saya mohon maaf

**Comment by Niks-chan** [comment]
@WesleyVanNeck so can you delete this post?
