### ISSUE TITLE
Cannot run version newer than 1.12 (so far)

### ISSUE THREAD

**Issue by stevefan1999-personal** [AOF-Dev/MCinaBox#665]
**Describe the bug**
See title

**To Reproduce**
1. Download any past MC version after 1.12
2. After a long load, CTL (crash to launcher)

**Expected behavior**
Game runs

**Smartphone (please complete the following information):**
 - Device: S20 FE 5G
 - OS: Android 10
 - App Version: v0.1.4-p4

**Additional context:**
~~Haven't checked debug log yet but I think this is 99% related to the new MC launch animation, i.e. new Mojang loading logo. The animation part requires some specific OpenGL extension that OpenGLES cannot handle switftly/the emulation not handled correctly, hence the crash.~~

This should be because of library loading capability issue

**Comment by stevefan1999-personal** [comment]
[Desktop.zip](https://github.com/AOF-Dev/MCinaBox/files/5518677/Desktop.zip)
Here are some crash logs for analysis

**Comment by CosineMath** [comment]
aarch64 not supported for 1.13+. Use 32bit version please.
