### ISSUE TITLE
Joystick support

### ISSUE THREAD

**Issue by stevefan1999-personal** [AOF-Dev/MCinaBox#666]
**Describe the solution you'd like**
Implement joystick support. It is certainly not going to be natively integrated as I recall Java Edition does not have joystick support out of the box, and one of the Forge mod that claimed to support joystick is actually dead and unusable.

My advice: translate the joystick input into keyboard input (assuming the user does not change the keymap, then we can bind the key's one-to-one), e.g. X to Space just like BE and Steam Gamepad emulation. Then we translate analog stick movement into WASD (left stick) and mouse movement for camera angle (right stick)

This is going to be a medium-sized work.

**Is your feature request related to a problem? Please describe.**
I know Minecraft is not supposed to be played on mobile as it has a lot of complicated movements and interactions that even BE version's UX design is very limited and badly implemented compared to PC version (e.g. chest size misalignment). Generally speaking, all mobile games suck with such a small screen. Tablet only make it a little better but the touch screen sensitivity & latency issue make it unbearable sometimes, especially with touch based rhythm games that they eventually have to approximate finger movement to compensate the precision and timing issue.

However, I think MC will be fantastic to use an external controller instead of relying on touch control, as we can lift the user interaction to a much more precise controller and we have more breathing room for error. Plus there's joystick support in BE and my experience is great so far from my perspective, both from BE PC and BE Android. Real story: I can just hop into my BE server (realm for some others) in my bed, hung the phone in a holder, and play MC with the controller until I starting to yearn for sleep.

**Describe alternatives you've considered**
Using a Bluetooth keyboard an mouse. I will have a totally native MC experience, but it takes a lot more space and defeats the entire purpose of this project (Runs MOBILE MC but with Java Edition, mobility is the key). I cannot carry it out with me causally for example.

**Additional context**
I think there are already joystick to keyboard emulator out in Play Store but I haven't tested it out. But my guess is there will be no analog sticks support to what I described.

Specifically I use Xbox One controller but any other BT joysticks should do the same.

**Comment by Iscle** [comment]
This is a good idea, I will keep it in mind for the future.

**Comment by longjunyu2** [comment]
#800 
Have supported Xbox One with android 8 and higher.
