### ISSUE TITLE
Do optimizing mods work normally on MCinaBox?

### ISSUE THREAD

**Issue by PeterScorPioN** [AOF-Dev/MCinaBox#681]
I know, it's a hard question to answer, but i would like to know if mods that optimize minecraft (Phosphor, Surge, VanillaFix, BetterFPS) work as they need to work in MCinaBox. I play on 1.12.2 with these mods mentioned upper. The problem is that i use the same mods in my laptop when i play the same 1.12.2 and i get what i expect to get, 100+ FPS, when in my phone, since i got these mods, i noticed that the game started to lag. If this is possible, can i get an answer?

**Comment by MatheusTgamerPro** [comment]
Like I'm not a developer but, in my opinion they work just like OptFine but like OptFine and "Official" I think like BetterFPS and these things help but VERY little ...

**Comment by PeterScorPioN** [comment]
> Like I'm not a developer but, in my opinion they work just like OptFine but like OptFine and "Official" I think like BetterFPS and these things help but VERY little ...

Thanks dude, but I'd rather to get a better answer.

**Comment by FreddyFeuerstein** [comment]
From my testing, optifine (loaded directly, not from forge) can give me an increase of up to 15 fps. The betterfps mod just simply crashes.

**Comment by PeterScorPioN** [comment]
> From my testing, optifine (loaded directly, not from forge) can give me an increase of up to 15 fps. The betterfps mod just simply crashes.

Oh. Well, i actually run Optifine with Forge and using a flagship smartphone (Pocophone F1) i get up to 100 fps, also using the BetterFps mod.

**Comment by FreddyFeuerstein** [comment]
> > From my testing, optifine (loaded directly, not from forge) can give me an increase of up to 15 fps. The betterfps mod just simply crashes.
> 
> Oh. Well, i actually run Optifine with Forge and using a flagship smartphone (Pocophone F1) i get up to 100 fps, also using the BetterFps mod.

I didnt say that i only have 15 fps. I said that i have 15 fps MORE with optifine than without.
I usually get around 80 fps with optifine 1.12.2
