### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Kelicker** [AOF-Dev/MCinaBox#683]
i installed runtime pack, imported, but it says that i dont have a pack(

**Comment by xszqxszq** [comment]
If you downloaded runtime pack for 0.1.0 and imported it to 0.1.4-p2+, please download the runtime on the 0.1.4-p2 release page and import that. There might be differences between old runtime packs and new ones.

**Comment by CosineMath** [comment]
Use corresponding runtime pack.
