### ISSUE TITLE
My game crashes when world loading is at 30%

### ISSUE THREAD

**Issue by chinh4thepro** [AOF-Dev/MCinaBox#690]
**Describe the crash**
When I open a world or make a new world it crashes around 30-40%

**To Reproduce**
Steps to reproduce the crash:
1. Go to singleplayer
2. Click on make a new world
3. Wait for it to finish to 30-40%
4. See the crash

**Expected behavior**
I expected it to finish making the world with no problems

**Screenshots**
![Screenshot 2020-11-17 at 9 57 49 AM](https://user-images.githubusercontent.com/34662114/99407090-b163c300-28bc-11eb-9b85-adcc570403eb.png)
![Screenshot 2020-11-17 at 10 06 33 AM](https://user-images.githubusercontent.com/34662114/99407114-baed2b00-28bc-11eb-9e39-76507d967739.png)

**Device Info**
 - Device: Lenovo C330 Chromebook 
 - OS: Chrome OS: Version 86.0.4240.183 (32 bit) Android Subsystem: Version Android 9
 - App Version v0.1.4-p4-arm32

**Additional context**
This is on the latest release of Minecraft

**Comment by MatheusTgamerPro** [comment]
It has Various Possibilities of Error men, May be Android 9.0 that is happening Various Crash errors or May be The Downloaded Version.

**Comment by MondeeArcade** [comment]
U May have download runtime 64 maybe that the issue take to download runtime 32
![20201121_141111](https://user-images.githubusercontent.com/63823528/99886608-843c4b00-2c03-11eb-860c-8e90b11443a5.jpg)

**Comment by chinh4thepro** [comment]
i did lol
