### ISSUE TITLE
Is it possible to have both MCinaBox and Projav Launcher?

### ISSUE THREAD

**Issue by PeterScorPioN** [AOF-Dev/MCinaBox#692]
I just want to play some newer versions using Projav Launcher, because we all know that MCinaBox only supports 1.6.x - 1.12.2, but i also want to keep the MCinaBox because of it's perfect optimization, control customizing and great Forge compatibility. So the question is that can i have both of them, without having problems with datas and runtime packs? Will i have problems with their files, or anything else? If you can, please answer me. Thank you.

**Comment by AjGamingPHOfficial** [comment]
Dude
Mcinabox supports 1.6 upto 1.16 XD

**Comment by LegacyGamerHD** [comment]
@AjGamingPHOfficial yes on aarch32 remember aarch64 cant

**Comment by AyHa1810** [comment]
No, because Pojav patches the game to be playable, whereas MCinaBox completely runs the original jars on JRE without modifying it.

**Comment by CosineMath** [comment]
MCinabox supports latest snapshot.

**Comment by CosineMath** [comment]
It will be pretty good to add some features of PojavLauncher into Boat/MCinaBox, but we are too busy to update.

**Comment by CosineMath** [comment]
Of course, you can just install both of them in your phone. Their installations of Minecraft and runtime are separate. MCinaBox can also run Minecraft installed in PojavLauncher's directory.

**Comment by LegacyGamerHD** [comment]
> No, because Pojav patches the game to be playable, whereas MCinaBox completely runs the original jars on JRE without modifying it.

Well yes on v2 v3 does same thing as mc in the box

**Comment by PeterScorPioN** [comment]
> Dude
> Mcinabox supports 1.6 upto 1.16 XD

I know that, but you have to download a 32 bit runtime and play with everything at low, which i don't want honestly...

**Comment by PeterScorPioN** [comment]
> It will be pretty good to add some features of PojavLauncher into Boat/MCinaBox, but we are too busy to update.

I understand that. I don't judge you for not updating the game for a while. I just have no patience...😁
