### ISSUE TITLE
On 1.13.2 Crashes when on launch

### ISSUE THREAD

**Issue by chinh4thepro** [AOF-Dev/MCinaBox#695]
**Describe the crash**
I open up Minecraft 1.13.2 then after a few seconds after loading it crashes.

**To Reproduce**
Steps to reproduce the crash:
1. Go to home
2. Click on select version (with 1.13.2 selected)
3. Wait
4. See the crash

**Expected behavior**
It worked for 1.7.10
**Screenshots**
I don't have any screenshots, but I have a recording
https://youtu.be/BaA7K0wmZrg

**Smartphone (please complete the following information):**
 - Device: Lenovo C330 Chromebook
 - OS: Chromeos with android subsystem: Android 9 (32 bit)
 - App Version 0.1.4-p4-arm32

**Comment by CosineMath** [comment]
1.13.2 not supported.
