### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by ninjashooter194** [AOF-Dev/MCinaBox#696]
how much would mcinabox run on this cell phone: 6gb ram Snapdragon 710 octa core???

**Comment by PeterScorPioN** [comment]
Dude, this is a perfect phone to play minecraft java. For example, i have a phone with 6GB RAM, Snapdragon 845 and i play 1.8.9 and 1.12.2 (with a bunch of mods...) And i vet more that 100 fps.

**Comment by ninjashooter194** [comment]
Thanks, I'm only interested in playing 1.7.10 (Only that version) with mods. Pd: I use google translator so if you find inconsistencies you know why it is ...

**Comment by CosineMath** [comment]
It would run influently and fast. Enjoy your game!
