### ISSUE TITLE
Cannot connect to server using its domain name

### ISSUE THREAD

**Issue by xszqxszq** [AOF-Dev/MCinaBox#699]
**Describe the bug**
It seems that MCinaBox cannot connect to a server using its domain name. Since some servers using DDNS or etc do not support direct IP connection(especially in China), solutions mentioned in other issues WON'T WORK.

**To Reproduce**
1. Launch the game.
2. Choose the multiplayer mode.
3. Add any server using its domain name rather than its IP.
4. Click connect to the server and wait to see the "io.netty.channel.ConnectTimeoutException: connection timed out" error.

**Expected behavior**
Server's motd message being displayed in the servers list and normal connection to the server.

**Screenshots**
![Screenshot_20201123_211659_com aof mcinabox](https://user-images.githubusercontent.com/18241776/99969920-172cdf00-2dd6-11eb-9879-4c3e15d6b1ed.jpg)
![Screenshot_20201123_211735_com aof mcinabox](https://user-images.githubusercontent.com/18241776/99969943-1dbb5680-2dd6-11eb-8b88-590666db4937.jpg)

**Smartphone (please complete the following information):**
 - Device: tested on Huawei Mate 30 and Huawei Nova youth
 - OS: Android 10
 - App Version: v0.1.3, v0.1.4-p4(arm32, because arm64 version will crash on my device if it starts)
 - Game Version: 1.16.1, 1.16.4

**Additional context**
I've tried connecting to servers in Java Edition on my Windows laptop and it succeeded, thus the problem is not related to the server. Besides, my target server has dynamic ips, as the ping result changes every time, so plz stop answering direct IP solutions.

**Comment by xszqxszq** [comment]
Now confirmed that this problem is related to SRV resolve problem. Hope this can be fixed.

**Comment by xszqxszq** [comment]
(English Version) Temporary solution for everyone who cannot connect server using its domain:
1. Use SRV query tools(like [this one](https://mxtoolbox.com/SRVLookup.aspx)) to query the SRV record. If your server's domain is `yourserverdomain.com`, then query **THIS DOMAIN INSTEAD**: `_minecraft._tcp.yourserverdomain.com`
**Please notice that `_minecraft._tcp.` prefix is supposed to keep before your server's domain.** And do not try commands like nslookup since you are CURRENTLY USING A PHONE NOT A DESKTOP OR LAPTOP.
2. You can find your server's real domain and real port from the result of previous step, then fill it in Minecraft. Now you can connect to the server.

（Chinese）中文版说明：以下为无法连接服务器的临时解决方案：
1. 先用在线SRV查询工具（例如[这个](https://mxtoolbox.com/SRVLookup.aspx)）查询你要连接的服务器的SRV记录。例如你服务器的域名是`yourserverdomain.com`，那么**应当查询的域名应该是：**`_minecraft._tcp.yourserverdomain.com`
注意`_minecraft._tcp.`前缀一定要加在你服务器域名前面，不然查询不到正确的结果。另外请勿使用百度到的用nslookup之类的指令来查询，**因为你现在用的是手机而不是电脑。**
2. 经过上一步操作你将能在网页中看到你服务器的真实域名和真实端口（如果用的是上面的工具，那么结果倒数第一行和第二行分别是域名和端口），接着把这个域名和端口填进Minecraft里就能连接服务器了。

**Comment by TSaltedfishKing** [comment]
666
