### ISSUE TITLE
I'm completely lost with this runtime step.

### ISSUE THREAD

**Issue by mbootys** [AOF-Dev/MCinaBox#703]
I'm trying to install the runtime but when I go to android > com.aof.mcinabox > files >Mcinabox. There is no install runtime folder, is there a different place I need to download from?

**Comment by Slepicak1** [comment]
Hello mbootys, if you have installed newest version of Mcinabox you now must install runtime in the Launcher in general settings.

**Comment by CosineMath** [comment]
Yes, use latest version and follow new guide.
