### ISSUE TITLE
1.13 and 1.14 still don't work at 0.1.4p4, in the next update to Mcinabox I wanted Mcinabox to support Optifine from 1.15.2+, it sucks to have Optifine from 1.12.2 down!

### ISSUE THREAD

**Issue by OwzygZawg** [AOF-Dev/MCinaBox#704]
1.13 and 1.14 still don't work at 0.1.4p4, in the next update to Mcinabox I wanted Mcinabox to support Optifine from 1.15.2+, it sucks to have Optifine from 1.12.2 down!

**Comment by PeterScorPioN** [comment]
Dude sorry, but it's easy to say that you want them to add all the versions and all the optifines, but do you know how to do that at your own? STOP DOING THIS. EVERYONE. YOU JUST ALWAYS SAY THAT, LIKE IT IS VERY EASY TO DO. THIS NEEDS A LOT OF WORK AND PROGRAMMING KNOWLEDGE. THIS IS NOT LIKE PLAYING MINECRAFT. IF YOU REALLY WANT TO PLAY THESE VERSIONS, GO GET A PC, OR GO HELP THEM. Sorry again, but i talk to everyone, who says this.

**Comment by OwzygZawg** [comment]
> Cara, desculpe, mas é fácil dizer que você quer que eles adicionem todas as versões e todos os optifines, mas você sabe como fazer isso sozinho? PARE DE FAZER ISSO. TODOS. VOCÊ SEMPRE DIZ ISSO, COMO QUE É MUITO FÁCIL DE FAZER. ISTO PRECISA DE MUITOS CONHECIMENTOS DE TRABALHO E PROGRAMAÇÃO. ISTO NÃO É COMO JOGAR MINECRAFT. SE VOCÊ REALMENTE QUER JOGAR ESTAS VERSÕES, PEGUE UM PC OU VÁ AJUDÁ-LAS. Desculpe novamente, mas eu falo com todos que dizem isso.

I've already copied all the Optifine 1.16.3 folders, but it still doesn't work! not the need to be mad at me! more in the next update Mcinabox should support more versions of Optifine

**Comment by OwzygZawg** [comment]
> Cara, desculpe, mas é fácil dizer que você quer que eles adicionem todas as versões e todos os optifines, mas você sabe como fazer isso sozinho? PARE DE FAZER ISSO. TODOS. VOCÊ SEMPRE DIZ ISSO, COMO QUE É MUITO FÁCIL DE FAZER. ISTO PRECISA DE MUITOS CONHECIMENTOS DE TRABALHO E PROGRAMAÇÃO. ISTO NÃO É COMO JOGAR MINECRAFT. SE VOCÊ REALMENTE QUER JOGAR ESTAS VERSÕES, PEGUE UM PC OU VÁ AJUDÁ-LAS. Desculpe novamente, mas eu falo com todos que dizem isso.
It's all right! you may even be mad at me! but I do not accept your apologies for what I read what you wrote!

**Comment by OwzygZawg** [comment]
It's all right! you may even be mad at me! but I do not accept your apologies for what I read what you wrote!

**Comment by PeterScorPioN** [comment]
I will say this again. I am not MAD, an especially on you. I just don't understand everyone's mind. Please, do not take my words seriously. Anyway, we just need to wait.

**Comment by OwzygZawg** [comment]
> Eu direi isso novamente. Eu não sou MAD, e especialmente em você. Eu simplesmente não entendo a mente de todos. Por favor, não leve minhas palavras a sério. De qualquer forma, só precisamos esperar.

You left me disappointed! :( do you want me to take it as a joke? i'm not one of those who takes it all in joke!

**Comment by InAntonio101** [comment]
Okay Okay Let's Stop here. Apparently, Making an Android Application That Makes Minecraft Java Edition Playable On Mobile is a lot of days work and with less number of people to contribute to the project makes it even harder to Accomplish The things that we need. That's GitHub was Chosen for this project so that we can get more number of people from all over the world to help in coding. It's Just, It's taking time to come here and help and mainly people who use this application but don't know to code only demand the Developer to do this and that. I don't know too how to code the application but I am trying my best as a bug tracker to track as many bugs for the them to make their life easier in finding. However, The decision resides with them if they think it's minor or it will take more time to complete. So please have patience. Thank you.

**Comment by OwzygZawg** [comment]
> Ok Ok, vamos parar aqui. Aparentemente, fazer um aplicativo Android que torne o Minecraft Java Edition executável no celular exige muitos dias de trabalho e com menos número de pessoas para contribuir com o projeto torna ainda mais difícil realizar o que precisamos. O GitHub foi escolhido para este projeto para que possamos ter mais pessoas de todo o mundo para ajudar na codificação. É justo, está demorando para vir aqui ajudar e principalmente as pessoas que usam este aplicativo, mas não sabem codificar, apenas exigem que o desenvolvedor faça isso e aquilo. Eu também não sei como codificar o aplicativo, mas estou tentando o meu melhor como rastreador de bugs para rastrear tantos bugs para eles para tornar sua vida mais fácil de encontrar. No entanto, a decisão é deles se eles acharem que é menor ou se levará mais tempo para ser concluída. Portanto, tenha paciência. Obrigado.

Okay, I'll be patient! but will the new version of mcinabox support all versions of Optifine 1.15.2+? or will it still take many days of work for this? I also don't know how to code the game

**Comment by OwzygZawg** [comment]
> Ok Ok, vamos parar aqui. Aparentemente, fazer um aplicativo Android que torne o Minecraft Java Edition executável no celular exige muitos dias de trabalho e com menos número de pessoas para contribuir com o projeto torna ainda mais difícil realizar o que precisamos. O GitHub foi escolhido para este projeto para que possamos ter mais pessoas de todo o mundo para ajudar na codificação. É justo, está demorando para vir aqui ajudar e principalmente as pessoas que usam este aplicativo, mas não sabem codificar, apenas exigem que o desenvolvedor faça isso e aquilo. Eu também não sei como codificar o aplicativo, mas estou tentando o meu melhor como rastreador de bugs para rastrear tantos bugs para eles para tornar sua vida mais fácil de encontrar. No entanto, a decisão é deles se eles acharem que é menor ou se levará mais tempo para ser concluída. Portanto, tenha paciência. Obrigado.

Yes! let's say this takes a long time to do! and it also takes several days for them to release a version supporting all forge and Optifine versions! but the developers are working on it if I'm not mistaken this takes days I know! plus the only launcher that can support forge and Optifine with multiple versions is Pojav it supports Optifine Da 1.16 below and also supports Fabric Mod da 1.16 below too! but I hope that Mcinabox is better as well as Pojav,

**Comment by OwzygZawg** [comment]
I will end the problem when a future version of Mcinabox is released with various support for versions of Optifine and also forge! and Fabric mod plus Optifabric too

**Comment by InAntonio101** [comment]
You will? Then please Fix It, That's what we want. 🙂

**Comment by OwzygZawg** [comment]
However, Pojav is ahead! he now supports 1.13+ with jre2, jre8 and jre86x, jre86 and jre9 but at the moment mcinabox does not support from 1.13 to 1.14; )

**Comment by OwzygZawg** [comment]
> Você irá? Por que não fazer agora nesta versão? Por favor, conserte, isso é o que queremos.🙂

I am not one of the developers of Mcinabox or Pojav either, however when the developer releases a future version with these features that I talked about I will end the problem

**Comment by InAntonio101** [comment]
So why you are here? If you have problems from this application, Then go to That application. Why are you irritating Developers for that? They have their own lives too, Let them take their time.

**Comment by OwzygZawg** [comment]
> Então, por que você está aqui? Se você tiver problemas com este aplicativo, vá para Esse aplicativo. Por que vocês irritam os desenvolvedores por causa disso? Eles têm suas próprias vidas também, Deixe-os levar o seu tempo.
And then why are you here too? I commented on the problem because I don't think anyone knew!

**Comment by OwzygZawg** [comment]
And then why are you here too? I commented on the problem because I don't think anyone knew!

**Comment by OwzygZawg** [comment]
??

**Comment by InAntonio101** [comment]
> > Você irá? Por que não fazer agora nesta versão? Por favor, conserte, isso é o que queremos.🙂
> 
> I am not one of the developers of Mcinabox or Pojav either, however when the developer releases a future version with these features that I talked about I will end the problem
I am not the expert 
Bro, Then why GitHub Exists, You can Code the app. You have all the resources of the version in the files menu I believe. I am not an expert, But I am pretty sure you can get the codes and stuff and upload it in Android Studio.

**Comment by OwzygZawg** [comment]
> Você irá? Por que não fazer agora nesta versão? Por favor, conserte, isso é o que queremos.🙂

if I shouldn't be here! you shouldn't be either!

**Comment by InAntonio101** [comment]
> And then why are you here too? I commented on the problem because I don't think anyone knew!

Of course we know, 1.13+ have Rendering Issues. I am here just to tell that people who are working in this project have their own life, They aren't earning any money out of this and They need money To live, so they are working on thier jobs. Keeping themselves entertained to make sure their Mental Health is Okay and are not in stress. Some Have families to take care about. If you have time to contribute to this community then do that, But have patience too and If you have time to mention other Applications that do that, Then we don't want that here, Just leave and contribute to that community, let Us (the others) contribute to this community. If you are there any Developers, I guess we can close this thread as we have moved to off-topic and we don't want more drama here.

**Comment by OwzygZawg** [comment]
Nobody here is doing drama! I do have time to contribute to this community or something!

**Comment by renerosal021** [comment]
FIGHT FIGHT FIGHT FIGHT FIGHT!!!!!

**Comment by OwzygZawg** [comment]
> LUTA LUTA LUTA LUTA LUTA !!!!!

If he wants to fight! there will be a fight 🙄

**Comment by OwzygZawg** [comment]
> > E então por que você está aqui também? Comentei sobre o problema porque acho que ninguém sabia!
> 
> Claro que sabemos, 1.13+ tem problemas de renderização. Estou aqui apenas para dizer que as pessoas que estão trabalhando neste projeto têm sua própria vida, elas não estão ganhando dinheiro com isso e precisam de dinheiro para viver, então estão trabalhando em seus empregos. Manter-se entretido para ter certeza de que sua saúde mental está OK e não está sob estresse. Alguns têm famílias para cuidar. Se você tem tempo para contribuir com esta comunidade, faça isso, mas tenha paciência também e se você tiver tempo para mencionar outros aplicativos que fazem isso, então não queremos isso aqui, basta sair e contribuir com essa comunidade, deixe-nos ( os outros) contribuem para esta comunidade. Se houver algum desenvolvedor, acho que podemos fechar este tópico, pois mudamos para fora do tópico e não queremos mais drama aqui.

In fact! it's not just creators and contributors who need money to live! all of us of course! if you think i don't have time for anything, know that i'm available anytime! if you say how and why I came here! why did you end up here too?

**Comment by khanhduytran0** [comment]
Well, `inheritsFrom` behavior was not implemented. Modded clients will not work

**Comment by CosineMath** [comment]
It is good. But this project is currently not active as there are no enough active developers.

**Comment by artdeell** [comment]
In pojav there are 3, and, most of the time, 1 active developers, and we
somehow still keep up. Management issues?

вс, 29 нояб. 2020 г., 12:02 CosineMath <notifications@github.com>:

**Comment by OwzygZawg** [comment]
I did not understand

**Comment by CosineMath** [comment]
> In pojav there are 3, and, most of the time, 1 active developers, and we somehow still keep up. Management issues?

Sorry to tell you that currently there is 0 active developers.

**Comment by OwzygZawg** [comment]
🧐

**Comment by artdeell** [comment]
> > In pojav there are 3, and, most of the time, 1 active developers, and we somehow still keep up. Management issues?
> 
> Sorry to tell you that currently there are 0 active developers.

Understandable, have a great day
