### ISSUE TITLE
Pls read if you want to play 1.16.x

### ISSUE THREAD

**Issue by davidii12nu** [AOF-Dev/MCinaBox#705]
The versions 1.16 and above (dont know how it is for 1.13-1.15)
are only working on the 32aarch versions not 64aarch.
Even if your phone is 64bit.
I'm using a Oneplus 6 and it is still working properly.
But forge isn't going to work.

**Comment by OwzygZawg** [comment]
I have 32 bits and runs very well at 1.16. This problem is not necessary or are you just saying who uses aarch 64? i use aarch 32

**Comment by davidii12nu** [comment]
When you want to play 1.16 you need to install the aarch 32 version. Just wanted to say it to the people who wanted to play 1.16 but used 64.

**Comment by OwzygZawg** [comment]
Understand! it is very simple to use 1.16 only for those who know like me!

**Comment by OwzygZawg** [comment]
I just made a problem if you could see it! appreciate!

**Comment by davidii12nu** [comment]
There didnt stand anything about that what i writed 30 min ago

**Comment by PeterScorPioN** [comment]
So, what graphics do you guys play with? I guess you have everything at low, cause of the 32 bits, right?

**Comment by davidii12nu** [comment]
Still works good with 12 chuncks.

**Comment by PeterScorPioN** [comment]
Wow!

**Comment by SnowNF** [comment]
The versions 1.16 and above are working on the aarch64 (p5)
