### ISSUE TITLE
Evgeni

### ISSUE THREAD

**Issue by evgeniikrasnyi** [AOF-Dev/MCinaBox#707]
@**Describe the crash**
A clear and concise description of what the bug is. При запуске игры приложение вылетает.

**To Reproduce**
Steps to reproduce the crash:
4. See the crash

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 6
 - OS: [e.g. Android 9.0]
 - App Version 

**Additional context**

**Comment by PeterScorPioN** [comment]
Ты делал всё как надо было?

**Comment by evgeniikrasnyi** [comment]
Вроде да.

пт, 27 нояб. 2020 г., 15:43 PeterScorPioN <notifications@github.com>:

**Comment by evgeniikrasnyi** [comment]
Он вылетает при запуске игры.

пт, 27 нояб. 2020 г., 15:43 PeterScorPioN <notifications@github.com>:
