### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by elyesishere** [AOF-Dev/MCinaBox#708]
after i installed 64 runtime on 64 mcinabox-p4 (my phone has 64bit support) it said missing file (idk what is that missing file it is just like 0a00abdoorvdos00hrdideh)

**Expected behavior**

**Screenshots**
![Screenshot_20201127-072206](https://user-images.githubusercontent.com/72686414/100417690-c4774f80-3081-11eb-98e4-53769f9e888c.png)

**Smartphone (please complete the following information):**
 - Device: [infinix HOT 8]
 - OS: [Android 9]
 - App Version [v0.1.4-p4]

**Comment by CosineMath** [comment]
It is the language and music file of Minecraft. Try reinstalling Minecraft. (By the way, you can launch without those files.)
