### ISSUE TITLE
这可能是一个问题

### ISSUE THREAD

**Issue by FurryRbl** [AOF-Dev/MCinaBox#709]
forge的mod无法读取本地储存的文件  
optifine无法读取本地光影  
无法在Minecraft内输入文字,例如多人游戏内输入服务器ip等等  
我并没有测试Minecraft是否可以读取本地材质

**Comment by CosineMath** [comment]
建议你具体描述一下情况以便我们复现无法读取文件的错误。

**Comment by EndVampireThunderFlash** [comment]
![Screenshot_20201130_071230](https://user-images.githubusercontent.com/61524717/100556193-78274c00-32db-11eb-83d5-e62fdef7e827.jpg)  
光影文件夹里面已经存在光影,但是在游戏中却没有光影  
游戏只有一个'关闭'和'(内置)'
