### ISSUE TITLE
Runtime Not Importing in Version 0.1.3. 

### ISSUE THREAD

**Issue by InAntonio101** [AOF-Dev/MCinaBox#710]
Description of Bug:-
When Runtime Is imported, The Message is sent by the application that the Runtime has been successfully imported. However, when we open Management Tab, It says that the Runtime hasn't been imported. 

Steps to reproduce the behavior:-
1. Go to launcher settings and select the Recommended Runtime File For 0.1.3 (Which is aarch32_runtime_20200328.tar.xz)
2. Click Import and a message 'Runtime Pack Is getting imported.' Wait for a minute or 2 and a new message will pop-up saying, 'Runtime Pack Has Been Installed.'
3. Now, Open The Management Tab. 
4. When The Management Tab is Opened, An error message is seen which says that 'Please Put The Runtime pack...' and we are unable to go further in the steps to Play Minecraft.

Expected behavior:-
We were supposed To see the Management Tab with all of its Specifications, For Example, 'Select Custom Keyboard.'

Media:-
Click This Link to see a Video in which I do the above Steps and Get the error Message.
 https://drive.google.com/file/d/1FefpVDr_AJ8GSjdZ3Z6X-ZzHq2Q-mw2F/view?usp=drivesdk

Device Specifications:-
 - Nokia 7.2 
 - Android 10
Version Used:- v0.1.3
Runtime Used:- aarch32_runtime_20200328.tar.xz

**Comment by OwzygZawg** [comment]
Mcinabox does not support Android 10 only from 9.0 down! or if the problem continues, install the latest version of Mcinabox! Hope this helps : )

**Comment by InAntonio101** [comment]
Oh Oof, Didn't Knew that. Thanks!

**Comment by OwzygZawg** [comment]
😉

**Comment by OwzygZawg** [comment]
It worked?

**Comment by CosineMath** [comment]
> Mcinabox does not support Android 10 only from 9.0 down! or if the problem continues, install the latest version of Mcinabox! Hope this helps : )

MCinaBox supports Android 10.

**Comment by CosineMath** [comment]
0.1.3 is out-of-date, some bugs might not fixed.
