### ISSUE TITLE
Mcinabox does not support 20w22a 1.16 snapshot when you enter this snapshot the mcinabox comes out

### ISSUE THREAD

**Issue by OwzygZawg** [AOF-Dev/MCinaBox#712]
Mcinabox does not support 20w22a 1.16 snapshot when you enter this snapshot the mcinabox comes out

**Comment by CosineMath** [comment]
Try 20w48a. Make sure that you use 32bit version and note that max memory size should not be too high.

**Comment by OwzygZawg** [comment]
I want to play is in the 1.16 snapshot the 20w22a more when starting this version the game comes out! I know that 32 bits cannot allocate higher memory! I already play 20w48a on mcinabox

**Comment by OwzygZawg** [comment]
I don't play the 20w48a version much because only the dripstone was added

**Comment by OwzygZawg** [comment]
1.17 snapshots crash in the flat world except in the standard world on my phone!
