### ISSUE TITLE
Redmi note 8 pro

### ISSUE THREAD

**Issue by Mineplayer123** [AOF-Dev/MCinaBox#714]
Does minecraft java 1.8 run me at a stable 60 fps on a redmi note 8 pro (6 ram) Without optifine and with minecraft default settings?

**Comment by Denkon325** [comment]
![Screenshot_2020-11-30-22-46-42-912_com aof mcinabox](https://user-images.githubusercontent.com/75277991/100663098-79e62380-335e-11eb-8bb1-f0415241ab57.jpg)

**Comment by Mineplayer123** [comment]
Is it a redmi note 8 pro? safe??

**Comment by Mineplayer123** [comment]
Excuse my insistence, But ... I still have doubts about the performance on the redmi 8 note pro. Since I still don't have a cell phone and I would like you to make some things clear to me .. 1How much maximum ram can I assign to the mcinabox with the redmi note 8 pro? 2 it will be possible for minecraft 1.8 to run at 60fps Very stable, at least I want it to go down to 50fps but no more from there. And finally I want to make it clear that IF I can be able to lower the graphic quality of minecraft 1.8 in case the performance is deficient .. But the only thing that if I do not go down is the chunks, I want at least the chunks to be 8. So would the mcinabox run fine on the redmi note 8 pro? These questions are more for someone who owns a redmi note 8 pro. So if someone with a 6gb ram redmi note 8 pro sees this PLEASE do a test of the mcinabox 1.8 for me (Without optifine) And I know that this is a lot to ask but ... I want you to be very accurate with the performance data, since I don't want to buy a cell phone that at least doesn't run minecraft 1.8 at 60 fps stable ... That's it ... Ufff PS: There is no forum for this but in Spanish? I don't know English and I realize that there are more people who speak Spanish than they think, END.
