### ISSUE TITLE
AArch64

### ISSUE THREAD

**Issue by matt995** [AOF-Dev/MCinaBox#716]
1.16.4 wont launch on arrch64 platform.

When will you give support for arrch64 platform as arrch32 is kind of very laggy for me

Phome : huawei p30lite
Kirin 710
4gb ram 128gb internal storage @

**Comment by matt995** [comment]
I know that this is already bug but just asking when will it be fixed

**Comment by CosineMath** [comment]
I am working on Boat to fix this bug. There is a good news that dlopen failure of `libglfw.so` is fixed. But `glCheckFramebufferStatus` now fails to work. Need more research on this. I don't know when this will be fixed. 

(It is aarch64 rather than arrch64)

**Comment by matt995** [comment]
Thx

**Comment by khanhduytran0** [comment]
> But glCheckFramebufferStatus now fails to work.

Well, it's same problem on our one before. I managed to fix it, but it still happens sometimes.

**Comment by CosineMath** [comment]
> Well, it's same problem on our one before. I managed to fix it, but it still happens sometimes.

So what is your final solution? Could you tell me please?

**Comment by khanhduytran0** [comment]
> > Well, it's same problem on our one before. I managed to fix it, but it still happens sometimes.
> 
> So what is your final solution? Could you tell me please?

I added another [`glfwMakeCurrent()` on `org.lwjgl.opengl.GL.createCapabilities()`](https://github.com/PojavLauncherTeam/lwjgl3-glfw-java/blob/26ec22dd74e7eef95860b1f893a56a837ff149b9/src/main/java/org/lwjgl/opengl/GL.java#L349) method.

**Comment by CosineMath** [comment]
> I added another `glfwMakeContextCurrent()` on `org.lwjgl.opengl.GL.createCapabilities(boolean forwardCompatible)` method.

Thank you for your help :) . I will try this solution some time.

**Comment by CosineMath** [comment]
This problem has been fixed on my device. Please waited for update.
