### ISSUE TITLE
Forge 1.16.4

### ISSUE THREAD

**Issue by Androser420** [AOF-Dev/MCinaBox#730]
Hey I just wanted to ask, how do i install forge 1.16.4?
I tried but an error occurred, please help me lol.
btw im using 32bit app v0.1.4-p4
![Screenshot_20201209-181537_MCinaBox](https://user-images.githubusercontent.com/72580260/101663100-906d3880-3a4a-11eb-913b-d9cfb20fa32e.png)

**Comment by OwzygZawg** [comment]
Mcinabox does not support forge for 1.16 and does not support optifine 1.16

**Comment by Androser420** [comment]
> Mcinabox does not support forge for 1.16 and does not support optifine 1.16

damnit

**Comment by OwzygZawg** [comment]
: (

**Comment by SavagePy10** [comment]
> > Mcinabox does not support forge for 1.16 and does not support optifine 1.16
> 
> damnit

@Androser420 Pojav do support optifine 1.16 but not forge...

**Comment by SavagePy10** [comment]
> > Mcinabox does not support forge for 1.16 and does not support optifine 1.16
> 
> damnit

The fact that mcinabox is not compatible with 1.16 optifine is discovered by @KUALAM.

**Comment by OwzygZawg** [comment]
> > > Mcinabox não suporta forge para 1.16 e não suporta optifine 1.16
> > 
> > 
> > droga
> 
> @ Androser420 Pojav suporta optifine 1.16 mas não forja ...

Yes

**Comment by OwzygZawg** [comment]
> > > Mcinabox não suporta forge para 1.16 e não suporta optifine 1.16
> > 
> > 
> > droga
> 
> O fato de mcinabox não ser compatível com 1,16 optifine foi descoberto por Muhd

What?

**Comment by SavagePy10** [comment]
> > > > Mcinabox não suporta forge para 1.16 e não suporta optifine 1.16
> > > 
> > > 
> > > droga
> > 
> > 
> > O fato de mcinabox não ser compatível com 1,16 optifine foi descoberto por Muhd
> 
> What?

Oh ... Using an trans. Its not perfect.

**Comment by CosineMath** [comment]
Forge for 1.13+ is not supported.

**Comment by OwzygZawg** [comment]
Yes

**Comment by XxMATRIXXxX** [comment]
Does anyone know how to get pojav launcher 1.16.4 with optifine
