### ISSUE TITLE
[Feature Request] make the runtime auto install

### ISSUE THREAD

**Issue by LegacyGamerHD** [AOF-Dev/MCinaBox#732]
this solves most of people complaining

**Comment by SavagePy10** [comment]
Self assign yourself

**Comment by CosineMath** [comment]
We might release apk packages bundled with runtime pack.

**Comment by pojavluncher2021** [comment]
Pojav has that, It auto installs a runtime from it's servers, 64bit and 32bit are supported in Pojav when the servers find a runtime matching your bit tech
