### ISSUE TITLE
Left Top InputBox and chat crashes

### ISSUE THREAD

**Issue by noobimpostor** [AOF-Dev/MCinaBox#735]
**crash description**
when i click input box or try open chat, app crashes

**Expected behavior**
A keyboard should open on clicking input box and chat option but it not

**Screenshot urls**
![Screenshot_2020-12-11-15-30-36-501_com aof mcinabox](https://user-images.githubusercontent.com/65805762/101890148-55900f80-3bc6-11eb-87a2-acd8f32f70db.jpg)
![Screenshot_2020-12-11-15-09-48-728_com miui bugreport](https://user-images.githubusercontent.com/65805762/101890178-5e80e100-3bc6-11eb-9627-aa3e8975fc15.jpg)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 8
 - OS: android 9
 - App Version : latest preview p4

**Comment by kaiwalyar** [comment]
@longjunyu2 please release urgent fix on this

**Comment by LegacyGamerHD** [comment]
duplicated of #555
