### ISSUE TITLE
would mcinabox work on the smartphone Letv Leeco Le 2 X526

### ISSUE THREAD

**Issue by iranfull** [AOF-Dev/MCinaBox#739]
Letv Leeco Le 2 X526 Smartphone 3 Gb 64g Snapdragon 652.
this and my phone it is an Android version 6.0 so it being old so could you play mcinabox?

**Comment by SavagePy10** [comment]
> Letv Leeco Le 2 X526 Smartphone 3 Gb 64g Snapdragon 652.
> this and my phone it is an Android version 6.0 so it being old so could you play mcinabox?

Good enough

**Comment by iranfull** [comment]
@SavagePy10 is it possible to play Minecraft version 1.16?

**Comment by longjunyu2** [comment]
yes
