### ISSUE TITLE
Cant login with Premium Account 

### ISSUE THREAD

**Issue by ReinerPing** [AOF-Dev/MCinaBox#746]
Hello,
I have a problem with the login of my mojang Account. I am using the Version 1.0.4 and every time i wanna try to login there is the error message of a wrong Email or password. This cant be the Problem because i already Checked my Account Informations. I also dont know if i have to type somethink in the Server part.

Thank you :D

**Comment by Alekuso** [comment]
Put your email address instead of your password
it works fine for me

**Comment by alchemist6969** [comment]
And password in the place of email address?? Please reply

**Comment by Alekuso** [comment]
Sorry I meant username

**Comment by pojavluncher2021** [comment]
java.lang.PremiumTokenGenerationFailedException:Premium account token
failed to generate
