### ISSUE TITLE
返回按钮无法被隐藏

### ISSUE THREAD

**Issue by ChenDoXiu** [AOF-Dev/MCinaBox#747]
**Describe the bug**
对于某些带有虚拟按钮的手机来说，在运行游戏时，虚拟按键不会被隐藏

如下图
![17d9de1798f19fe1](https://user-images.githubusercontent.com/46947912/102499567-4fae9880-40b6-11eb-98a0-f03a7c6cc0e4.jpg)

这会影响到正常的游玩，有时会误触导致游戏被退出
**Expected behavior**
当进入游戏之后，虚拟按键应该被隐藏
**Smartphone (please complete the following information):**
 - Device: SONY XZ1
 - OS: Android 9
 - App Version v0.1.4-p4 arm64

**Comment by longjunyu2** [comment]
我测试了几台设备，暂时没能复原这个bug，可能是个别系统的问题。
推荐在系统设置里禁用虚拟按键。

**Comment by ChenDoXiu** [comment]
此问题在p5版本已经被修复了
