### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by ChargedHat42838** [AOF-Dev/MCinaBox#748]
Can I play mcinabox 1.17 properly on poco M2 
Armv8 6 gb ram

**Comment by Luwaee** [comment]
1.17 probably isn't stable since there is alot to fix on MCinabox, so I wouldn't recommend it.

**Comment by artdeell** [comment]
duno about box but 1.17 definitely can work on android relatively good

another launcher

чт, 17 дек. 2020 г., 17:59 ChargedHat42838 <notifications@github.com>:
