### ISSUE TITLE
Cannot connect to servers

### ISSUE THREAD

**Issue by NeverLandYT** [AOF-Dev/MCinaBox#756]
**Describe the bug**
I can't join any servers. 

**To Reproduce**
1. Go to Multiplayers
2. Click on Direct Connect
3. Attempt to join a server

**Expected behavior**
Connect to the server

**Screenshots**
I cannot put in the video, but I'm putting in a YouTube Link 
https://youtu.be/_GpHi_7Laa0 

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - OS: [e.g. Android 8.1]
 - App Version 0.1.4-p4

**Comment by noobimpostor** [comment]
Try connecting play.legendsmc.net

**Comment by NeverLandYT** [comment]
Wait it works, what?

A terça, 22 de dez de 2020, 11:41, noobimpostor <notifications@github.com>
escreveu:

**Comment by SoupSoomer** [comment]
> Try connecting play.legendsmc.net

How do you register on the server it dosnet let me type the command

**Comment by noobimpostor** [comment]
> > Try connecting play.legendsmc.net
> 
> How do you register on the server it dosnet let me type the command

Run offline with unique name , and then u can register

**Comment by NeverLandYT** [comment]
Well, that means it can send packets, but not receive (did I get that right)

Enviado do meu iPhone

**Comment by SoupSoomer** [comment]
> Well, that means it can send packets, but not receive (did I get that right) Enviado do meu iPhone
> […](#)
> No dia 26/12/2020, às 00:29, SoupSoomer ***@***.***> escreveu: ﻿ Try connecting play.legendsmc.net How do you register on the server it dosnet let me type the command — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

No, you know how on thta server you have to type something /register and then a password? I don't know how to get to chat to do that

**Comment by NeverLandYT** [comment]
Ah, got it. Just press T in the computer keyboard

Enviado do meu iPhone

**Comment by GreenninjaGamingyt** [comment]
Same I also reported it

**Comment by wallxq** [comment]
P30 pro i have the same problem

**Comment by NeverLandYT** [comment]
6 months later, after testing around some stuff, it seems like the domains work when they are an A record. The hypixel.net for example is an SRV record and it doesn't work. mc.hypixel.net is an A record for the SRV record so it works. Seems like the issue is the SRV Records.
Glad I could help anyone who came arround this issue.
