### ISSUE TITLE
Mcinabox 1.7.10 me va muy mal

### ISSUE THREAD

**Issue by Mineplayer123** [AOF-Dev/MCinaBox#759]
Instale mcinabox en mi Android, Probé la 1.7.10 y me va muy lento como a 10-20 FPS y veo algunos bloques como bugeados NO he hecho ninguna modificación a las configuraciones del Minecraft los chunks son 8 los gráficos en detallado y todo lo demás predeterminada mente y me va muy lento, 
mi celular tiene 6gb de ram (Le asigne 4gb de ram al mcinabox) el cpu es un MediaTek helio g90t, Se que no es el mejor célular del mundo pero esperaba entre 30 y 60 FPS con al menos 8 chunks no así de mal... Ayuda :

**Comment by EtherealSJ** [comment]
Deduzco que tienes el Redmi Note 8 Pro, yo lo probé hace un tiempo creo que en esa misma versión y me iba aceptable mente fluido, alrededor de 20 o 25 fps, no se que causará lo que dices, intenta reinstalar todo. No recuerdo las configuraciones gráficas que tenía puestas, pero lo instalaré de nuevo y te comento, saludos :)

**Comment by Mineplayer123** [comment]
Ya lo reinstale y todo igual :( Ahora no sé si es mi celular qué es muy poco potente o que, He visto a usuarios que juegan a 2 chunks y les va como a 80 FPS con celulares de gama baja, pero pensé que el redmi note 8 pro al ser gama media y tener un buen cpu me correría a 60 FPS a 8 chunks, pero creo que no es así. pero mi problema verdadero es que a 2 chunks me va a 60 FPS y entre 40 y aveces baja hasta 20 y si en un celular de gama baja corre mejor que el mío que es un célular gama media entonces es qué algo malo le pasa a mi juego o a mí celular...El celular lo compre apenas hace 2 días y está 100% las únicas aplicaciónes que tengo son las del sistema, WhatsApp YouTube y mcinabox MAS NADA pero es que los FPS qué tengo no son nada estable..Instale optifine a ver si bajando la calidad gráfica a lo mínimo me funcionaría y solo me subió como 4 o 5 FPS...No sé si es mi celular qué vine defectuoso o es poco potente para el mcinabox o es alguna configuración..De verdad no sé qué es..He visto como mil videos en Youtube pero ninguno resuelve mi problema tasa.Ahora que terminé de escribir esto pienso que es mi celular..

**Comment by Mineplayer123** [comment]
Ósea apenas me compre el celular probé el mcinabox y pocas horas publiqué esto..Tsss

**Comment by Mineplayer123** [comment]
Pero con otros juegos si me corre bien todo..Pero creo que esto no es normal..No lo sé de verdad no lo sé..

**Comment by EtherealSJ** [comment]
También tengo el Redmi Note 8 Pro, instale el MCinabox (0.1.4-p4) con el último runtime (revisaste eso?) Probé descargando la versión 1.11.2 y me corre bastante fluido, a 8 chunks corre entre 40-60 fps aquí adjunto 2 imágenes ;) no se cual será tu problema, tal vez si es el teléfono, es oficial u homologado? ![Screenshot_2020-12-26-15-56-13-977_com.aof.mcinabox.jpg](https://user-images.githubusercontent.com/64757771/103157607-7f832d80-4793-11eb-97b5-60801be5653b.jpg)![Screenshot_2020-12-26-16-00-15-727_com.aof.mcinabox.jpg](https://user-images.githubusercontent.com/64757771/103157608-8447e180-4793-11eb-858e-f492e68c2ac7.jpg)

**Comment by Mineplayer123** [comment]
Oficial...

**Comment by Mineplayer123** [comment]
Estoy un 50% seguro de que es el celular.. Igualmente seguiré haciendo pruebas de rendimiento con otros juegos testeando aplicaciones básicas del célular y ese tipo de cosas..Si veo que actúa de una forma que no debe ser entonces uso la garantía del centro comercial en el que lo compré...(el runtime lo revise todo está correcto TODO) Que mala suerte tengo pfff...

**Comment by EtherealSJ** [comment]
Humm, :( bueno, espero que te salga todo bien, que mal y que extraño lo que te ocurre :/ suerte!

**Comment by Mineplayer123** [comment]
EtherealSJ Disculpa por molestar tanto pero.. Podrías probar la versión 1.7.10 con las configuraciones normales del Minecraft?(Las que viene de inició) solo para estar más seguro?? Se que si te corrió en esa versión bien entonces en la 1.7.10 debería irte mejor pero es que estoy pensando en usar la garantía y es un poco delicado para mí..(Además tengo 15 años y este es la primera cosa que compró con dinero que yo gané haciendo trabajos rápidos en mi vida..Y me pone un poco triste porqué me esforze por conseguirlo.. Además Me gustaría saber el rendimiento aproximado en la 1.7.10 ya que antes de comprar el celular tenía dudas de este..Y muchas gracias...

**Comment by Mineplayer123** [comment]
EtherealSJ Disculpa por molestar tanto pero.. Podrías probar la versión 1.7.10 con las configuraciones normales del Minecraft?(Las que viene de inició) solo para estar más seguro?? Se que si te corrió en esa versión bien entonces en la 1.7.10 debería irte mejor pero es que estoy pensando en usar la garantía y es un poco delicado para mí..(Además tengo 15 años y este es la primera cosa que compró con dinero que yo gané haciendo trabajos rápidos en mi vida..Y me pone un poco triste porqué me esforze por conseguirlo.. Además Me gustaría saber el rendimiento aproximado en la 1.7.10 ya que antes de comprar el celular tenía dudas de este..Y muchas gracias...

**Comment by Mineplayer123** [comment]
Este mes ha sido extrañó para mí la verdad ..

**Comment by EtherealSJ** [comment]
> EtherealSJ Disculpa por molestar tanto pero.. Podrías probar la versión 1.7.10 con las configuraciones normales del Minecraft?(Las que viene de inició) solo para estar más seguro?? Se que si te corrió en esa versión bien entonces en la 1.7.10 debería irte mejor pero es que estoy pensando en usar la garantía y es un poco delicado para mí..(Además tengo 15 años y este es la primera cosa que compró con dinero que yo gané haciendo trabajos rápidos en mi vida..Y me pone un poco triste porqué me esforze por conseguirlo.. Además Me gustaría saber el rendimiento aproximado en la 1.7.10 ya que antes de comprar el celular tenía dudas de este..Y muchas gracias...

Claro!, no es molestia jaja, ya la probé y me anda a 53 fps promedio, mira ![Screenshot_2020-12-26-17-06-49-656_com.aof.mcinabox.jpg](https://user-images.githubusercontent.com/64757771/103158475-02f54c80-479d-11eb-8769-48b9cd282a5f.jpg)![Screenshot_2020-12-26-17-07-02-786_com.aof.mcinabox.jpg](https://user-images.githubusercontent.com/64757771/103158476-07ba0080-479d-11eb-812c-1753897a9c60.jpg)

Quizás le asignaste mucha ram, yo le puse 2048 MB en eso de memory size algo así xd, pero me dijo la app que era mucho, entonces le puse que asignara automáticamente, antes de usar la garantía comprueba todo, a veces puede pasar que uno cree que es un gran problema y puede ser solo un detalle jaja, la otra vez con una prima teníamos un problema en su PC de que no le funcionaba la camara, se apagaba al iniciarla, entonces hicimos un gran jaleo para nada, resulta que había desactivado la camarita con el botón del teclado y no se había dado cuenta jajaja, y bueno... te adjuntaria mi carpeta de MCinabox, pero no sé cómo adjuntar archivos :( espero te sirvaa, y ánimo :D

**Comment by Mineplayer123** [comment]
Muchas gracias y si voy a seguir tu consejo...Jeje de verdad muchas gracias.
