### ISSUE TITLE
安装高版本黑屏

### ISSUE THREAD

**Issue by Visvaria** [AOF-Dev/MCinaBox#762]
**Describe the bug**
安装1.12.2正常，安装1.16.4启动后黑屏，只有虚拟键和指针。易闪退。
**To Reproduce**
安装1.16.4
点击启动
内存为自动调节，其他参数默认
**Expected behavior**
没有出现mojang加载进度条，全程黑屏，有指针与虚拟键
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy J6]
 - OS: [e.g. Android 8.1]
 - App Version [e.g. v0.1.3]
荣耀30
eui11/magic ui4.0
软件版本0.1.4p4
**Additional context**

**Comment by w123456w30w** [comment]
使用arm32运行环境

**Comment by longjunyu2** [comment]
0.1.4-p5解决了这个问题
