### ISSUE TITLE
Unable to launch 1.16.4 on both 32/64 bit runtimes

### ISSUE THREAD

**Issue by noobimpostor** [AOF-Dev/MCinaBox#767]
Latest build on action (8 days ago commited) launched,keyboard also works but doesn't launch 1.16.4 and some its previous versions . Tried both runtimes 32/64 plz solve this issue.

**Comment by CosineMath** [comment]
32bit runtime matches 32bit apk.
64bit runtime matches 64bit apk.

Try new updates.

**Comment by noobimpostor** [comment]
It worked @CosineMath , but do something for white sheeps and eggs(its boardwalk bug maybe)
