### ISSUE TITLE
Question on MCPE controlls

### ISSUE THREAD

**Issue by ThatGifIsNice** [AOF-Dev/MCinaBox#768]
How do i lock the sneak button while going backwards(if i want to play bedwars for example)
0.1.4-p4

**Comment by serpentspirale** [comment]
You can't without creating a custom key that holds it for you.

**Comment by ThatGifIsNice** [comment]
> You can't without creating a custom key that holds it for you

Wasnt there this feature in 0.1.3 why wasnt it taken over ?
