### ISSUE TITLE
Optifine 1.12.2_HD_U_F5!

### ISSUE THREAD

**Issue by AyHa1810** [AOF-Dev/MCinaBox#771]
Here: 
[OptiFine_1.12.2_HD_U_F5(Manual_install).zip](https://github.com/AOF-Dev/MCinaBox/files/5753142/OptiFine_1.12.2_HD_U_F5.Manual_install.zip)

You can now install Optifine without Forge!
Extract the files in the game folder, and it's done!

Haha this isn't a issue. I got 200+ fps on my phone wow!

**Comment by Adam0530** [comment]
WoW
