### ISSUE TITLE
I have some questions

### ISSUE THREAD

**Issue by Alan-sfs** [AOF-Dev/MCinaBox#774]
1. If i install the runtime will it change anything in my Android OS?
2. How can i stop some crashes?
3. Does the app work on a Mali GPU? my phone is the Redmi Note 8 PRO 64GB 6GB RAM

**Comment by Joseantonio193** [comment]
a lot of text xd

**Comment by Matryx0207w** [comment]
Hello, I wanted to ask why you do not have support for mause with android 8 to play with keyboard and mause in android so it would be more comfortably I hope you listen to my request :)

**Comment by Matryx0207w** [comment]
Hi, I wanted to ask you why you don't have mouse support with android 8 to play with keyboard and mouse on android to make it more comfortable I hope you hear my request :)

**Comment by AyHa1810** [comment]
1. Nope.
2. You can check some configurations and settings to prevent crashes. If it still crashes, it might be the bugs of the app which is causing this.
3. Yup, you can.

**Comment by AyHa1810** [comment]
> Hello, I wanted to ask why you do not have support for mause with android 8 to play with keyboard and mause in android so it would be more comfortably I hope you listen to my request :)

They didn't implement this feature yet. You can ask them to implement by opening a new issue about it. There might be another issue opened about it. Or, you can contribute to this project to add this feature.

**Comment by AyHa1810** [comment]
Also, Happy new year to all of you guys!

**Comment by Alan-sfs** [comment]
also yeah i forgot, one last question, does any game anti cheat detect mcinabox as a cheat?

**Comment by Alan-sfs** [comment]
ill close after i get the answer

**Comment by AyHa1810** [comment]
> also yeah i forgot, one last question, does any game anti cheat detect mcinabox as a cheat?

Maybe no, since its just a launcher. You can try though.

**Comment by Alan-sfs** [comment]
ok
