### ISSUE TITLE
"Runtime does not exist"

### ISSUE THREAD

**Issue by LucaForever** [AOF-Dev/MCinaBox#780]
I followed all the instructions, and still, the app could not find the runtime.

![Screenshot_20210101_145432_com huawei hidisk](https://user-images.githubusercontent.com/58527636/103438965-5eae5280-4c41-11eb-8b43-a83c84a4baab.jpg)

![Screenshot_20210101_145442_com aof mcinabox](https://user-images.githubusercontent.com/58527636/103438968-666df700-4c41-11eb-8316-2f97a8baec74.jpg)

![Screenshot_20210101_145502_com aof mcinabox](https://user-images.githubusercontent.com/58527636/103438971-71c12280-4c41-11eb-954c-51698efe8c96.jpg)

**Comment by LucaForever** [comment]
The problem was that i made the wrong directory.

**Comment by benthetechguy** [comment]
@LucaForever How did you fix it? I have the same problem and i've tried both `/sdcard/Android/com.aof.mcinabox/files/MCinaBox/runtimepack` and `/sdcard/Android/com.aof.mcinabox/files/MCinaBox/runtime`, and neither have worked.

**Comment by CriticalRange** [comment]
@benthetechguy look at the second image, you should change to public directory and put the file inside that folder i suggest don't change the file directory

**Comment by benthetechguy** [comment]
I actually was able to use the private directory. I figured out that `/sdcard` doesn't correspond to the actual sd card, rather to a part of internal storage.
