### ISSUE TITLE
Keyboard file is damaged, tried multiple and nothing works.

### ISSUE THREAD

**Issue by Tommy2678** [AOF-Dev/MCinaBox#783]
**Describe the bug**
Where you try to import a keyboard, it just tells you the file is damaged. I've tried multiple, so I don't know why it says they're all damaged 

**To Reproduce**
1. Go to Keyboard settings 
2. Click on The wrench
3. Scroll down to your file and import

**Expected behavior**
Adding the keyboard with no problems.

**Screenshots**
https://youtu.be/jYlJNykqwtc

**Smartphone (please complete the following information):**
 - Device: [OnePlus 8]
 - OS: [Android 10]
 - App Version [0.1.4 p4]

**Additional context** 
I have also had a bug with just not being able to launch 1.16.4 at all, however I think there's multiple tutorials for that anyways.

**Comment by AyHa1810** [comment]
https://github.com/AOF-Dev/MCinaBox/suites/1750866518/artifacts/33286361

Try these, its v0.1.4-p5. It supports 1.14+ with aarch64 runtime.

**Comment by Tommy2678** [comment]
I actually found out it was because I was using a 1.13 keyboard! Thanks to the person who commented on the video! :D
