### ISSUE TITLE
为什么我今天安装mcinabox后手机上自动多出来一个leaks软件？

### ISSUE THREAD

**Issue by yejunjie10311031** [AOF-Dev/MCinaBox#787]
mcinabox版本是actions里的0.1.4p5:
https://github.com/AOF-Dev/MCinaBox/actions/runs/455627329
我安装后手机上多出来一个leaks是甚么东西？
![Screenshot_20210102_203848_com aof mcinabox](https://user-images.githubusercontent.com/62139629/103481543-9baa4e80-4dd3-11eb-864d-8055cd4fab45.jpg)
![Uploading Screenshot_20210103_224920_com.aof.mcinabox.jpg…]()

**Comment by longjunyu2** [comment]
引入了一个检测内存溢出的库，因此debug编译后会出现一个新的图标。
