### ISSUE TITLE
I keep crashing when I press wrench button 

### ISSUE THREAD

**Issue by SpargGaming** [AOF-Dev/MCinaBox#788]
why i keep crashing everytime i press the wrench button, its only happened when i was in the game. thank you

Device: Infinix hot play 9
Android: 10
MCinaBox Version: 0.1.4 (p5)

**Comment by longjunyu2** [comment]
Hello @SpargGaming.
  The current description does not provide enough information. I think we should find a way to reproduce this bug.
  I need more information if you can use logcat.
  Originally MCinaBox can get the running log, but I don't know why this function disappeared...
