### ISSUE TITLE
Bug Reports and Issues

### ISSUE THREAD

**Issue by AyHa1810** [AOF-Dev/MCinaBox#794]
**Launcher:**
(X) Bug 1: The buttons aren't completely visible, or the list isn't scrollable in the menu in the screenshot. **[Fixed]**
![Screenshot_2021-01-05-12-07-39-25_4cb6582af5c3b01ac644d295dc92f43e](https://user-images.githubusercontent.com/63386848/103614922-a689ee00-4f4f-11eb-96b7-be068d44fc69.jpg)

Bug 2: The input box sucks! You cannot delete or backspace a letter.
![Screenshot_2021-01-05-12-07-57-64_4cb6582af5c3b01ac644d295dc92f43e](https://user-images.githubusercontent.com/63386848/103615143-0ed8cf80-4f50-11eb-864e-569e400e0642.jpg)

Bug 3: The wrench button always gets resetted from its customised position after every restart.
![Screenshot_2021-01-05-12-20-01-60_4cb6582af5c3b01ac644d295dc92f43e](https://user-images.githubusercontent.com/63386848/103615343-71ca6680-4f50-11eb-9da0-b6082be53453.jpg)

Bug 4: the Jump button gets stuck at the same place after saving the buttons configuration, by which you can't change the position of Jump button.
![Screenshot_2021-01-05-12-10-44-55_4cb6582af5c3b01ac644d295dc92f43e](https://user-images.githubusercontent.com/63386848/103615616-e30a1980-4f50-11eb-9b1f-17285a38c071.jpg)

(X) Bug 5: The restart prompt appears while the operation is done and working without requiring to restart. **[Fixed]**
![Screenshot_2021-01-05-12-35-05-77_4cb6582af5c3b01ac644d295dc92f43e](https://user-images.githubusercontent.com/63386848/103616600-bbb44c00-4f52-11eb-87ad-0f41ffd091e5.jpg)

Issue 1: Since Mojang is ported Minecraft accounts to Microsoft account, the current account authenticator doesn't work.
![Screenshot_2021-01-05-12-25-01-78_4cb6582af5c3b01ac644d295dc92f43e](https://user-images.githubusercontent.com/63386848/103615882-69bef680-4f51-11eb-883a-f5d0b00d0b81.jpg)

**Minecraft Bugs:**
Bug 6: The screen taps are slightly out of place from the input.
https://user-images.githubusercontent.com/63386848/103617442-434e8a80-4f54-11eb-998a-58b5d5369aa0.mp4

Bug 7: Some texture bugs, like the sheep is white, but the wool from it is different colour. And the spawn eggs on the hand is white or gray-ish.
![Screenshot_2021-01-05-12-45-46-55_4cb6582af5c3b01ac644d295dc92f43e](https://user-images.githubusercontent.com/63386848/103617799-e0a9be80-4f54-11eb-8a84-6ca1e8a80892.jpg)

Tested device: Oppo A9 2020
OS: ColorOS V7.1, Android 10, Kernel 4.14.117
Display: 720x1600 px, 269 dpi, 6.52 inches
in-game screen resolution: 1544x720 px 
(1) App version: v0.1.4-p5, commit: 5eeda31, bin: Android CI #75
Game Version: 1.16.4

**(15 January, 2021 Update)**
(X) Issue 2: To install newer version of the app or any other version, you have to uninstall the previous version. **[Fixed]**

(X) Bug 8: There is no gap in the title between "selected version" and "[version]". The format should be "Selected version: [version]. And there is random text written as "operating". **[Fixed]**
![Screenshot_2021-01-15-22-30-00-71_4cb6582af5c3b01ac644d295dc92f43e](https://user-images.githubusercontent.com/63386848/104756188-7fb68d80-5781-11eb-89ba-c03837fae669.jpg)

(2) App version: v0.1.4-p5, commit: 9cfebb5, bin: Android CI #87
Game Version: 1.16.5

Mentions: @longjunyu2, @Iscle

**Comment by ThatGifIsNice** [comment]
@longjunyu2, @Iscle please fix in next beta

**Comment by longjunyu2** [comment]
OK, you found a lot of bugs. It's going to take some time, but I'm going to solve them anyway...

**Comment by longjunyu2** [comment]
I also noticed that the design of mcinabox's interface is very unreasonable. As a result, screen synthesis becomes very stuck on some devices. I want to rewrite them, but it's a time-consuming work. I want to finish it later.

**Comment by AyHa1810** [comment]
@longjunyu2 ok you can take your time. And also, thanks for your responce.

**Comment by AyHa1810** [comment]
Also, I don't even have a f√¢×ing minecraft account. Damn I'm broke

**Comment by AyHa1810** [comment]
Update: Bug 1, 5 and 7 are fixed.

App version: v0.1.4-p5, commit: 9cfebb5, bin: Android CI #87
Game Version: 1.16.4

**Comment by AyHa1810** [comment]
@longjunyu2 lol I forgot to mention another issue. 
It's related to the app installation. 

Issue 2: To install newer version of the app or any other version, you have to uninstall the previous version.

**Comment by longjunyu2** [comment]
I didn't close this issue but it was closed by itself ?

**Comment by AyHa1810** [comment]
@longjunyu2 maybe you mentioned this issue as fixed, so it automatically got closed.

**Comment by CosineMath** [comment]
Coloring of sheep has been fixed.
