### ISSUE TITLE
Controller Support

### ISSUE THREAD

**Issue by ThatGifIsNice** [AOF-Dev/MCinaBox#800]
Support for Dualshock or Xbox controller please if possible, eould be really nice

**Comment by longjunyu2** [comment]
Yes, and this is what I am doing.

**Comment by longjunyu2** [comment]
Currently only Xbox 360 mode game handles are supported, PS4 support will be added in the future.

Left Rocker: Control Direction
Right Rocker: Control Perspective and Mouse Pointer
Cross key: up: F4 down: ESC right: F3 left: F2
LB: Scroll up
RB: Scroll down
LT: Right mouse button
RT: Left mouse button
X: E
Y: Q
A: Space
B: Left Shift
THUMBR: Left Shift

These are all keys currently in use.

**Comment by longjunyu2** [comment]
Try to restore the bedrock version of the handle operation, but some can not be restored
