### ISSUE TITLE
Change MCPE Controls

### ISSUE THREAD

**Issue by ReinerPing** [AOF-Dev/MCinaBox#803]
How am i able to change the Controls of the MCPE Controls? I want to reposition them into a corner.

Thank you for your help! :)

**Comment by ThatGifIsNice** [comment]
You can, in game theres a settings sign like that wrench, when youre on that menu press the padlock thingy so it turns blue and opens now u can move it wherever u loke( hold press the mcpe controll thingy but dont press the buttons)

**Comment by ReinerPing** [comment]
Thank you it worked! :D
