### ISSUE TITLE
Feature Request! Do you intend to create aarch 8 32? or do you intend to create an aarch 32 that is almost unlimited just like aarch 64?

### ISSUE THREAD

**Issue by OwzygZawg** [AOF-Dev/MCinaBox#811]
Do you intend to create aarch 8 32? or do you intend to create an aarch 32 that is almost unlimited just like aarch 64?

**Comment by SnowNF** [comment]
On windows,32 bit OpenJDK also has a limit of RAM(up to about 1G)

It's impossible to use more than 1G RAM while using 32 bit runtime

Sorry,I'm poor in English

**Comment by OwzygZawg** [comment]
Got it! but i was talking if it was possible to use jre2 as well as Pojav in mcinaboxP5 .. no need to apologize! I understood what you meant

**Comment by OwzygZawg** [comment]
:)

**Comment by CosineMath** [comment]
What are you talking about? I don't know what is jre2.

**Comment by CosineMath** [comment]
We use openjdk-8 for both 32bit and 64bit.

**Comment by ChargedHat42838** [comment]
What's meaning of unlimited max memory on 64 bit architecture?

**Comment by OwzygZawg** [comment]
> O que significa memória máxima ilimitada na arquitetura de 64 bits?

64 can allocate much more memory than 32

**Comment by OwzygZawg** [comment]
> Do que você está falando? Não sei o que é jre2.

If you play Pojav on a 32 cell phone, you should know that is jre2

**Comment by CosineMath** [comment]
So I don't know such thing as jre2.

**Comment by CosineMath** [comment]
Maybe jre2 is specialized for pojav. openjdk-8 works well for MCinaBox. Closing.

**Comment by OwzygZawg** [comment]
Can 32 bytes be able to run at 23 or 30 FPs in Mcinabox? Pojav outperforms Mcinabox at the moment
