### ISSUE TITLE
Shift[Sneaking]

### ISSUE THREAD

**Issue by YuraMC** [AOF-Dev/MCinaBox#815]
After MCinaBox version 0.1.3 if you want to sneak, the shift button must be constantly pressed, otherwise you will stop sneaking, this is very inconvenient

**Comment by AyHa1810** [comment]
Bruh, this already exist. Here, use my key config
[Key-config_1544x720px_269dpi.json.zip](https://github.com/AOF-Dev/MCinaBox/files/5794208/Key-config_1544x720px_269dpi.json.zip)
