### ISSUE TITLE
Game gives me "out of memory error" when I try to go into any games

### ISSUE THREAD

**Issue by leem919** [AOF-Dev/MCinaBox#818]
Main menu works fine, but if I try to go into a sp or mp game, the game hangs for a minute, then crashes saying that it ran out of memory, so can I somehow dedicate more memory?

**Comment by ChargedHat42838** [comment]
![Screenshot_2021-01-11-08-15-23-199_com aof mcinabox](https://user-images.githubusercontent.com/70811047/104143395-3d89f680-53e5-11eb-82ba-dbc88c4463bf.jpg)
Press on this global game settings and next
![Screenshot_2021-01-11-08-14-51-678_com aof mcinabox](https://user-images.githubusercontent.com/70811047/104143413-51cdf380-53e5-11eb-9ca8-daa949ef436c.png)
Turn on automatically set memory limit it will set for your device automatically. Works only on Mcinabox version-p4+.

**Comment by Tol561** [comment]
Highlight in maximum memory up to 6000 and the game will not fly out. Manually.

**Comment by evan25lee** [comment]
Don't set it to 6000, that is the limit of your Phone, set it to 3000. If its an S9, the OS is only using around 2.8gb of ram so you have 3gb left.

**Comment by leem919** [comment]
Thanks, found it, set it to 1024 and game runs fine now :)
