### ISSUE TITLE
Pixelmon pc glitch and crash

### ISSUE THREAD

**Issue by ASGAMING009** [AOF-Dev/MCinaBox#823]
[crash-2021-01-13_07.25.27-client.txt](https://github.com/AOF-Dev/MCinaBox/files/5807187/crash-2021-01-13_07.25.27-client.txt)
Whenever i open PC to put my pokemons its did a weird thing and crash. Pls help This problem is Serious Many people in my discord server Want it to be fixed. Pls Help and fix it.
![Screenshot_20210113-125542_MCinaBox](https://user-images.githubusercontent.com/68546736/104421364-40c9e180-55a1-11eb-9a91-40f1d15f30d6.jpg)

**Comment by Luwaee** [comment]
It has something to do with input, that's what the devs told me. Hopefully it can be fixed.

**Comment by ASGAMING009** [comment]
Lu

> It has something to do with input, that's what the devs told me. Hopefully it can be fixed.

Do you know how to contact with one of their developers because i really want to play it. And thanks for the reply

**Comment by TSaltedfishKing** [comment]
you should not add mods
- NEI

**Comment by TSaltedfishKing** [comment]
> you should not add mods
> - NEI

because the mod needs something 
but we don not put it on runtimepacks

**Comment by Luwaee** [comment]
@ASGAMING009 It's an MCinabox-side unfortunately not Pixelmon, hopefully this will get fixed on the next update.

**Comment by ASGAMING009** [comment]
> @ASGAMING009 It's an MCinabox-side unfortunately not Pixelmon, hopefully this will get fixed on the next update.

 Thanks bro your so helpful not like that guy who is saying dont use mods blah blah blah. Hope is all that matters right now...

**Comment by ASGAMING009** [comment]
> > you should not add mods
> > 
> > * NEI
> 
> because the mod needs something
> but we don not put it on runtimepacks

If you're working with mcinabox devs Pls try to talk with them and fix this. Thanks for reply.

**Comment by TSaltedfishKing** [comment]
> > > you should not add mods
> > > 
> > > * NEI
> > 
> > because the mod needs something
> > but we don not put it on runtimepacks
> 
> If you're working with mcinabox devs Pls try to talk with them and fix this. Thanks for reply.

yeah
but we want not fix it
sorry
you can report this future result to the mod's devloper

**Comment by ASGAMING009** [comment]
> > > > you should not add mods
> > > > 
> > > > * NEI
> > > 
> > > 
> > > because the mod needs something
> > > but we don not put it on runtimepacks
> > 
> > 
> > If you're working with mcinabox devs Pls try to talk with them and fix this. Thanks for reply.
> 
> yeah
> but we want not fix it
> sorry
> you can report this future result to the mod's devloper

You think they will fix it???

**Comment by ASGAMING009** [comment]
> > > > you should not add mods
> > > > 
> > > > * NEI
> > > 
> > > 
> > > because the mod needs something
> > > but we don not put it on runtimepacks
> > 
> > 
> > If you're working with mcinabox devs Pls try to talk with them and fix this. Thanks for reply.
> 
> yeah
> but we want not fix it
> sorry
> you can report this future result to the mod's devloper

I talked with them and they said this
![Screenshot_20210115-195308_Discord](https://user-images.githubusercontent.com/68546736/104738335-686ca580-576b-11eb-84e6-dce8e14bda78.jpg)

**Comment by TSaltedfishKing** [comment]
😂
okay 
we will add support library into runtime pack
thank your's feedback

**Comment by ASGAMING009** [comment]
> 😂
> okay
> we will add support library into runtime pack
> thank your's feedback

Thanks bro.

**Comment by ASGAMING009** [comment]
> @``

**Comment by ASGAMING009** [comment]
THANKS
