### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by FurryRbl** [AOF-Dev/MCinaBox#824]
我在打开1.16.4但游戏中画面是白色的,游戏启动后有一层模糊的白色
如果这是一个bug希望快点解决

![Screenshot_20210113_210948_com aof mcinabox](https://user-images.githubusercontent.com/61524717/104456706-07ff2c00-55e4-11eb-84c9-1a01e2dc0d44.jpg)

**Comment by longjunyu2** [comment]
请提供： 设备型号 和 操作系统版本

**Comment by FurryRbl** [comment]
> 请提供：设备型号和操作系统版本
手机品牌：华为
型号：lon-al00
Android：9.0
hwui：9.0.1

**Comment by longjunyu2** [comment]
好的好的，请问你之前使用过MCinaBox 0.1.3的版本吗？

**Comment by FurryRbl** [comment]
> 好的好的，请问你之前使用过MCinaBox 0.1.3的版本吗？
没有

**Comment by longjunyu2** [comment]
好的

**Comment by CosineMath** [comment]
你使用1.16.4遇到了这个问题。请问你能否试一下1.7.10看看是否也有这个问题？

**Comment by FurryRbl** [comment]
> 您使用1.16.4遇到了这个问题。请问你能否试一下1.7.10看看是否也有这个问题？

1.7.10我进不去,会崩溃

**Comment by artdeell** [comment]
尝试1.12.2

**Comment by FurryRbl** [comment]
> 尝试1.12.2

不会出现什么问题

**Comment by FurryRbl** [comment]
> 尝试1.12.2

我希望能快点解决吧。
