### ISSUE TITLE
Runtime does not want to install

### ISSUE THREAD

**Issue by bobfromthefuture** [AOF-Dev/MCinaBox#828]
When i try to click import runtime(i have tried aarch32_runtime_20200328.tar.xz and aarch64-20200927.tar.xz) it still shows me this screen even tho when i click import after that it says "runtime installed sucsesfully", it shows me this screen if i try to boot up the game: 
![Screenshot_2021-01-14-14-59-00-779_com aof mcinabox](https://user-images.githubusercontent.com/77444789/104594575-04b67f80-567a-11eb-8a78-2696e2d6f72c.jpg)

 - Device: xiaomi redmi note 9 pro
 - OS:  Android 10
 - App Version: 0.1.4-p5

**Comment by TSaltedfishKing** [comment]
@longjunyu2

**Comment by ThatGifIsNice** [comment]
Try reinstalling the app and look up if your phone is 64 or 32 i think it might dont work bcs u installed the wrong one first and it stayed there when u installed the new one

**Comment by bobfromthefuture** [comment]
I didnt have it on sd/android/data etc.. only on the phones own memory
