### ISSUE TITLE
WEIRD TEXT

### ISSUE THREAD

**Issue by ZeyMax** [AOF-Dev/MCinaBox#829]
Hi, When I join servers, sometimes the text is weird

![WEIRD TEXT](https://user-images.githubusercontent.com/77450245/104647849-bd98b080-56b2-11eb-9982-529800ee215f.png)

Please help

 - Device: Huawei P30
 - OS: Android 10
 - App Version v0.1.3

**Comment by ASGAMING009** [comment]
Install new Mcinabox. Then it will be fix or you can use optifine

**Comment by ZeyMax** [comment]
What version ?
