### ISSUE TITLE
MCinaBox v0.1.4-p5 Error forge 1.7.10 

### ISSUE THREAD

**Issue by Kuprik007** [AOF-Dev/MCinaBox#831]
What can be done about it
![Screenshot_20210115_130324_com aof mcinabox](https://user-images.githubusercontent.com/72050618/104714197-f88ff800-5735-11eb-9194-075af8b7e87d.jpg)

**Comment by ThatGifIsNice** [comment]
Install minecraft 1.7.10 first then install the forge

**Comment by Kuprik007** [comment]
I installed

**Comment by Kuprik007** [comment]
Minecraft 1.7.10 But forge doesn't want to

**Comment by RaydanOMGr** [comment]
Oh, Beeline

**Comment by Kuprik007** [comment]
I figured it out if you also have such an error then download Forge universal

**Comment by Kuprik007** [comment]
I figured it out if you also have such an error then download Forge universal
