### ISSUE TITLE
Config file support ? (from modpacks)

### ISSUE THREAD

**Issue by ThatGifIsNice** [AOF-Dev/MCinaBox#832]
Hello @longjunyu2, 
Thank you for giving us such wonderfull software, i would like to ask if the forge is an artificial version or is it also straight up emulated ? Since you can run mods but it seems like it doesnt recognise/implement the config folder which is used in any modpack out there (to note: you could theoretically play any modpack by pasting the for example the comtent of the mod zip onto the .minecraft folder files) 

To cut it short:
-would it be possible to implememt config folder support (which configurates how mods work, mostly in modpacks)
-or is it already there and i did something wrong ?
 Thanks for reading this and sorry for the tags

**Comment by CosineMath** [comment]
Configuration of mods work well, thanks.

**Comment by CosineMath** [comment]
The forge is not a modified or patched version for MCinaBox, just same as one in PC.
