### ISSUE TITLE
Add ×86 runtime?

### ISSUE THREAD

**Issue by Plizik** [AOF-Dev/MCinaBox#835]
When I launch the game it's says that architecture is more than runtime. And it's right, runtimes are 32bit and 64bit, not 86bit! Just asking, is it possible to do it, or not for my device?

**Comment by CosineMath** [comment]
Sorry, x86 support might not be in plan.

**Comment by Plizik** [comment]
then someone made if can or want ok? I close it now

**Comment by BryleHelll** [comment]
> Sorry, x86 support might not be in plan.

But, why? It would be nice if intel tabs can also use the app

**Comment by BryleHelll** [comment]
Btw, by combining mcinabox lwjgl (2 and 3) with pojav's JRE8 x86 , u would get your x86 runtime. Then u would compile mcinabox app for x86 architecture

**Comment by CosineMath** [comment]
We developers don't have any android x86 device....So we could not test MCinaBox in x86 device and release the runtime.

**Comment by BryleHelll** [comment]
> We developers don't have any android x86 device....So we could not test MCinaBox in x86 device and release the runtime.

I saw some guys running x86 linux distros on arm device.

**Comment by BryleHelll** [comment]
Maybe use limbo pc emulator then put android x86

**Comment by dashboarder** [comment]
pojav one simply compiled aarch64 port for x86 target. for android x86. if one has pc just fire up android emulator in it
