### ISSUE TITLE
Runtime not detected

### ISSUE THREAD

**Issue by tinker1234** [AOF-Dev/MCinaBox#842]
Okay i downloaded the runtime and the latest version of mcinbox installed the file via launcher settings it extracted from my downloads folder and its not detecting it

**Comment by tinker1234** [comment]
That was in the first prerelease

**Comment by KorewaLidesu** [comment]
You don't need to extract the runtime.
Just go to Launcher Setting, press Import in Runtime section, and select the runtime package.

**Comment by Danika6677** [comment]
Tho where is the Runtime?

**Comment by KorewaLidesu** [comment]
> Tho where is the Runtime?

p1

**Comment by CosineMath** [comment]
Use latest version, OK?
