### ISSUE TITLE
Добавьте фабрик

### ISSUE THREAD

**Issue by Bekzat123** [AOF-Dev/MCinaBox#843]
1. Почему нет фабрик
2.У других ну там pojav launcher есть фабрик а на Mcinabox нету.
3Фабрик лучше фордж добавить фабрик это круто тип для фабрик модом много

**Comment by RaydanOMGr** [comment]
Фабрик вообще-то нужно самому качать 😑

**Comment by RaydanOMGr** [comment]
fabricmc.com если я не ошибаюсь

**Comment by artdeell** [comment]
> Фабрик вообще-то нужно самому качать 😑

он имеет ввиду что этот ваш мсинабокс поддерживает только утановку форжа внутри себя

**Comment by artdeell** [comment]
а появ умеет и фабрик и оптифайн и форж

**Comment by CosineMath** [comment]
Fabric works fine with Boat, and so will be supported in MCinaBox soon. A installer and resolver would be needed.
