### ISSUE TITLE
提出了一个带增加要求？

### ISSUE THREAD

**Issue by FurryRbl** [AOF-Dev/MCinaBox#844]
希望可以做得和[Hmcl](https://github.com/huanghongxun/hmcl)差不多

**Comment by KorewaLidesu** [comment]
Android limit alot of things. Which make this request hard to complete.

**Comment by CosineMath** [comment]
在“启动MC”方面我们会继续改进，尽可能像HMCL那样功能完整。当然MCinaBox有其特殊性，还需要做HMCL不用做的事情：）。
