### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by Ice-fire-perfect** [AOF-Dev/MCinaBox#845]
I put the file into right folder，it detected，however，it doesn't work，is that my problem?

**Comment by RaydanOMGr** [comment]
What a file?

**Comment by Xag8031** [comment]
What file? If it is the runtime download it and open it using the app

1. Open the app.
2. Go to launcher settings
3. Tap empty
4. Tap continue 
5. Tap import runtime
6. Tap select from storage...
7. Find where it downloads to
8. Tap the runtime

**Comment by CosineMath** [comment]
Use latest version and import runtime pack by following the file chooser.
