### ISSUE TITLE
I have a question what is a the runtime and how unistal it

### ISSUE THREAD

**Issue by nightmareano** [AOF-Dev/MCinaBox#846]
1. If you have any questions, you can ask here and wait for the answers.
2. You can also post files or screenshots if it is related to the question.

**Comment by KorewaLidesu** [comment]
Have you ever play Minecraft Java Edition on PC?
Did you know that actually the game that you run on your PC is actually Java based code?

**Comment by KorewaLidesu** [comment]
Runtime in here is mean the Java Runtime that allow minecraft to start up.
As its name, **Java edition**

**Comment by KorewaLidesu** [comment]
Uninstall by go to the Launcher Setting, click to Empty on Runtime section.
