### ISSUE TITLE
Where to get the runtime, and which one do I need?

### ISSUE THREAD

**Issue by legop3** [AOF-Dev/MCinaBox#847]
What place online should I download the runtime package from? I tried the windows, linux, and linux arm installer files, but none of them showed up in the app under the downloads folder.

**Comment by Valdex** [comment]
You can download here: https://github.com/AOF-Dev/MCinaBox/releases/tag/v0.1.4-p2

**Comment by CosineMath** [comment]
Runtime packs are released in [Releases](https://github.com/AOF-Dev/MCinaBox/releases). Please read release information in detail.
