### ISSUE TITLE
When importing runtime it still shows as empty

### ISSUE THREAD

**Issue by Xyth0n** [AOF-Dev/MCinaBox#849]
**When I import the latest version it told me to go to p1 so I went there and it said to go to v0.1.0 and when I go there and copy the runtime I go to the app and I import it after clicking downloads, it says successfully installed runtime but it shows as empty**

I explained on the paragraph on top

** I expected it to show the runtime next to the import button but when I import it just says empty**

** I am typing this on my Chromebook so I cant provide this but if there is some sort of discord I can definitely show it there**

**Smartphone (please complete the following information):**
 - Device: [e.g. LGq7+]
 - OS: [e.g. Android]
 - App Version [e.g. v0.1.4-p5.apk]
 - CPU architecture [e.g. arm64]  
** I have heard that it doesn't work for some devices but i am not sure if it works for mine**

**Comment by longjunyu2** [comment]
Download [aarch64-20200927.tar.xz](https://github.com/AOF-Dev/MCinaBox/releases/download/v0.1.4-p2/aarch64-20200927.tar.xz)

**Comment by longjunyu2** [comment]
aarch32_runtime_20200328.tar.xz is for 0.1.3 and 0.1.4 can not find it.

**Comment by CosineMath** [comment]
Import correct pack. Rutime pack for 0.1.3- is not compatible with new one.
