### ISSUE TITLE
添加一个功能

### ISSUE THREAD

**Issue by FurryRbl** [AOF-Dev/MCinaBox#850]
我弄错了标签
这应该是请求添加一个功能
我系统添加一个自动下载源

**Comment by CosineMath** [comment]
什么是自动下载源？

**Comment by FurryRbl** [comment]
> 什么是自动下载源？

应该是我输入的内容被谷歌翻译了
应该是添加一个自定义下载源

**Comment by CosineMath** [comment]
可能在将来的版本考虑加入。不过为什么需要自定义下载源呢？我也就知道几个下载源：官网、bmclapi、mcbbs

**Comment by FurryRbl** [comment]
> 可能为什么将来的版本考虑加入。不过为什么需要自定义下载源呢？我也就知道几个下载源：官网，bmclapi，mcbbs

一些人或者学校会搭建镜像站

**Comment by CosineMath** [comment]
了解了。接下来看龙总心情。（逃
