### ISSUE TITLE
Textures need updated gl4es 

### ISSUE THREAD

**Issue by pedrosouzabrasil** [AOF-Dev/MCinaBox#854]
**Describe the bug**
A clear and concise description of what the bug is.Some textures are white and need an update from gl4es(ptitseb)

**To Reproduce**

**Expected behavior**
textures are wrong in game(some spawn eggs..experience orbs..sheep texture etc)

**Screenshots**
There are many..also some issues related to this

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy J6] any arm device
 - OS: [e.g. Android 8.1]any
 - App Version [e.g. v0.1.3]any
 - CPU architecture [e.g. arm64]  
**Additional context**
need to use latest gl4es commit from ptitseb from gitthub

**Comment by longjunyu2** [comment]
OK

**Comment by pedrosouzabrasil** [comment]
Thanks ..also keep amazing work !blessed day /night dev

**Comment by CosineMath** [comment]
OK. We might releases split runtime pack for some updating components. In fact, it is easy to update components by yourself.

**Comment by OkkkkfdzJkk** [comment]
@CosineMath I have a texture problem, please help me when I hit some mob the game texture bugs completely, and as far as I know it's a gl4es bug, which seems to only occur on 64 bit cell phones
