### ISSUE TITLE
Feature Request: Fabric API support?

### ISSUE THREAD

**Issue by XnimaPRO** [AOF-Dev/MCinaBox#857]
Will mcinabox have native Fabric API support? Fabric's high efficiency with sodium may enhance the gaming experience:)

**Comment by longjunyu2** [comment]
The fabric API has been supported in the test. We are looking for an installation scheme for the fabric API. Please wait for this function to be updated.

**Comment by MatheusTgamerPro** [comment]
> The fabric API has been supported in the test. We are looking for an installation scheme for the fabric API. Please wait for this function to be updated.

Would that mean that mods will work on the MCinaBox Fabric?

**Comment by MatheusTgamerPro** [comment]
> > Would that mean that mods will work on the MCinaBox Fabric?
> 
> Yes, I have been playing Minecraft together with Fabric and VoxelMap for a period. Works fine.

Good! But does Optifine work? If so, this is already a giant step forward for MCinabox!

**Comment by MohammadH15** [comment]
hi

**Comment by MohammadH15** [comment]
i want a version of mcinabox that supports fabric olz
