### ISSUE TITLE
I have a question. Will MCinaBox be updated to work with for and optifine in newer versions?

### ISSUE THREAD

**Issue by GavinKacprowicz** [AOF-Dev/MCinaBox#862]

**Comment by BryleHelll** [comment]
As Muhd tested, mcinabox dont support optifine 1.16

**Comment by BryleHelll** [comment]
But newer pojav versions does.

**Comment by GavinKacprowicz** [comment]
> But newer pojav versions does.

Where do I get these versions?

**Comment by CosineMath** [comment]
Forge is already supported. We might working on test for optifine soon.

**Comment by GavinKacprowicz** [comment]
> Forge is already supported. We might working on test for optifine soon.

How do I install forge? I tried moving the files from the computer but when I start the game it stays on a white screen.
