### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by ryksa29** [AOF-Dev/MCinaBox#867]
Is Mcinabox have viruses? I check the apk file in virustotal, and it says : Android.Boogr.Afc50[](https://www.virustotal.com/gui/file/765a1d8f2920c67c7a102fc88469872798b22ae66a86b76d9ca52f4cdb8ff746/detection)

**Comment by Xag8031** [comment]
Mcinabox does not have any viruses, If you play it modded the mods you get might be viruses

**Comment by ryksa29** [comment]
> Mcinabox does not have any viruses, If you play it modded the mods you get might be viruses

Okay, thanks
