### ISSUE TITLE
OpenGL Error

### ISSUE THREAD

**Issue by Benefit-Zebra** [AOF-Dev/MCinaBox#868]
**Description**
Chat repeatedly shows OpenGL Error: 1280 (Invalid Enum)
I have Forge and Optifine running.

**To Reproduce**
1. Join a server
2. See error in chat

**Screenshots**
![ScreenShot](https://user-images.githubusercontent.com/42458260/105450144-e2d38300-5c9f-11eb-94f9-817c58d4fbb5.jpg)

**Smartphone: **
 - Device: Samsung M30s
 - OS: Android 10
 - App Version: v0.1.3

**Comment by YuraMC** [comment]
This message is sending by optifine

**Comment by KorewaLidesu** [comment]
Optifine always has a strict rule to use it.
You can just ignore that message if it didn't drop performance.

**Comment by Benefit-Zebra** [comment]
> Optifine always has a strict code to use it.
> You can just ignore that message if it didn't drop performance. (or turn off it in Option -> Other -> OpenGL Error)

Thanks Very Much 👍
