### ISSUE TITLE
ram bug

### ISSUE THREAD

**Issue by RaydanOMGr** [AOF-Dev/MCinaBox#869]
On my phone i the ram limit is too low and to high at once
![Screenshot_2021-01-22-10-44-15](https://user-images.githubusercontent.com/73817645/105475073-4315f500-5c9f-11eb-982a-9f1d8bd76c21.png)

Device: Samsung Galaxy S5
RAM: 1,67GB
CPU: Qualcomm Snapdragon 801 (MSM8974AC)

**Comment by CosineMath** [comment]
Use 64bit version to allocate more ram. Also a new phone with more ram is better.
