### ISSUE TITLE
Can't open version a1.2.6 and 1.0 (MCinaBox 0.1.3)

### ISSUE THREAD

**Issue by Fl414r** [AOF-Dev/MCinaBox#872]
![Screenshot_20210123_225925_com aof mcinabox](https://user-images.githubusercontent.com/74704475/105612728-d13cc900-5dce-11eb-9cec-a73abedd9210.jpg)
Downloaded, opened and error "No game inventory data"
What to do? I wanted to play old Minecraft on my phone...

**Comment by jianren818** [comment]
It seems that there will be an X11 error when starting the Minecraft version below 1.6

**Comment by Fl414r** [comment]
![Screenshot_20210124_111921_com aof mcinabox](https://user-images.githubusercontent.com/74704475/105624891-3677d500-5e36-11eb-8ad3-02fb60733fcc.jpg)
![Screenshot_20210124_111915_com aof mcinabox](https://user-images.githubusercontent.com/74704475/105625088-cc602f80-5e37-11eb-8fbb-b2082b4406ed.jpg)

1.12.2 Forge, 1.12.2 vanila and 1.11.2 works fine when played on servers. In single player mode, after a short time, a crash occurs on all versions and the launcher settings are deleted. (But the Skyblock 3.07 map for 1.12.2 does not crash)

1.16 works, but I can't switch between 1-9 inventory slots, all textures are black and I can't move the camera.
![Screenshot_20210124_122404_com aof mcinabox](https://user-images.githubusercontent.com/74704475/105626255-94f58100-5e3f-11eb-87f1-a22c5e2802c8.jpg)

(Hmm ... Why did I write this, although I'm talking about a non-working alpha version of Minecraft ... Well, let it be here.)

**Comment by CosineMath** [comment]
It is a known issue listed in README that Minecraft 1.5 and older one do not work. There is no plan for supporting these old versions in recent.
