### ISSUE TITLE
Forge 1.12.2 2855 installer cannot download libraries

### ISSUE THREAD

**Issue by vico93** [AOF-Dev/MCinaBox#873]
**Describe the bug**
Basically when trying to install the latest version of Forge 14.23.5.2855 mcinabox fails to download the libraries, making a unusable (game with no sound/language other than english) forge version on the launcher.

**To Reproduce**
1. Download the 14.23.5.2855 installer from [forge website](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.2.html)
2. Try to install
3. Failed to download error appears

**Expected behavior**
14.23.5.2855 being installed sucessfully

**Smartphone (please complete the following information):**
 - Device: [Cubot Note 20 Pro](https://cubot.net/smartphones/note-20-pro)
 - OS:  Android 10
 - App Version: v0.1.4-p5
 - CPU architecture: arm64

**Additional context**
The problem happened in the phone of my friend, that's why i didnt have screenshots to share with you

**Comment by Valdex** [comment]
Change official -> bmclapi
![Uploading Screenshot_20210125-163545.png…]()

**Comment by vico93** [comment]
Done. Thanks!
