### ISSUE TITLE
我有一个问题

### ISSUE THREAD

**Issue by jianren818** [AOF-Dev/MCinaBox#876]
将来有一天我们能在mcinabox上使用1.7.10的NEI、1.12.2的DE、TC4以及其他在mcinabox 0.1.4-p5无法正常游玩（比如说一查物品就崩溃或者无法启动）的mod吗？
我看到有一些人二次修改的boat已经能保证部分模组的完全兼容了（但还在未公布的测试阶段，此作者仅给出图片）

**Comment by CosineMath** [comment]
mio正在做这些工作，我们有和mio交流相关方法，未来可能在MCinaBox也上修复这些问题。

**Comment by jianren818** [comment]
> mio正在做这些工作，我们有和mio交流相关方法，未来可能在MCinaBox也上修复这些问题。

哦，那太好了
