### ISSUE TITLE
后台运行问题

### ISSUE THREAD

**Issue by jianren818** [AOF-Dev/MCinaBox#878]
一部分mod在游戏启动时会打开浏览器运行一些操作
但后台运行程序是在游戏启动完毕后运行的
这使得运行它们的时候会闪退

**Comment by jianren818** [comment]
emmmm
好像弄错了标签

**Comment by CosineMath** [comment]
没太懂你的意思。什么是“但后台运行程序是在游戏启动完毕后运行的”？MCinaBox目前并不支持mod唤起android系统上安装的浏览器。

**Comment by jianren818** [comment]
> 没太懂你的意思。什么是“但后台运行程序是在游戏启动完毕后运行的”？MCinaBox目前并不支持mod唤起android系统上安装的浏览器。

哦，怪不得用小地图之类的就崩了
