### ISSUE TITLE
Can you share libjvm.so?

### ISSUE THREAD

**Issue by fandangos** [AOF-Dev/MCinaBox#884]
Hi, 

I'm working on a project to bring full bluray playback to Android but I need a java runtime enviroment for Android for it to work.
I see that you are able to load libjvm.so in Android. 

Do you think you could share it with me? Or the source of it?

**Comment by CosineMath** [comment]
Just have a look on [openjdk aarch64 android](https://github.com/AOF-Dev/openjdk-aarch64-jdk8u-androidport) or [openjdk aarch32 android](https://github.com/CosineMath/openjdk-jdk8u-aarch32-android). You can get binaries compiled for MCinaBox by extracting them from runtime pack released in Releases page.
