### ISSUE TITLE
官网无法访问

### ISSUE THREAD

**Issue by sc-1123** [AOF-Dev/MCinaBox#886]
访问mcinabox.top时提示超时。
Chrome和新版Edge均出现此问题，是官网出了问题吗？

**Comment by CosineMath** [comment]
可能吧，不过这个网站不是由龙总维护的。

**Comment by Valdex** [comment]
English pls

**Comment by AyHa1810** [comment]
Sorry buddy, those websites aren't official. They are fan-made.

**Comment by AyHa1810** [comment]
> English pls

Title - 
The official website cannot be accessed

Issue - 
A timeout is prompted when accessing mcinabox.top.
 This problem occurs in both Chrome and the new version of Edge. Is there a problem with the official website?

CosineMath's comment 1 -
Maybe, but this website is not maintained by Mr. Long.

Translator - Google Translate (lmao)

**Comment by FrankOu2001** [comment]
官网啥的无所谓吧，github才是最主要的。
The official website doesn't matter, github is more important.

**Comment by WuJiayiUbi** [comment]
any release plan before china new year? ^_^

**Comment by CosineMath** [comment]
好像又能访问了，你看看吧。

Seems that works again.
