### ISSUE TITLE
Dear author,I need some help!

### ISSUE THREAD

**Issue by MisakaNatsu** [AOF-Dev/MCinaBox#890]
I want to port Minecraft to arm64 platform such as Raspberry Pi 4B.But I cannot find any LWJGL library which built on ARM64.
OpenAL are the same.I found them in your runtime pack,but I don't know how to modify the configuration file.I tried many times but I always failed.Can you give me some suggestion?
Thank you so much!!!

**Comment by FrankOu2001** [comment]
[link](https://tieba.baidu.com/p/5239832466?share=9105&fr=share&see_lz=0)  这个是longjunyu当年在贴吧的教程。他当时也用了这个方法让一个树莓派3B成功运行了minecraft 1.7.2。希望对你有帮助
This is a posting which was published by longjunyu in Baidu Post Barmany years ago . He also used the same way to run minecraft 1.7.2 successfully on a Raspberry Pi 3B. I hope it can be helpful to you.

**Comment by BryleHelll** [comment]
> I want to port Minecraft to arm64 platform such as Raspberry Pi 4B.But I cannot find any LWJGL library which built on ARM64.
> OpenAL are the same.I found them in your runtime pack,but I don't know how to modify the configuration file.I tried many times but I always failed.Can you give me some suggestion?
> Thank you so much!!!

What u can do is to chroot to a 32 bit os. Then install box86. 😃😃

**Comment by BryleHelll** [comment]
Box86 dont support 64 bit so chrooting to 32 bit os is needed

**Comment by BryleHelll** [comment]
Box86 is x86 emu

**Comment by CosineMath** [comment]
You can just compile lwjgl, openal, etc for rpi arm64. Please have a look on their doc. Good luck.

**Comment by CosineMath** [comment]
These packages have official ports for GNU/Linux arm64. The ports used in MCinaBox is specialized and would not work on rpi board.
