### ISSUE TITLE
Game crashes in-middle of playing

### ISSUE THREAD

**Issue by IdonthaveaPC** [AOF-Dev/MCinaBox#901]
Game crashes/closes everytime in-middle of game while using offline account. I selected for the app to set my ram automatically for me (718 mb ram)

- Device: Huawei Matepad T10
 - OS: Android 10
 - App Version v0.1.4-p5
 - CPU architecture: aarch64

**Comment by ASGAMING009** [comment]
Its not stable remember. ( Its happens to me alot of time i dont think it can be fix for NOW!)

**Comment by IdonthaveaPC** [comment]
Ok thanks for telling me, i can play on cracked servers fine.
