### ISSUE TITLE
how can i fix this

### ISSUE THREAD

**Issue by 321goahhhhhhhhhh** [AOF-Dev/MCinaBox#906]
WARNING: linker: Warning: "/data/data/com.aof.mcinabox/files/runtime/boat/j2re-image/lib/aarch64/libzip.so" unused DT entry: DT_RPATH (type 0xf arg 0x8fd) (ignoring)
WARNING: linker: Warning: "/data/data/com.aof.mcinabox/files/runtime/boat/j2re-image/lib/aarch64/libzip.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/com.aof.mcinabox/files/runtime/boat/j2re-image/lib/aarch64/libmanagement.so" unused DT entry: DT_RPATH (type 0xf arg 0x167c) (ignoring)
WARNING: linker: Warning: "/data/data/com.aof.mcinabox/files/runtime/boat/j2re-image/lib/aarch64/libmanagement.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
[08:55:09] [Client thread/INFO]: Setting user: ZianDaReal
[08:55:18] [Client thread/INFO]: LWJGL Version: 2.9.3
[08:55:18] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Could not create EGL context
	at org.lwjgl.opengl.BoatContextImplementation.nCreate(Native Method) ~[lwjgl.jar:?]
	at org.lwjgl.opengl.BoatContextImplementation.create(BoatContextImplementation.java:50) ~[lwjgl.jar:?]
	at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:134) ~[lwjgl.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:852) ~[lwjgl.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:759) ~[lwjgl.jar:?]
	at bib.at(SourceFile:622) [1.12.2.jar:?]
	at bib.aq(SourceFile:458) [1.12.2.jar:?]
	at bib.a(SourceFile:404) [1.12.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [1.12.2.jar:?]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2/1/21 8:55 AM
Description: Initializing game

org.lwjgl.LWJGLException: Could not create EGL context
	at org.lwjgl.opengl.BoatContextImplementation.nCreate(Native Method)
	at org.lwjgl.opengl.BoatContextImplementation.create(BoatContextImplementation.java:50)
	at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:134)
	at org.lwjgl.opengl.Display.create(Display.java:852)
	at org.lwjgl.opengl.Display.create(Display.java:759)
	at org.lwjgl.opengl.Display.create(Display.java:741)
	at bib.at(SourceFile:635)
	at bib.aq(SourceFile:458)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.BoatContextImplementation.nCreate(Native Method)
	at org.lwjgl.opengl.BoatContextImplementation.create(BoatContextImplementation.java:50)
	at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:134)
	at org.lwjgl.opengl.Display.create(Display.java:852)
	at org.lwjgl.opengl.Display.create(Display.java:759)
	at org.lwjgl.opengl.Display.create(Display.java:741)
	at bib.at(SourceFile:635)
	at bib.aq(SourceFile:458)

-- Initialization --
Details:
Stacktrace:
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version 4.9.117+
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 115234032 bytes (109 MB) / 201326592 bytes (192 MB) up to 239075328 bytes (228 MB)
	JVM Flags: 2 total; -Xmx256m -Xms128m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: MCinaBox_0.1.4-p5
	LWJGL: 2.9.3
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /storage/emulated/0/MCinaBox/gamedir/crash-reports/crash-2021-02-01_08.55.19-client.txt
LIBGL: Initialising gl4es
LIBGL: v1.1.2 built on Sep 26 2020 17:35:03
LIBGL: Using GLES 2.0 backend
LIBGL: loaded: libGLESv2.so
LIBGL: loaded: libEGL.so
LIBGL: Using GLES 2.0 backend
LIBGL: Hardware Full NPOT detected and used
LIBGL: Extension GL_EXT_blend_minmax detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Substract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_OES_mapbuffer detected
LIBGL: Extension GL_OES_element_index_uint detected and used
LIBGL: Extension GL_OES_packed_depth_stencil detected and used
LIBGL: Extension GL_OES_depth24 detected and used
LIBGL: Extension GL_OES_rgb8_rgba8 detected and used
LIBGL: Extension GL_EXT_multi_draw_arrays detected
LIBGL: Extension GL_EXT_texture_format_BGRA8888 detected and used
LIBGL: Extension GL_OES_depth_texture detected and used
LIBGL: Extension GL_OES_texture_stencil8 detected and used
LIBGL: Extension GL_EXT_texture_rg detected and used
LIBGL: Extension GL_OES_texture_float detected and used
LIBGL: Extension GL_OES_texture_half_float detected and used
LIBGL: Extension GL_EXT_color_buffer_float detected and used
LIBGL: Extension GL_EXT_color_buffer_half_float detected and used
LIBGL: Extension GL_OES_fragment_precision_high detected and used
LIBGL: Max vertex attrib: 16
LIBGL: Extension GL_OES_standard_derivatives detected and used
LIBGL: Extension GL_OES_get_program detected and used
LIBGL: Number of supported Program Binary Format: 1
LIBGL: Max texture size: 4096
LIBGL: Max Varying Vector: 15
LIBGL: Texture Units: 8(8), Max lights: 8, Max planes: 6
LIBGL: Extension GL_EXT_texture_filter_anisotropic detected and used
LIBGL: Max Anisotropic filtering: 2
LIBGL: Hardware vendor is Imagination Technologies
LIBGL: ignore MipMap
LIBGL: Targeting OpenGL 2.0
LIBGL: Not trying to batch small subsequent glDrawXXXX
LIBGL: try to use VBO
LIBGL: FBO workaround for using binded texture enabled
LIBGL: glX Will try to recycle EGL Surface
LIBGL: Current folder is:/

when i start minecraft it crashes

the version that im runing is 1.12.2 btw

**Comment by 321goahhhhhhhhhh** [comment]
when i run at a my 2nd phone. It show a white screen then turn black then plays minecraft well. but on this newer phone it show a black screen 1st then Boom it crashes

**Comment by 321goahhhhhhhhhh** [comment]
pls Respond

**Comment by SlerianDL** [comment]
Have you looked in this file?

/storage/emulated/0/MCinaBox/gamedir/crash-reports/crash-2021-02-01_08.55.19-client.txt

Also are you running any mods?

**Comment by SlerianDL** [comment]
From the error above it looks like its something to do with OpenGL.

OpenGL: ERROR RuntimeException: No OpenGL context found in the current thread.

Which makes me think you've got some kind of mod which is trying to change graphical effect I.e. dynamiclights. However if not, then maybe you phone is not graphically accelerating the application.

**Comment by 321goahhhhhhhhhh** [comment]
sorry im late. I was asleeep

**Comment by 321goahhhhhhhhhh** [comment]
oh just a sec

**Comment by 321goahhhhhhhhhh** [comment]
i don't have any mods installed

**Comment by 321goahhhhhhhhhh** [comment]
and the phone im using is

**Comment by 321goahhhhhhhhhh** [comment]
Infinix HOT 8

**Comment by 321goahhhhhhhhhh** [comment]
here is the latest one goodluck reading this


---- Minecraft Crash Report ----
// There are four lights!

Time: 2/1/21 10:07 AM
Description: Initializing game

org.lwjgl.LWJGLException: Could not create EGL context
	at org.lwjgl.opengl.BoatContextImplementation.nCreate(Native Method)
	at org.lwjgl.opengl.BoatContextImplementation.create(BoatContextImplementation.java:50)
	at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:134)
	at org.lwjgl.opengl.Display.create(Display.java:852)
	at org.lwjgl.opengl.Display.create(Display.java:759)
	at org.lwjgl.opengl.Display.create(Display.java:741)
	at bib.at(SourceFile:635)
	at bib.aq(SourceFile:458)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.BoatContextImplementation.nCreate(Native Method)
	at org.lwjgl.opengl.BoatContextImplementation.create(BoatContextImplementation.java:50)
	at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:134)
	at org.lwjgl.opengl.Display.create(Display.java:852)
	at org.lwjgl.opengl.Display.create(Display.java:759)
	at org.lwjgl.opengl.Display.create(Display.java:741)
	at bib.at(SourceFile:635)
	at bib.aq(SourceFile:458)

-- Initialization --
Details:
Stacktrace:
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version 4.9.117+
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 168818184 bytes (160 MB) / 251658240 bytes (240 MB) up to 430964736 bytes (411 MB)
	JVM Flags: 2 total; -Xmx462m -Xms128m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: MCinaBox_0.1.4-p5
	LWJGL: 2.9.3
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>

**Comment by 321goahhhhhhhhhh** [comment]
WARNING: linker: Warning: "/data/data/com.aof.mcinabox/files/runtime/boat/j2re-image/lib/aarch64/libzip.so" unused DT entry: DT_RPATH (type 0xf arg 0x8fd) (ignoring)
WARNING: linker: Warning: "/data/data/com.aof.mcinabox/files/runtime/boat/j2re-image/lib/aarch64/libzip.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/com.aof.mcinabox/files/runtime/boat/j2re-image/lib/aarch64/libmanagement.so" unused DT entry: DT_RPATH (type 0xf arg 0x167c) (ignoring)
WARNING: linker: Warning: "/data/data/com.aof.mcinabox/files/runtime/boat/j2re-image/lib/aarch64/libmanagement.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
[08:55:09] [Client thread/INFO]: Setting user: ZianDaReal
[08:55:18] [Client thread/INFO]: LWJGL Version: 2.9.3
[08:55:18] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Could not create EGL context
at org.lwjgl.opengl.BoatContextImplementation.nCreate(Native Method) ~[lwjgl.jar:?]
at org.lwjgl.opengl.BoatContextImplementation.create(BoatContextImplementation.java:50) ~[lwjgl.jar:?]
at org.lwjgl.opengl.ContextGL.(ContextGL.java:134) ~[lwjgl.jar:?]
at org.lwjgl.opengl.Display.create(Display.java:852) ~[lwjgl.jar:?]
at org.lwjgl.opengl.Display.create(Display.java:759) ~[lwjgl.jar:?]
at bib.at(SourceFile:622) [1.12.2.jar:?]
at bib.aq(SourceFile:458) [1.12.2.jar:?]
at bib.a(SourceFile:404) [1.12.2.jar:?]
at net.minecraft.client.main.Main.main(SourceFile:123) [1.12.2.jar:?]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2/1/21 8:55 AM
Description: Initializing game

org.lwjgl.LWJGLException: Could not create EGL context
at org.lwjgl.opengl.BoatContextImplementation.nCreate(Native Method)
at org.lwjgl.opengl.BoatContextImplementation.create(BoatContextImplementation.java:50)
at org.lwjgl.opengl.ContextGL.(ContextGL.java:134)
at org.lwjgl.opengl.Display.create(Display.java:852)
at org.lwjgl.opengl.Display.create(Display.java:759)
at org.lwjgl.opengl.Display.create(Display.java:741)
at bib.at(SourceFile:635)
at bib.aq(SourceFile:458)
at bib.a(SourceFile:404)
at net.minecraft.client.main.Main.main(SourceFile:123)

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Client thread
Stacktrace:
at org.lwjgl.opengl.BoatContextImplementation.nCreate(Native Method)
at org.lwjgl.opengl.BoatContextImplementation.create(BoatContextImplementation.java:50)
at org.lwjgl.opengl.ContextGL.(ContextGL.java:134)
at org.lwjgl.opengl.Display.create(Display.java:852)
at org.lwjgl.opengl.Display.create(Display.java:759)
at org.lwjgl.opengl.Display.create(Display.java:741)
at bib.at(SourceFile:635)
at bib.aq(SourceFile:458)

-- Initialization --
Details:
Stacktrace:
at bib.a(SourceFile:404)
at net.minecraft.client.main.Main.main(SourceFile:123)

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Linux (aarch64) version 4.9.117+
Java Version: 1.8.0-internal, Oracle Corporation
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 115234032 bytes (109 MB) / 201326592 bytes (192 MB) up to 239075328 bytes (228 MB)
JVM Flags: 2 total; -Xmx256m -Xms128m
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
Launched Version: MCinaBox_0.1.4-p5
LWJGL: 2.9.3
OpenGL: ERROR RuntimeException: No OpenGL context found in the current thread.
GL Caps:
Using VBOs: Yes
Is Modded: Probably not. Jar signature remains and client brand is untouched.
Type: Client (map_client.txt)
Resource Packs:
Current Language: ERROR NullPointerException: null
Profiler Position: N/A (disabled)
CPU:
#@!@# Game crashed! Crash report saved to: #@!@# /storage/emulated/0/MCinaBox/gamedir/crash-reports/crash-2021-02-01_08.55.19-client.txt
LIBGL: Initialising gl4es
LIBGL: v1.1.2 built on Sep 26 2020 17:35:03
LIBGL: Using GLES 2.0 backend
LIBGL: loaded: libGLESv2.so
LIBGL: loaded: libEGL.so
LIBGL: Using GLES 2.0 backend
LIBGL: Hardware Full NPOT detected and used
LIBGL: Extension GL_EXT_blend_minmax detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Substract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_OES_mapbuffer detected
LIBGL: Extension GL_OES_element_index_uint detected and used
LIBGL: Extension GL_OES_packed_depth_stencil detected and used
LIBGL: Extension GL_OES_depth24 detected and used
LIBGL: Extension GL_OES_rgb8_rgba8 detected and used
LIBGL: Extension GL_EXT_multi_draw_arrays detected
LIBGL: Extension GL_EXT_texture_format_BGRA8888 detected and used
LIBGL: Extension GL_OES_depth_texture detected and used
LIBGL: Extension GL_OES_texture_stencil8 detected and used
LIBGL: Extension GL_EXT_texture_rg detected and used
LIBGL: Extension GL_OES_texture_float detected and used
LIBGL: Extension GL_OES_texture_half_float detected and used
LIBGL: Extension GL_EXT_color_buffer_float detected and used
LIBGL: Extension GL_EXT_color_buffer_half_float detected and used
LIBGL: Extension GL_OES_fragment_precision_high detected and used
LIBGL: Max vertex attrib: 16
LIBGL: Extension GL_OES_standard_derivatives detected and used
LIBGL: Extension GL_OES_get_program detected and used
LIBGL: Number of supported Program Binary Format: 1
LIBGL: Max texture size: 4096
LIBGL: Max Varying Vector: 15
LIBGL: Texture Units: 8(8), Max lights: 8, Max planes: 6
LIBGL: Extension GL_EXT_texture_filter_anisotropic detected and used
LIBGL: Max Anisotropic filtering: 2
LIBGL: Hardware vendor is Imagination Technologies
LIBGL: ignore MipMap
LIBGL: Targeting OpenGL 2.0
LIBGL: Not trying to batch small subsequent glDrawXXXX
LIBGL: try to use VBO
LIBGL: FBO workaround for using binded texture enabled
LIBGL: glX Will try to recycle EGL Surface
LIBGL: Current folder is:/


this file is from the "boat_output.txt" btw

**Comment by 321goahhhhhhhhhh** [comment]
all so i fixed the problem in my pc by a missing file
its the official minecraft java so it Might be a missing file or you know something else

**Comment by ASGAMING009** [comment]
That file was in runtime maybe or in your version if its say some files are missing when you start the Game download the version again ok.

**Comment by 321goahhhhhhhhhh** [comment]
ok just a sec

**Comment by 321goahhhhhhhhhh** [comment]
it crashed

**Comment by 321goahhhhhhhhhh** [comment]
also that pc version had a "bin" folder thats where i found the missing file in the pc version of minecraft.

**Comment by 321goahhhhhhhhhh** [comment]
here is the file that was missing at the bin

opengl32.dll

**Comment by AyHa1810** [comment]
@321goahhhhhhhhhh well that bin folder is the folder where the official launcher keeps game's natives temporarily each time you launch the game. Als don't worry because those natives are already included in the runtime pack which is especially build for android. Your problem might be the OpenGL issue.

**Comment by SlerianDL** [comment]
https://community.esri.com/t5/esri-india-questions/java-lang-runtimeexception-createcontext-failed-egl-success/td-p/564772

Looking into it seems like this is a problem with some phones not giving out their OpenGL information properly to the application. I can't see much a solution other than maybe a phone update. As it might update the drivers for the PowerVR 8320 GPU.

**Comment by 321goahhhhhhhhhh** [comment]
So what does that mean?

**Comment by 321goahhhhhhhhhh** [comment]
Also it works on this older phone running Minecaft 1.12.2 so it might be the newer phone has an "Older" Version of  OpenGL?
![1612241701710-1387539604](https://user-images.githubusercontent.com/76249004/106554296-04612400-6556-11eb-8a2d-d192765426e2.jpg)

So yea

**Comment by 321goahhhhhhhhhh** [comment]
Also the android version of the older phone is 

5.1.1

**Comment by 321goahhhhhhhhhh** [comment]
Why no response??? Are you making progress?

**Comment by 321goahhhhhhhhhh** [comment]
NVM
