### ISSUE TITLE
can't connect to servers

### ISSUE THREAD

**Issue by nikosger** [AOF-Dev/MCinaBox#915]
i can't connect to servers I use WiFi and mobile data and neither of them are working what I can do

**Comment by StwfGT** [comment]
Use minecraft server status
Here is the link
https://mcsrvstat.us/
And type your ip server you want Like
mc.mineland.com
And scroll down
Pick a server debug info
And copy the hostname
![IMG_20210206_202229](https://user-images.githubusercontent.com/76163976/107118003-1544c900-68b9-11eb-90cb-b3c05d77eccb.jpg)

**Comment by StwfGT** [comment]
If you can't, nevermind

**Comment by StwfGT** [comment]
Or your wifi or mobile data was run out

**Comment by vnmn2611** [comment]
> Use minecraft server status
> Here is the link
> https://mcsrvstat.us/
> And type your ip server you want Like
> mc.mineland.net
> And scroll down
> Pick a server debug info
> And copy the hostname
> ![IMG_20210206_202229](https://user-images.githubusercontent.com/76163976/107118003-1544c900-68b9-11eb-90cb-b3c05d77eccb.jpg)

Hey, thank you so much! This helped me out and now I can play on any server! Have a nice day and stay safe! :D

**Comment by StwfGT** [comment]
No problem:D

**Comment by nikosger** [comment]
OK thanks my problem is now solved
