### ISSUE TITLE
一个要求?

### ISSUE THREAD

**Issue by FurryRbl** [AOF-Dev/MCinaBox#917]
触摸问题,点一下屏幕放置方块,长按破坏,希望按键跟基岩版一样,物品栏也是,长按丢弃

**Comment by CosineMath** [comment]
点一下放置方块、长按破坏应该已经添加了，请仔细查看设置。长按丢弃会在将来加入。更多仿PE的操作仅MCinaBox是不能做到的需要设计一个mod配合。
