### ISSUE TITLE
Mod能否调用android SDK

### ISSUE THREAD

**Issue by Coloryr** [AOF-Dev/MCinaBox#919]
原本想用javax.sound.sampled.AudioFormat来播放自定义音频，但是找不到任何设备，后来想用android.media.MediaPlayer，同时也找不到类，不知道这是不是bug

**Comment by CosineMath** [comment]
如果需要其实可以实现调用Android sdk，但不应该这么做。

**Comment by CosineMath** [comment]
javax.sound不能使用是一个bug，可能会在之后的版本关注这个问题。

**Comment by Coloryr** [comment]
关键是找不到Android的类

**Comment by CosineMath** [comment]
本来就是这样的。pc上有Android的类吗？

**Comment by CosineMath** [comment]
Android那些类又不是java虚拟机加载的。

**Comment by CosineMath** [comment]
你可以通过修改boat或jdk来把一些Android API暴露给MC

**Comment by Coloryr** [comment]
我自己构建不了。

**Comment by CosineMath** [comment]
可能在后续完善jdk时修复jsound。
