### ISSUE TITLE
I don't know how to use forge pls help

### ISSUE THREAD

**Issue by Yes160** [AOF-Dev/MCinaBox#930]
I installed some mods and played a bit. I want to play with a modpack. I have downloaded the server and put all files in the correct place. When I started the game i had to remove the client files because of crash.
Where do I put client files?

**Comment by jianren818** [comment]
There are some problems with this application at the moment. 
First, it can't load many mods at the same time. 
And then because of the runtime problem, Some modules can't be played or need to modify the config.

**Comment by Yes160** [comment]
What should I do?

**Comment by Yes160** [comment]
I tried to put the client files in: Internal shared storage>MCinaBox>gamedir>local>client
It still does not work

**Comment by jianren818** [comment]
> What should I do?

Wait for the app to be perfected.  
At present,  this app is more suitable for scattered plus a few mod to play or to play with the vanilla server.

**Comment by Yes160** [comment]
Is 100 mods too much?

**Comment by jianren818** [comment]
> Is 100 mods too much?

I haven't tried.   But there are a lot of them.

**Comment by jianren818** [comment]
> Is 100 mods too much?

Yes
