### ISSUE TITLE
Installer feature

### ISSUE THREAD

**Issue by kimsmith65** [AOF-Dev/MCinaBox#933]
Can you add a feature that fabric installer are compatible?, Not just forge.

Because I've downloaded the version 1.16 but i can't put any mods in it, and that's because forge installer doesn't work, same as fabric installer

Can you add that feature?

(Sorry about my english 😊)

**Comment by jianren818** [comment]
They said that both forge and fabric worked well in the test environment.  We need to wait.

**Comment by kimsmith65** [comment]
But for me it doesn't work, it doesn't work on ver. 0.1.4-p5.
![Uploading Screenshot_2021-02-10-08-44-04-36_4cb6582af5c3b01ac644d295dc92f43e.jpg…]()
(Thanks for the reply 😊)

**Comment by MatheusTgamerPro** [comment]
> But for me it doesn't work, it doesn't work on ver. 0.1.4-p5.
> (Thanks for the reply 😊)

He told You that it worked on the TEST versions not the Pre-realese or Realese version.

**Comment by jianren818** [comment]
> > But for me it doesn't work, it doesn't work on ver. 0.1.4-p5.
> > (Thanks for the reply 😊)
> 
> He told You that it worked on the TEST versions not the Pre launch or oficial.

You're right.

**Comment by Simeonlps** [comment]
well fabric does run I guess

I manually added libraries, jars etc, I just haven't gotten past the "preparing jars on first launch" Part yet

**Comment by kimsmith65** [comment]
Ok, I'll just gonna wait for the full release.
I can still play minecraft even though i don't have forge/fabric
