### ISSUE TITLE
华为手机无法启动

### ISSUE THREAD

**Issue by EnderTheCoder** [AOF-Dev/MCinaBox#934]
**Describe the crash**
使用华为Nova5Pro运行软件启动时显示检测到系统架构与运行库架构不符
**To Reproduce**
Steps to reproduce the crash:
1. 配置好所有项目
2. 启动然后崩溃闪退
**Expected behavior**

**Screenshots**

**Smartphone (please complete the following info

rmation):**
 - Device: [Huawei Nova5Pro]
 - OS: [e.g. Android 10]
 - App Version [e.g. v0.1.4-p5]
 - CPU architecture [e.g. arm64]  

**Additional context**

**Comment by jianren818** [comment]
请为您的设备安装正确的平台。（如果您的设备仅支持 arm32，则只能安装 mcinabox arm 32。如果您的设备支持 arm64，则您可以安装 mcinabox arm 64  和 mcinabox arm 32）
请为 mcinabox 导入正确的运行时。( aarch32 ->mcinabox-arm32 , aarch64 -> mcinabox-arm64 )

**Comment by EnderTheCoder** [comment]
两种运行库都尝试了，但是闪退

**Comment by MatheusTgamerPro** [comment]
> 两种运行库都尝试了，但是闪退

You also installed the right Apk?

**Comment by EnderTheCoder** [comment]
I downloaded the latest apk from release page.  it's not working the still.  is there anything special with Huawei's processer?

**Comment by EnderTheCoder** [comment]
if i ignore the warning and launch, the game will crash instantly.

**Comment by jianren818** [comment]
华为的处理器没有任何特别之处——因为我就是一名华为用户
在导入运行库旁边按清理键清理干净，重新导一次试试？

**Comment by EnderTheCoder** [comment]
问题解决了，是自动分配的内存大小有问题导致游戏崩溃
