### ISSUE TITLE
Crash when with pixelmon mod

### ISSUE THREAD

**Issue by Random-personn** [AOF-Dev/MCinaBox#955]
Whenever I press start the game the 1.12.2 forge version
It would start up fine, but when I include the pixelmon mod it would start up but get stuck at the Mojang loading screen and crash.

Is there anyway to fix this?

**Comment by MutantJaylen** [comment]
> Whenever I press start the game the 1.12.2 forge version
> It would start up fine, but when I include the pixelmon mod it would start up but get stuck at the Mojang loading screen and crash.
> 
> Is there anyway to fix this?

Some mods dont work with mcinabox yet. We just have to wait for another update that may fix it.

**Comment by jianren818** [comment]
The runtime is not complete.  There are still many bug. They might fix it.

**Comment by TSaltedfishKing** [comment]
> The runtime is not complete. There are still many bug. They might fix it.

you are right

**Comment by Random-personn** [comment]
You right
