### ISSUE TITLE
Future 未来计划

### ISSUE THREAD

**Issue by TSaltedfishKing** [AOF-Dev/MCinaBox#957]
# We're still here.
# 我们还在
# we are rebuilding MCinaBOX
## 请不要回复这个议题

**Comment by TSaltedfishKing** [comment]
之前的问题我们会尝试修复的
但是可能进度比较缓慢
> jvm学业繁忙
> 大部分开发者是学生，马上寒假就过去了
在接下来的一段时间，项目可能停滞不前，但是我们并没有放弃这个项目

**Comment by TSaltedfishKing** [comment]
待解决的问题

**Comment by TSaltedfishKing** [comment]
test hook

**Comment by TSaltedfishKing** [comment]
/

**Comment by ModernTuring** [comment]
@TSaltedfishKing Are your really the developer?
Some issues has been solved already and some of them don't exist at all.

**Comment by ModernTuring** [comment]
@TSaltedfishKing I don't think this is a meaningful plan. In fact, longjunyu2 has exited AOF-dev. At present, mcinabox is still the best front-end of boat, although its development pauses now.
