### ISSUE TITLE
iOS Support (Jailbroken-Only)

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [AOF-Dev/MCinaBox#965]
Can you make this app for iOS for those who are Jailbroken because OpenJDK 16 for iOS has already been made so I think in time at least the first project (MCinaBox) for iOS could be made

**Comment by artdeell** [comment]
Fun Fact: Pojav is already first on iOS.

**Comment by LegacyGamerHD** [comment]
> Fun Fact: Pojav is already first on iOS.

yes indeed

**Comment by admin-elvistrujanovic** [comment]
But maybe MCinaBox could be better on iOS

**Comment by CosineMath** [comment]
Sorry to tell you no plan for iOS currently.
