### ISSUE TITLE
Forge does not install sometimes

### ISSUE THREAD

**Issue by NBGReal** [AOF-Dev/MCinaBox#967]
![Screenshot_20210221_143730_com aof mcinabox](https://user-images.githubusercontent.com/79307418/108625255-8e642480-7452-11eb-9e0b-0b7780dd7a7b.jpg)
This appears when trying to intall Forge 1.10.2.
idk why i can't install it.
Does somebody has a suggestion, of what i can do?

**Comment by IzDarkFlame** [comment]
Do you download the installer version?

**Comment by NBGReal** [comment]
> Do you download the installer version?

I discovered that some forge versions need  the installer and some the universal

**Comment by ThatGifIsNice** [comment]
Try a different download server and try both installer and universal

**Comment by Briliant391** [comment]
![Uploading Screenshot_20210916_121320.jpg…]()

Mine Appear to when install forge 1.12.2
