### ISSUE TITLE
How to delete a previous version of minecraft

### ISSUE THREAD

**Issue by benthetechguy** [AOF-Dev/MCinaBox#979]
I installed a snapshot then a newer one came out. How do I delete the older snapshot?

**Comment by MatheusTgamerPro** [comment]
Go to "All Versions" Search for the Snapshot and Click the "Trash" icon Done!

**Comment by benthetechguy** [comment]
Sorry if I'm being incredibly dumb and not noticing something, but where is the trash icon? I'm on 0.1.3 btw
![Screenshot_20210223-184336_MCinaBox](https://user-images.githubusercontent.com/29379327/108923662-36baea00-7607-11eb-9a38-17e377db3a08.jpg)

**Comment by RaydanOMGr** [comment]
> Sorry if I'm being incredibly dumb and not noticing something, but where is the trash icon? I'm on 0.1.3 btw
> ![Screenshot_20210223-184336_MCinaBox](https://user-images.githubusercontent.com/29379327/108923662-36baea00-7607-11eb-9a38-17e377db3a08.jpg)

You could delete the folder of the version

**Comment by benthetechguy** [comment]
Where would I find the version folder? It isn't in
`/sdcard/Android/com.aof.mcinabox/files/MCinaBox` anywhere from what I can
tell.

**Comment by zhangjing-GitHub-Code** [comment]
You can find the version folder in "Game menu/GAME DIRECTORIES".The directory you say is MCinabox's privite folder. Version folder(game directory) default sets to public directory.

**Comment by benthetechguy** [comment]
OK, thanks. I found and deleted the snapshot.
