### ISSUE TITLE
How can i enter in a server? (If it's possible.)

### ISSUE THREAD

**Issue by Davinsel** [AOF-Dev/MCinaBox#982]

**Comment by artdeell** [comment]
Do it as you do on PC.

**Comment by Davinsel** [comment]
> Do it as you do on PC.

I do but the servers aren't working

**Comment by artdeell** [comment]
Some servers aren't working because SRV record resolving is broken. You can go to https://mcsrvstat.us, key in your server IP, show the debug information and type in IP and port from it instead of the original ones

**Comment by Davinsel** [comment]
Thx
