### ISSUE TITLE
Forge installer....How to use it?

### ISSUE THREAD

**Issue by CloserPopcorn20** [AOF-Dev/MCinaBox#99]
Read the title.

**Comment by Soul-Void** [comment]
download forge-(verxxx)-universal.jar file and place it under Android/data/com.aof.mcinabox/files/MCinaBox/forgeinstaller

then go to launcher configuration in-app and set forge version you desire, click install, and be patient
once download is done, attempt to start forge, it will most likely crash.

if it does crash, go to your file manager (I use Astro), enable viewing of hidden files in settings , then navigate to MCinaBox/.minecraft/config and edit splash.properties to say enabled=false, then try launching again (note that this is the mcinabox folder in root storage, not under /Android).

let me know if you have any questions

**Comment by CloserPopcorn20** [comment]
![Screenshot_2020-04-19-21-26-21-348_com aof mcinabox](https://user-images.githubusercontent.com/63425498/79696279-7fd23d00-8284-11ea-95d6-f92836ea34b7.jpg)
Error, what is this mean?

**Comment by blissband123** [comment]
The config folder wont show

**Comment by gabbosta** [comment]
What is the maximum memory I have to put to run smooth

**Comment by Soul-Void** [comment]
> The config folder wont show

Have you tried running the game first?

**Comment by Soul-Void** [comment]
> 
> ![Screenshot_2020-04-19-21-26-21-348_com aof mcinabox](https://user-images.githubusercontent.com/63425498/79696279-7fd23d00-8284-11ea-95d6-f92836ea34b7.jpg)
> Error, what is this mean?
> 
> 

Change download source

**Comment by Soul-Void** [comment]
> What is the maximum memory I have to put to run smooth

Max varies by device (950mb for me is max)
256-500 should be fine, just keep render distance to 8 or lower so you don't use too much ram

Also be sure to turn mipmapping completely off, as it causes bad frame drops

**Comment by Soul-Void** [comment]
Also when running forge after editing splash.config to say enabled=false, the screen will be black for a little while before it loads. 

Be patient, and remember that 1.14 and up has render issues, and versions below 1.6 (I believe, check readme) don't work.

**Comment by gabbosta** [comment]
But I put it in 1024 but it still closes sometimes, with the mods "Decocraft, Craft Architecture, Wallpapers Craft, Carpenters Block, Better FPS and Optfine" all in 1.7.10 and I have 3 gb of ram

**Comment by CloserPopcorn20** [comment]
Well, thank you so much :)

**Comment by CloserPopcorn20** [comment]
Oh wait, why on version 1.9+ don't playing sounds and, in resource packs ,,not found pack.mcmeta"?

**Comment by longjunyu2** [comment]
#94

**Comment by issuereporter292** [comment]
> > What is the maximum memory I have to put to run smooth
> 
> Max varies by device (950mb for me is max)
> 256-500 should be fine, just keep render distance to 8 or lower so you don't use too much ram
> 
> Also be sure to turn mipmapping completely off, as it causes bad frame drops

Since I have 12 gb of ram how much should I put in?

**Comment by Sergii03** [comment]
Forge on version 1.7.10, crashed.

**Comment by Soul-Void** [comment]
> > > What is the maximum memory I have to put to run smooth
> > 
> > Max varies by device (950mb for me is max)
> > 256-500 should be fine, just keep render distance to 8 or lower so you don't use too much ram
> > 
> > Also be sure to turn mipmapping completely off, as it causes bad frame drops
> 
> Since I have 12 gb of ram how much should I put in?

I have 12gb ram as well, but the way Android allocates ram to apps limits the max we can use

**Comment by Scallysnix** [comment]
> download forge-(verxxx)-universal.jar file and place it under Android/data/com.aof.mcinabox/files/MCinaBox/forgeinstaller (it absolutely MUST be the universal.jar!)
> 
> then go to launcher configuration in-app and set forge version you desire, click install, and be patient
> once download is done, attempt to start forge, it will most likely crash.
> 
> if it does crash, go to your file manager (I use Astro), enable viewing of hidden files in settings , then navigate to MCinaBox/.minecraft/config and edit splash.properties to say enabled=false, then try launching again (note that this is the mcinabox folder in root storage, not under /Android).
> 
> let me know if you have any questions

Would you assist me?

**Comment by JE55E6arlow** [comment]
> Also when running forge after editing splash.config to say enabled=false, the screen will be black for a little while before it loads.
> 
> Be patient, and remember that 1.14 and up has render issues, and versions below 1.6 (I believe, check readme) don't work.
> 
> If you want optifine, go to .minecraft and create the mods folder, then paste optifine within

I did everything, but for some reason there is no ".minecraft" folder. I looked up YouTube videos and they have it too, but not me. Do you know why?

**Comment by Crafer32** [comment]
Forge installation always fails, says download failed and doesn't work.
ps = My device is an Oppo Find X2 Pro with Android 10.
