### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by GavinKacprowicz** [AOF-Dev/MCinaBox#990]
I have tried the forge parameters and forge still isn't working. How do I get it to work?

**Comment by ZianDaTester** [comment]
Me too

**Comment by KUALALUM** [comment]
> I have tried the forge parameters and forge still isn't working. How do I get it to work?

Enable debugging option goto gamelist click the global game setting

**Comment by GavinKacprowicz** [comment]
I'm still just getting a white screen. Have I done something wrong?

**Comment by KUALALUM** [comment]
Same
